### ISSUE TITLE
Implementing TOTP time-based one time passwords

### ISSUE THREAD

**Issue by jkleckner** [Tunnelblick/Tunnelblick#267]
TOTP is the method used by Google Authenticator and Authy for 2-factor authentication.

I'm now using a VPN that requires this and so am running both Tunnelblick and OpenVPN Connect but I would much rather use Tunnelblick.

Are there any tips to make this work or plans to add it?

**Comment by jkbullard** [comment]
There are no plans to add it, but anyone is welcome to contribute patches to do so.

This isn't an "Issue"; the best place to discuss it would be the [Tunnelblick Discussion Group](https://groups.google.com/forum/#!forum/tunnelblick-discuss).

**Comment by jkleckner** [comment]
Got it, thanks.

**Comment by jeffwidman** [comment]
Personally I think this is indeed an "issue", although more of a "enhancement / feature" rather than a "bug". 

It's a lot easier to track progress against the specific features that I care about on projects by  subscribing to an issue here on Github rather than subscribing to the overall project email list. I also know when I'm considering contributing to a Github-based project, I often take a look through the outstanding issues to see what I might be able to tackle. 

So maybe you'd consider re-opening this?

**Comment by jkleckner** [comment]
FYI, [here](https://groups.google.com/forum/#!topic/tunnelblick-discuss/7JI4CgW8WWI) is a discussion group topic that appears connected that gets into details about how to use a pluggable authentication module one of which is TOTP.  In that post, the person is trying to get DuoSecurity implemented.

**Comment by llange** [comment]
I tried to implement basic support for the challenge/response protocols which are already built-in into OpenVPN.
There are two protocols (one static which needs that the config file has the info that a challenge/response mechanism is in place, one dynamic where the servers asks for the challenge/response after a successful authentication).
For the moment I only committed support for the static one (config file), because I still have issues with the dynamic one ; but I will eventually also commit support for the dynamic protocol.

You can [find the code here](/llange/Tunnelblick/tree/handle_challenge_response_protocols). Be warned that code quality is certainly not on par with the rest of Tunnelblick as I don't know Objective-C nor the object/threading model of Tunnelblick, so design choices (popup window handling, etc...) may not be acceptable as-is.
Consider it as a Proof-of-Concept that it can be done - it certainly needs updates and is not ready for inclusion.

For the moment I have it working with OpenVPN AS + Google Authenticator 2FA (which is a TOTP mechanism).

Any feedback is welcome.

**Comment by jkbullard** [comment]
Thanks. I will look at this.

**Comment by jkbullard** [comment]
Thanks again. I will add implementing this to my list (which is pretty long).

Your code looks pretty good, actually, but it does block the main Tunnelblick thread, and it's tricky to avoid that. There are architectural problems with the way that Tunnelblick does this, so it isn't your "fault", and it is painful even for me to do (which is why I'm not doing it right now).

I'll leave this open until I do something about it.

**Comment by robertlilje** [comment]
I am using openVPN server that requires TOTP from Google-Authenticator Lib on the server side. TunnelBlick allows me to connect without any issues. The VPN was setup about 2 years ago, and I (our entire office) have since been using TunnelBlick without hiccup.

**Comment by midN** [comment]
@jkbullard Any news on that? Would be really great to have such feature since OpenVPN has a built-in feature for Google oAuth already.

P.S @llange Thank you for the branch with the fix/feature, built from source and works perfectly.

**Comment by jkbullard** [comment]
No, sorry, no news. Busy with other things.

**Comment by hryamzik** [comment]
@jkbullard how about merging this as is and opening a different issue about that thread lock? Currently you can't connect with 2fa at all.

**Comment by llange** [comment]
@hryamzik - without the patch, there may be the possibility (untested but I think I read it somewhere) to use, instead of (just) your password, the concatenation of "password" + "2fa code" (no spaces). Does it work ?

**Comment by hryamzik** [comment]
Nope, that doesn't work in my case. I'll try to build from your branch a bit later.

**Comment by midN** [comment]
Any updates on it? I had to move over to Viscosity because it's not implemented after 3 years :)

**Comment by hryamzik** [comment]
FYI, I've created a PR #430.

**Comment by jkbullard** [comment]
4c1dbde99314ab0b67c70f3f8e4b13572fc0ca58 implements static challenge/response, and 4c1dbde99314ab0b67c70f3f8e4b13572fc0ca58 implements dynamic challenge/response, so I'm closing this.

**Comment by jkbullard** [comment]
Closed because static and dynamic challenge/response are implemented in 4c1dbde99314ab0b67c70f3f8e4b13572fc0ca58 and 2d9f0e4159c66288600a468c468f9729869d025a, respectively.
