### ISSUE TITLE
'openssl/evp.h' file not found issue when build project with xcode 7.0

### ISSUE THREAD

**Issue by iloveopen** [Tunnelblick/Tunnelblick#277]
hi, when build project with xcode 7.0, compile issue 'openssl/evp.h' file not found in SUDSAVerifier.m.

Any update for this ?

**Comment by jkbullard** [comment]
Not yet.

Here's the problem, as I understand it: The OS X 10.11 SDK included in Xcode 7 does not include the standard OpenSSL headers. SDKs in versions of Xcode before 7 include the OpenSSL headers. Although the rest of the third_party software is built using the headers from the copy of OpenSSL that has been built for Tunnelblick, Sparkle apparently relies on the headers being built into the SDK, so it won't build if those headers are not present.

Building with Xcode 6 should still work, but I haven't verified that.

I would welcome a good patch to fix this. Some tips for anyone who wants to do that:

  * All the files that are involved are in the "third_party" folder

  * The headers are located (after OpenSSL is built) in
     $(OPENSSL_STAGING_DIR)/include/$$a/openssl
    where $(OPENSSL_STAGING_DIR) is a make variable, and $$a is the script
    variable which contains the architecture of the current build.

  * The make process works as follows: Makefile determines the version of Xcode being used, then includes either Makefile-Xcode3 or Makefile-Xcode4andUp. Each of these makefiles set some make variables such as TARGET_ARCHS, and then include Makefile-common, which is the main makefile and does all the work.

  * Makefile-common builds Sparkle before it builds OpenSSL. That needs to be changed because OpenSSL needs to be built so the headers exist when Sparkle is built. It's a trivial change to swap two lines (but deal with the line continuation slashes appropriately, too, of course).

  * Sparkle.xcodeproj needs to be modified (in an Xcode-independent manner, and by creating an additional patchfile for Sparkle's source code, which is expanded from the standard Sparkle .zip at build time) to use the headers created in the OpenSSL build process.

  * The patchfiles for Sparkle are located in
     …/sources/patches/sparkle/
and they are applied serially by "Makefile-common".

**Comment by jkbullard** [comment]
Also:

  * To run on OS X 10.11 (because I think 10.11 does not include the OpenSSL library *binaries*), it will be necessary to static link the Sparkle.framework to the Tunnelblick-built OpenSSL binaries, which is what we do when building OpenVPN itself.

**Comment by jkbullard** [comment]
To get the headers working, probably the cleanest way would be to have Makefile-common create a folder in the Sparkle source with symlinks to the header folder for each architecture, and change the Sparkle SUDSAVerifier.m code to reference the headers in that folder (which will then be in a known path which is relative to the source code).

For example:

(1) Have Makefile-common create a folder
     "third_party/build/sparkle-1.5b6/Extras/Source Code/openssl-headers"
and then (into that folder) put a symlink for each architecture to the folder with the headers for that architecture.

(2) Change the lines in SUDSAUpdater.m to look like
     include "openssl-headers/ARCHevp.h"
where "ARCH" is the Xcode variable with the current architecture. (I don't know what that variable is offhand.)

I hope all this helps someone get this working, and that they then contribute their fix back to the project.

**Comment by iloveopen** [comment]
well, I try to compile openssl manually and copy the include folder to mac SDK folder, and then build pass

**Comment by jkbullard** [comment]
The problem with that is that the headers you build with (from OpenVPN 1.0.2) may not be compatible with the binary library that OS X may dynamically link the Tunnelblick binary to. I seem to remember something about that being a problem when someone else created the DSA signature with a more modern version of OpenVPN. Then they found it didn't work with the (older) library that OS X was linking to Tunnelblick. So I think it will be necessary to static link the library to Tunnelblick.
