### ISSUE TITLE
Try with different credential destroys certificate keychain entry

### ISSUE THREAD

**Issue by serge16** [Tunnelblick/Tunnelblick#288]
Hi,
We use a two-factor authentication to connect to our VPN server. The user must type a password and certificate is used too. The passphrase of the certificate is stored in the keychain. If the user types the wrong password, authentication is denied by the server. 
When attempting a second connection after typing the password (the good one), a window appears asking him to retry or "Try with different credential."
If he Click here the passphrase of the certificate in the keychain is destroyed and he can't connect anymore (because he does not know the passphrase).
I think this is not normal behavior. There is no reason to destroy this entry in the keychain, anyway, without asking a clear user confirmation.
I saw the issue [145] (https://code.google.com/p/tunnelblick/issues/detail?id=145), but the problem is still there in the 3.6beta16 release (build 4461).
Thanks for your help

**Comment by jkbullard** [comment]
Thank you for your report and the clear explanation of the problems this is causing your user(s).

The situation you describe is not one that was anticipated when Tunnelblick was written. You are correct that "Try with different credentials" clears *all* of the credentials associated with a configuration, including the passphrase (also known as the "private key"), the username, and the password.

I will investigate fixing this and report back to this Issue 288.

Note: This has nothing to do with [Issue 145](https://github.com/Tunnelblick/Tunnelblick/issues/145), which was fixed in February 2010.

Again, thanks for reporting this problem.

**Comment by jkbullard** [comment]
Thanks again for reporting this problem.

I have just committed 2bcbd90, which fixes this problem and clarifies the language of the buttons that the user must chose when authentication fails. The change will be in the next beta release.

If the username and password are stored in the Keychain but fail to authenticate, the user will be told about the failure and asked to:
  * Cancel
  * Try again with the saved username/password
  * Delete the saved password and try again

If the passphrase (private key) is saved in the Keychain but fails to authenticate, the user will be told about the failure and asked to:
  * Cancel
  * Try again with the saved passphrase
  * Delete the saved passphrase and try again

If the username and password are *not* stored in the Keychain and fail to authenticate, or the passphrase/private key is not stored in the Keychain and fails to authenticate the user will be told about the failure and asked to:
  * Cancel
  * Try again

**Comment by serge16** [comment]
hi,
I tested with the beta 18 and it's OK.
Thank you for this fix and happy New Year.
