### ISSUE TITLE
Should checking "Route all ipv4 through the VPN" force-ignore default gateway sent by server?

### ISSUE THREAD

**Issue by singalen** [Tunnelblick/Tunnelblick#298]
I have ao OpenVPN configuration without `redirect-gateway` instruction. Though, I'm receiving this instruction (`redirect-gateway def1,remote-gateway 193.168.2.1`) from server:

> 2016-02-12 12:25:33 PUSH: Received control message: 'PUSH_REPLY,route 193.168.0.0 255.255.255.0,route 64.62.250.192 255.255.255.224,route 46.51.142.80 255.255.255.240,redirect-gateway def1,remote-gateway 193.168.2.1,dhcp-option DNS 8.8.8.8,route 193.168.2.1,ping 10,ping-restart 120,ifconfig 193.168.2.74 193.168.2.73'
2016-02-12 12:25:33 Options error: Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:5: remote-gateway (2.3_git_417fe4a)

and all my traffic goes through the VPN. I'm pretty sure because Tunnelblick starts showing enormous amounts of traffic over VPN, and my external IP address changes to one inside the VPN network.

Should `"Route all ipv4 through the VPN"` override this server command?

I've found [a way to work around it in client configuration](https://community.openvpn.net/openvpn/wiki/IgnoreRedirectGateway). I'm not sure what those `128.0.0.0` networks are. Anyway, shouldn't TunnelBlick do it?

**Comment by jkbullard** [comment]
From the program's help entry for "Route all ipv4 through the VPN":
<blockquote>When checked, a '--redirect-gateway def1' option is sent to OpenVPN, causing routing to be set up to route all IPv4 traffic through the VPN. If this is not checked, all IPv4 traffic may still be sent through the VPN because the OpenVPN configuration file may contain the option, or the option may be "pushed" from the VPN server.
</blockquote>

Tunnelblick doesn't provide a way to override a pushed '--redirect-gateway' because that option is often used for security purposes and should not be overridden. If some traffic goes through the VPN and some doesn't, there are ways that the LAN on the other side of the VPN can be attacked from the Internet. Quite reasonably, that is not acceptable.
