### ISSUE TITLE
Support for "static-challenge"

### ISSUE THREAD

**Issue by akhenakh** [Tunnelblick/Tunnelblick#300]
Tunnelblick 3.5.8 does not support `static-challenge` openvpn directive.

Is there someone working on it?

**Comment by jkbullard** [comment]
Tunnelblick is open source, so who knows?

But as far as I know, nobody is working on implementing the "Challenge/Response Protocol".

It isn't available in OpenVPN GUI, either, according to [OpenVPN Ticket #525](https://community.openvpn.net/openvpn/ticket/525).

**Comment by akhenakh** [comment]
it works on the OpenVPN Connect client, but this client is terrible.
I'll dig more into it.

**Comment by llange** [comment]
I tried to implement basic support for the challenge/response protocols which are already built-in into OpenVPN.
There are two protocols (one static which needs that the config file has the info that a challenge/response mechanism is in place, one dynamic where the servers asks for the challenge/response after a successful authentication).
For the moment I only committed support for the static one (config file), because I still have issues with the dynamic one ; but I will eventually also commit support for the dynamic protocol.

You can [find the code here](/llange/Tunnelblick/tree/handle_challenge_response_protocols). Be warned that code quality is certainly not on par with the rest of Tunnelblick as I don't know Objective-C nor the object/threading model of Tunnelblick, so design choices (popup window handling, etc...) may not be acceptable as-is.
Consider it as a Proof-of-Concept that it can be done - it certainly needs updates and is not ready for inclusion.

For the moment I have it working with OpenVPN AS + Google Authenticator 2FA (which is a TOTP mechanism).

Any feedback is welcome.

**Comment by hryamzik** [comment]
Hey @llange, did you manage to make it work?

**Comment by llange** [comment]
Hello @hryamzik ; yes it did work since that time I made the patch ; and at some point I was using it daily / weekly (I'm not using it that much at the moment - but it still works, tested it last december).

**Comment by hryamzik** [comment]
FYI, I've created a PR #430.

**Comment by jkbullard** [comment]
PR #464 adds static challenge/response support.

**Comment by jkbullard** [comment]
Closed because static and dynamic challenge/response are implemented in 4c1dbde99314ab0b67c70f3f8e4b13572fc0ca58 and 2d9f0e4159c66288600a468c468f9729869d025a, respectively.
