### ISSUE TITLE
DNS for split-tunnel configuration overwrites previous resolvers

### ISSUE THREAD

**Issue by xortim** [Tunnelblick/Tunnelblick#305]
Firstly, thanks for the awesome project!

This is more of a behavioral question/issue. Serving DNS, assigned via DHCP is a common practice. The tunnelblick up/down scripts handle assigning the DNS servers to the host machine, however it appears that resolvers that were previously defined are no longer used after connecting to the VPN.

Is it possible to append the DNS resolvers to the hosts' existing resolvers?

The scenario in which this is needed:
- Corporate network employs split-DNS. Ex: mail.company.com internally resolves to 192.x.x.x, and externally it resolves to 68.x.x.x.
- OpenVPN has been set up on a hosted network such as EC2 or RackSpace to provide access into this environment.
  - DNS is configured inside of this environment.
  - DHCP sets the name server.
  - Split Tunnel is enabled to allow users to access the internal resources of the company such as git.company.com.

When connected, the DNS settings which resolves internal addresses for the internal resources are no longer resolving, instead they are resolving to their public addresses if available.

Without disabling split tunnel, is it possible to use another DHCP option that Tunnelblick will honor to append the VPNs resolvers (which don't forward requests for other zones).

Ideal state is that if the nameservers prior to connecting to the VPN are:
- 192.168.1.1
- 192.168.2.1

And the DNS resolvers set by the VPN are:
- 172.16.1.1
- 172.16.1.2

Then the VPN client would have the following resolvers:
- 192.168.1.1
- 192.168.1.2
- 172.16.1.1
- 172.16.1.2

Is this possible using TunnelBlick as the client?

**Comment by jkbullard** [comment]
It is not possible unless you create customized up/down scripts (see [Using Scripts](https://tunnelblick.net/cUsingScripts.html)).

However, it isn't as simple as just "appending additional resolvers". OS X and Windows treat multiple nameservers very differently. On OS X, only the first resolver is used for queries until it fails (that is, fails to return any answer at all). If/when that happens, OS X starts using the second nameserver and uses it until it fails, etc. On Windows, queries are sent to all nameservers and the answer from the first one that responds is used.

**Comment by xortim** [comment]
Hi @jkbullard - I'm ok with the sequential querying approach that OS X uses as compared to Windows as it's not a timeout and most DNS is pretty fast, it wouldn't really hurt any usability.

Is it not possible to customize the current up/down scripts to support the behavior I've described? Perhaps an option in the interface "do not overwrite local DNS resolvers"? Then, copy the existing DNS resolvers and append the VPN resolvers to that list. I believe a copy of the resolvers is already being performed by those scripts. - though I'm not too familiar with the scutil utility.

**Comment by jkbullard** [comment]
The current up/down scripts could be modified to do as you propose, in fact I think that is better than creating your own up/down scripts from scratch. Just copy them out of source code or from a Tunnelblick binary. See [this Tunnelblick Discussion Group post](https://groups.google.com/d/msg/tunnelblick-discuss/7GaWje4EtyM/dP-ytzTZAwAJ), which describes the scripts and where they may be found.

However, I'm not sure I have explained the DNS query process on OS X clearly. If the first nameserver on the list returns a result, any result, that result will be used, even if it is "no such domain known". The second nameserver will only be used if the first one does not respond, and that would imply not having received a response within the timeout period, which is something like 30 seconds.

**Comment by xortim** [comment]
@jkbullard - that makes a much more sense. This will definitely take some testing. Perhaps shipping a portable version of dnsmasq that can handle DNS more predictably would be the long-term solution.

**Comment by alexchandel** [comment]
@jkbullard The expectation is that only certain resolvers will work for certain search domains. This is common. OpenVPN should not stomp previous resolvers (or should at least provide scripts which append rather than stomping nameservers), due to the common case of multiple VPN connections and/or the client-only subnet having an internal DNS server.

However, you can even get around the constraint that higher-priority resolver mustn't resolve the wrong search domain by using `/etc/resolv` files. Tunnelblick could easily create an `/etc/resolv/internal.example.com` upon connection and delete it upon disconnection.

**Comment by jkbullard** [comment]
@alexchandel - 

 1. multiple VPN connections are *not* common. The most common use of a VPN is to tunnel all traffic.

 2. OS X (now macOS) does not use /etc/resolv for networking, it has its own mechanism.

**Comment by alexchandel** [comment]
@jkbullard 

> multiple VPN connections are not common. The most common use of a VPN is to tunnel all traffic.

I'd disagree with that out of experience. Corporations often have multiple VPNs, and people who deal with multiple organizations often need access to multiple networks in my experience.

> OS X (now macOS) does not use /etc/resolv for networking,

Yes it does (`/etc/resolver` but same thing). OSX/macOS's internal mechanism uses `/etc/resolver` entries if you put them there.

**Comment by jkbullard** [comment]
@alexchandel 

Sorry, I didn't clearly express what I meant clearly. I meant that connecting multiple VPNs *simultaneously* is not common.
 * Most individual users just want a single VPN at a time.
 * Although many corporations have multiple VPNs, most corporate users use a single VPN at a time (and usually only a single VPN for a week or month). Most corporate IT departments want all traffic from an employee's BYOD to go through the VPN to avoid security vulnerabilities. Of course network engineers and IT departments overseeing large networks often use multiple VPNs simultaneously, and so do some consultants, some cross-boundary (division, department, etc.) teams, and so on, but that is only a small portion of VPN users.

OS X DNS is manipulated via the "System Configuration" framework, not via the filesystem. *It's not Linux or Unix* -- for example, there is no /etc/resolver folder on a stock OS X system, and the following comment appears in /private/var/run/resolv.conf (which is symlinked to from /etc/resolv.conf):

    # This file is not used by the host name and address resolution
    # or the DNS query routing mechanisms used by most processes on
    # this Mac OS X system.

**Comment by alexchandel** [comment]
@jkbullard 

> Sorry, I didn't clearly express what I meant clearly. I meant that connecting multiple VPNs simultaneously is not common

Ah I see, but connecting to multiple VPNs is not uncommon, especially for those working in the software industry, or in smaller software/engineering places with multiple networks.

> OS X DNS is manipulated via the "System Configuration" framework, not via the filesystem. It's not Linux or Unix -- for example, there is no /etc/resolver folder on a stock OS X system, and the following comment appears in /private/var/run/resolv.conf (which is symlinked to from /etc/resolv.conf):

This isn't completely true either.

OS X's "System Configuration" framework **does** use the filesystem. You're confusing `/etc/resolv.conf` with `/etc/resolver`. They're completely different, and the comment in `/etc/resolv.conf` has no bearing whatsoever on `/etc/resolver`. OS X doesn't create the `/etc/resolver` folder by default because it doesn't need it by default.

However, if you create `/etc/resolver`, it is used by "System Configuration" and works exactly as expected.

Go ahead right now. Create the file `/etc/resolver/test` with these contents:
```
nameserver 127.0.0.1
nameserver ::1
```

I sometimes put a `domain test` line in, but isn't not necessary in this case. Then run `scutil --dns`. You'll see a brand new resolver appended to the list, and OS X will use it when it's reachable for appropriate search queries.

**Comment by jkbullard** [comment]
> However, if you create /etc/resolver, it is used by "System Configuration" and works exactly as expected.
Great! It sounds like you know what you're talking about. How about making a PR for the standard Tunnelblick script to implement it? Or writing up what needs to be done to set up separate nameservers for different domains? Or pointing to some documentation that describes it?

**Comment by alexchandel** [comment]
@jkbullard 

That sounds like a great feature for Tunnelblick. I don't really know how to write Tunnelblick scripts though. My entries in `/etc/resolver` are just hacks to get DNS working on my VPNs. For each VPN, I select `Do not set nameserver` in Tunnelblick and make a file in `/etc/resolver` whose `nameserver` argument is the IP address of what the nameserver should be (from `push "dhcp-option DNS x.y.z.q"` I assume).

I guess I'd want a Tunnelblick script, upon being told to `Set DNS/WINS` for search domain `internal.example.com` to nameserver `192.0.2.1`, to create the file `internal.example.com` with contents:
```
domain internal.example.com
nameserver 192.0.2.1
```

I've heard `/etc/resolver` files have the same syntax as `/etc/resolv.conf`, so other options probably apply.

One point to be resolved is that I already know the search domains of my VPNs in advance when doing my hack, whereas ``push "dhcp-option DNS x.y.z.q"` doesn't tell you it.

**Comment by giox069** [comment]
I have the same problem as in the 1st post:
**a)** I'm in my office, so I'm using my local DNS to resolve hostnames, lets' say that "serv1.myoffice.dom" resolves to a local IP 192.168.10.10
**b)** When I'm outside of my office "serv1.myoffice.dom" resolves with a public IP address of myoffice, so I can reach my office server from the outside using the same hostname.
**c)** Now lets' go back to my office with my MAC, and connect with Tunnelblick to one of my customer's VPN: my mac will start resolve serv1.myffice.dom using external DNS, and this is wrong, because I can't use my office DNS when tunnelblick is active.

This is a common problem for many VPN clients in Mac, Windows and Linux: Split DNS is non correctly implemeped. SplitDNS **must** be implemented by queryng different DNS servers for different domain zones, not using priorities in network cards and hoping that it just works.

The only clients I remember correctly implementing correctly SplitDNS were: the Cisco propietary DNS clients (the Cisco legacy IPsec client for windows) and Ubuntu: Ubuntu uses dnsmasq by default as helping resolver, so some vpn clients are able to instruct dnsmasq to do SplitDNS.

For tunnelblick: is  there a way to use `scutil` to do SplitDNS ?

**Comment by jkbullard** [comment]
@giox069 - Thanks for your comments. You describe the problem well.

I do not know of a way to use scutil to do split DNS. The above [post by alexchandel](https://github.com/Tunnelblick/Tunnelblick/issues/305#issuecomment-250843796) is correct) says it can be done by manipulating files in `/etc/resolver/`, and that looks promising.

Although I have put this on my to-do list, it will probably be a while before it gets into Tunnelblick unless someone else does it.

**Comment by alexchandel** [comment]
@giox069 Yeah the problem isn't that split-DNS is impossible, it's just that no VPN clients do it correctly. `scutil` isn't even necessary here, and it's seems easier without it.

The way an OpenVPN client like Tunnelblick **should** do it is:

1. After a VPN connection is successfully made, if the VPN server pushes a DNS server && domain (let's say `192.168.0.1` and `test`), then

2. Create a file called `/etc/resolver/test` (note the file & domain name are the same) if it doesn't already exist (if it does, do step 3 instead). Its contents should be at least:

```
nameserver 192.168.0.1
domain test
```

3. If it did exist, then there are multiple VPNs offering to resolve this domain, so call your file `/etc/resolver/test.tunnelblick.a` or something. In this case, its contents should be (where `search_order` is higher than whatever `search_order` was in the existent file, if any):
```
nameserver 192.168.0.1
domain test
search_order 400000
```

3. Delete the file after the connection is closed.

There are probably other important parameters that belong in the file and confuse your system unpredictably when missing, but this is the bare minimum to get split-dns working.

**Comment by jkbullard** [comment]
Thanks, @alexchandel, for your clear and concise explanation. I'll put it on my "to do" list. (It's a long list!)

**Comment by FlorinAndrei** [comment]
The solution proposed by @alexchandel would be fantastic. That's the proper way to handle DNS in a VPN context.

**Comment by dragz202** [comment]
What is this solution proposed? I don’t see it; and I have this same problem.

**Comment by jkbullard** [comment]
@dragz202 - @alexchandel describes what needs to be done to implement split tunnels.

My intention is to implement this in Tunnelblick's built-in scripts so it would "just work". But if I have to do it myself it will be a while before it's done -- weeks or months or years (or never).

If you can't wait for this to be implemented in Tunnelblick, you could implement it in your own custom up/down scripts – see [Using Scripts](https://tunnelblick.net/cUsingScripts.html). If you do that, please contribute those scripts to Tunnelblick so everyone could benefit : )

**Comment by cl99** [comment]
Just as an FYI, for anyone that needs DNS split tunneling right away,  I can confirm it works correctly in Viscosity.

**Comment by MarSik** [comment]
The common use case for our company is a home office scenario. Local home connection is used for everything except company private addresses. This means we need to rely on two DNS systems - the ISP one for the public internet and the VPN provided one for internal network.

Our company IT currently recommends (paid) Viscosity over Tunnelblick because of this issue.

**Comment by mikz** [comment]
@jkbullard I wanted to implement this (creating /etc/resolver/domain) in the Tunnelblick User Scripts, but there is no information about DNS/DHCP options available.

Seems I'd have to reverse engineer what `client.up.tunnelblick.sh` does and retrieve the information from `scutil` where tunnelblick "persists" it. Also this script is not evaluated when `Do not set nameservers` is set, so the User Script would also have to reset the default nameserver etc. 
That is extremely complex for just writing a file templated with few options

It would be much easier if those options would be passed as ENV variable to the user scripts.

**Comment by mikz** [comment]
@jkbullard by "options" I mean what is pushed by OpenVPN: DNS servers, DOMAIN, default route, ...
```
'PUSH_REPLY,route-gateway 10.40.204.1,route 10.0.0.0 255.0.0.0,dhcp-option DNS 10.38.5.26,dhcp-option DNS 10.35.255.14,dhcp-option DOMAIN example.com,ping 30,ping-exit 600,explicit-exit-notify 3,topology subnet,ifconfig 10.40.205.74 255.255.252.0,peer-id 315,cipher AES-256-GCM'
```
Tunnelblick takes those options and sets DNS, domain, routes, ... 

`client.up.tunnelblick.sh` code is public and open source, but I don't think 1500 line bash script is maintainable by anyone else than who wrote it. It is complicated because it does complicated things, I understand. It is quite well commented, but still it is has really high contribution barrier.

I can see it uses `scutil` to read/write some metadata and get the DNS servers and domain.
So my script would have to do the same to read/write those values. I imagine it would be much better if 
`client.up.tunnelblick.sh` would be split to smaller parts that are re-usable and do just one thing. 
Also MacOS ships several scripting languages that could be used instead of bash. 

Sorry for not using the correct terminology. I meant the ["Tunnelblick VPN Configuration scripts"](https://tunnelblick.net/cUsingScripts.html#tunnelblick-vpn-configuration-scripts).
What I wanted to do is to:
* create my `connected.sh` and `post-disconnect.sh` scripts
* those scripts would know what DNS servers and domain was pushed by OpenVPN
* `connected.sh` would create `/etc/resolver/${domain}` with proper dns servers
* `post-disconnect.sh` would remove `/etc/resolver/${domain}`

This is really hard to do now as those scripts have no information available about the vpn connection.
And those scripts don't even have information about the interface that was opened, so when "Do not set nameservers" is set it could not even detect the DNS servers/domain because it can't know the interface.

If there is a better way to do this I'm all ears. But from my view the easiest way is to export those `DYN_`, `CUR_`, `FIN_` and other variables as environment for the `connected.sh` and other scripts.
Looks like tunnelblick is getting the information set by `client.up.tunnelblick.sh`:
https://github.com/Tunnelblick/Tunnelblick/blob/44c0515fb82ced0c8cc227ab09b15879937cd1ec/tunnelblick/process-network-changes.m#L101-L126 . Maybe this is some different subprocess, but it is something doable.

My point is that those Tunnelblick scripts are not really useful if they have no information about the tunnel. And if the "Do not set nameservers" option is set all the `foreign_option_` from OpenVPN are lost.

I see that my only way to implement this now is to:
* set "Do not set nameservers" in the configuration
* supply my own `up.sh` 
* possibly call `client.up.tunnelblick.sh` to set up Monitoring etc.

**Comment by jkbullard** [comment]
@mikz - Thanks. I think I understand your situation better.

You're right -- at least _some_ of the information you want is available to Tunnelblick and could be passed on to the "Tunnelblick" scripts such as "post-connect". Thanks for suggesting this.

`client.up.tunnelblick.sh` stores the data needed for the other standard scripts (such as `client.down.tunnelblick.sh` and `leasewatch`) in the System Configuration database (accessed via scutil). So Tunnelblick could extract the data from there and include the data as environment variables in the "Tunnelblick" scripts. The data is stored in lines 666-707 of `client.up.tunnelblick.sh`.

It might be necessary to have `client.up.tunnelblick.sh` store additional info, though, since it currently only stores the info needed by the standard "down" and "route-pre-down" scripts and `leasewatch`.

I've filed Issue #432 for this since it is more "general" than this "split tunnel" issue.

> Tunnelblick takes those options and sets DNS, domain, routes, ...

Actually, OpenVPN takes those options, processes some of them itself, and passes the rest to the "up" script (which might or might not be `client.up.tunnelblick.sh`) in environment variables. Neither Tunnelblick nor `client.up.tunnelblick.sh` have anything to do with routing, that's all done by OpenVPN itself. Tunnelblick's `client.up.tunnelblick.sh`does use some of those environment variables to set DNS/WINS/Domain.

**Comment by mikz** [comment]
So I implemented a custom up/down script that creates resolver and tears it down.

## resolver.rb

```ruby
#!/usr/bin/env ruby

require 'erb'
require 'ostruct'
require 'pathname'

def extract_options(name)
  ENV.select{ |k,_| k =~ /^foreign_option_\d+$/ }.values.join("\n").scan(/^dhcp-option #{name} (.+)$/).flatten(1)
end

def resolver_for(domain)
  Pathname('/etc/resolver/') / domain
end

def set_resolvers(domains, dns)
  template = ERB.new(DATA.read, nil, '<>')
  domains.each do |domain|
    resolver = resolver_for(domain)
    output = template.result(binding)
    File.write(resolver, output)
  end
end

def remove_resolvers(domains)
  domains.each do |domain|
    resolver = resolver_for(domain)
    File.unlink(resolver)
  end
end

case script_type = ENV.fetch('script_type', 'none')
when 'up'
  domains = extract_options('DOMAIN')
  dns = extract_options('DNS')

  set_resolvers(domains, dns)
when 'down'
  domains = extract_options('DOMAIN')

  remove_resolvers(domains)
else
  puts "Unknown script_type: #{script_type}"
end

__END__
domain <%= domain %>
<% dns.each do |nameserver| %>
nameserver <%= nameserver %>
<% end %>
```

And need to make it executable:
```shell
chmod +x resolver.rb
```
## config.ovpn

```

up ./resolver.rb
down ./resolver.rb
```

## permissions

Need to set-up ACL so your user script can write to /etc/resolver

```shell
sudo chmod +a "user:$(id -n -u) allow add_file,delete_child" /etc/resolver
```

## Tunnelblick

Set the "Set DNS/WINS" to "Do not set nameserver"

**Comment by jkbullard** [comment]
@mikz - Thanks.

I'm not sure why the ACL needs to be set up, though. The script runs as root.

You don't need to set DNS/WINS" to "Do not set nameserver" if you have up and down scripts in your Tunnelblick VPN Configuration -- Tunnelblick will see them and use them instead of its own scripts automatically.

Also, the new "killswitch" may not work since "Set nameserver" is not used. I'm not sure about that, though.

**Comment by mikz** [comment]
@jkbullard you are right, the ACL is not needed. Will update the comment.

Maybe it is because I'm editing the configuration after installing it, but I needed to disable setting the nameserver to execute my scripts. Also I don't really want to set up the nameservers with this setup.
I want them just for the domain defined by the dhcp-options using /etc/resolver/.

But if tunnelblick needs to run the up script for some reason, it should be possible to run it without setting the dns servers. Because I don't want the VPN DNS as my primary DNS.

**Comment by jkbullard** [comment]
> Maybe it is because I'm editing the configuration after installing it, but I needed to disable setting the nameserver to execute my scripts.

It depends on who you are telling to use the scripts:
 * If you put your "up" or "down" script inside the Tunnelblick VPN Configuration (and name it "up", or "down"), Tunnelblick will see it and tell OpenVPN to use it and will automatically ignore "Set nameserver".

 * If you put an "up" line inside the OpenVPN configuration file, then Tunnelblick doesn't notice that and doesn't do anything special, so you'd need to specify "Do not set nameserver" because otherwise Tunnelblick will specify that OpenVPN should use Tunnelblick's scripts, which will override whatever you have in the OpenVPN configuration file.

**Comment by SpiGAndromeda** [comment]
Could somebody give a short explenation what the resolver file should look like? As far as I understand there should be one file per served domain? Or could I use one file for multiple domains. One of the VPN I am using serves multiple domains in multiple networks.

**Comment by mikz** [comment]
@SpiGAndromeda from `man 5 resolver` is a good resource.

**Comment by SpiGAndromeda** [comment]
Does I understand that right? I should place the resolver files in the /etc/resolver directory and they will be parsed by the ruby script?

**Comment by mikz** [comment]
@SpiGAndromeda the Ruby script is executed when the tunnel comes up/down. And it adds/removes file in /etc/resolver (like /etc/resolver/example.com) directory that has `nameserver some.ip.address.`. 

The Ruby script should already work with multiple domains and dns servers, but I haven't tried it.

**Comment by SpiGAndromeda** [comment]
So where does is get the information from? The push directives from the OpenVPN server?

**Comment by mikz** [comment]
Yes. The `dhcp-option DOMAIN` and `dhcp-option DNS`. It expects each of those has just one value and is sent multiple times.

**Comment by SpiGAndromeda** [comment]
Ok. The files are created. But they are ignored by macOS.
These is the created file in /etc/resolver called mintar.

`domain mintar
    nameserver 10.0.9.1
`
This is the output of `scutil --dns`
`resolver #9
  domain   : mintar
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
`
The nameserver is reachable via ping and the whole thing is working with windows. But for a reason I dont understand macOS seems to ignore the resolver.

**Comment by mikz** [comment]
`/etc/resolver/` works for me for years (.dev domain for local development). And this Ruby script also since I posted it here. Using it almost daily. 
Just try to create those files by hand and verify your setup without the script.

**Comment by SpiGAndromeda** [comment]
I created the files manually. They are working. But the generated files arent. Could there be any permission issue with the generation?

**Comment by pagaille** [comment]
Hi @mikz thanks for submitting your script. It is not clear to me where to save it, could you enlighten me ? Txs

**Comment by pagaille** [comment]
Thanks @mikz. Strange, this what I did, but as soon as I click connect, TB asks for my password "To create a secure (shadow) copy of the configuration file" and immediately after the ruby file gets deleted and the connection fails because the script cannot be found. Any idea ?

**Comment by pagaille** [comment]
NB / Works with an absolute path to my home folder. **Doesn't work using ~ !**

**Comment by alexchandel** [comment]
@jkbullard I guess `client.up.tunnelblick.sh` should be changed, but it's quite complicated. However this `setDnsServersAndDomainName()` creates the correct `/etc/resolver/` file:

```bash
setDnsServersAndDomainName()
{
	set +e # "grep" will return error status (1) if no matches are found, so don't fail on individual errors

	declare -a vDNS=("${!1}")
	declare -a vSMB=("${!3}")
	declare -a vSD=("${!4}")

	if [ ${#vDNS[*]} -eq 0 ] ; then
		readonly DYN_DNS_SA=""
	else
		readonly DYN_DNS_SA="${!1}"
	fi

	if [ ${#vSMB[*]} -eq 0 ] ; then
		readonly DYN_SMB_WA=""
	else
		readonly DYN_SMB_WA="${!3}"
	fi

	if [ ${#vSD[*]} -eq 0 ] ; then
		readonly DYN_DNS_SD=""
	else
		readonly DYN_DNS_SD="${!4}"
	fi

	DYN_DNS_DN="$2"

	# preprocessing omitted

	# if DOMAIN and at least 1 DNS were specified,
	if [ "${DYN_DNS_DN}" != "" -a ${#vDNS[@]} -gt 0 ] ; then
		
		# salt the filename with the interface name + tunnelblick
		DYN_RESOLVER="/etc/resolver/${DYN_DNS_DN}.${dev}.tunnelblick"

		if [ ! -e "${DYN_RESOLVER}" ] ; then

			# use the interface number for search_order, plus an offset
			DYN_ORDER="${dev//[!0-9]/}"
			let "DYN_ORDER = 10000 + 100 * ${DYN_ORDER}"

			# trim to 3, per MAXNS from man 5 resolver
			if [ ${#vDNS[@]} -gt 3 ] ; then
				vDNS=("${vDNS[@]:0:3}")
			fi

			DYN_TEXT="domain ${DYN_DNS_DN}\n"
			DYN_TEXT+="search_order ${DYN_ORDER}\n"
			for ns in "${vDNS[@]}" ; do
				DYN_TEXT+="nameserver ${ns}\n"
			done
			# TODO use (the given domain +) search domains with search

			printf '%s' "${DYN_TEXT}" > "${DYN_RESOLVER}"
		else
			# Error, DOMAIN has already been defined for this interface.

			# Theoretically, as DYN_ORDER is incremented by 100, a unit index
			# could be incremented, allowing multiple domain definitions from
			# 1 interface. Such an index would change DYN_RESOLVER to something like:
			# DYN_RESOLVER="/etc/resolver/${DYN_DNS_DN}.${DYN_IDX}.${dev}.tunnelblick"
			# However this is not currently done.
		fi
	fi
}
```

And for the `down` script, this deletes it:
```bash
# @param String domainName - The domain name to use
deleteDnsServersAndDomainName()
{
	DYN_DNS_DN="$1"

	if [ "${DYN_DNS_DN}" != "" ] ; then
		# salt the filename with the interface name + tunnelblick
		DYN_RESOLVER="/etc/resolver/${DYN_DNS_DN}.${dev}.tunnelblick"

		if [ -e "${DYN_RESOLVER}" ] ; then
			rm "${DYN_RESOLVER}"
		else
			# Error, resolver file was never created or already deleted.
		fi
	else
		# Error, function signature violated
	fi
}
```

`setDnsServersAndDomainName()` omits some input preprocessing, as I didn't work through the entire file. And both omit debug logging and error reporting.

**Comment by jc0r3** [comment]
@mikz I copied your script (thank you for sharing) and modified the end with the parameters I'd like to use, placed it next to config.ovpn (which is now *.tblk) and modified it with up/down absolute path.  Did i modify the script correctly by only replacing the parameters at the bottom like so:

__END__
domain <%= myofficedomain.com %>
<% dns.each do |nameserver| %>
nameserver <%= xxx.xxx.xxx.xxx %>
<% end %>
search_order <%= search_order %>

**Comment by mikz** [comment]
@jc0r3 that snippet after `__END__` is [ERB](https://www.stuartellis.name/articles/erb/).

The `domain <%= domain %>` already templates the domain offered by the DHCP server into the actual config file. For example, if the DHCP server offers domain `example.com` then it would create a file `/etc/resolver/exmple.com` with the following content:

```
domain example.com
nameserver x.x.x.x
nameserver y.y.y.y
```

If your DHCP does not offer any domain (in the `dhcp-option DOMAIN`) then it would not create the file anyway. 

If you are not looking for a generic solution, then you can write the script in any language and just create a file `/etc/resolv/example.com` with hardcoded domain and extract nameservers from the ENV.

**Comment by bdaylik** [comment]
Here is a fully POSIX compliant shell script version using `scutil`. Note that it currently supports a single DNS and DOMAIN-ROUTE option. It can be improved to support other options as well as multiples.

```sh
#!/bin/sh

begins_with() { case $2 in "$1"*) true;; *) false;; esac; }
is_dns_option() { begins_with "dhcp-option DNS " "$1"; }
is_domain_route_option() { begins_with "dhcp-option DOMAIN-ROUTE " "$1"; }
get_dns() { echo ${1##*" "}; }
get_domain_route() { echo ${1##*" "}; }
parse_options() {
  IFS="$(printf '\nx')" && IFS="${IFS%x}";
  for key_value in $(set)
  do
    if begins_with "foreign_option_" $key_value
    then
      option_name=${key_value%%=*}
      eval option_value="\$$option_name"
      if is_dns_option "$option_value"
      then
        DNS=$(get_dns "$option_value")
      fi
      if is_domain_route_option "$option_value"
      then
        DOMAIN_ROUTE=$(get_domain_route "$option_value")
      fi
    fi
  done
}

register_dns_macos() {
  /usr/sbin/scutil << EndOfCommands
d.init
d.add ServerAddresses * $DNS
d.add SupplementalMatchDomains * $DOMAIN_ROUTE
set State:/Network/Service/$DOMAIN_ROUTE/DNS
EndOfCommands
}

unregister_dns_macos() {
  /usr/sbin/scutil << EndOfCommands
remove State:/Network/Service/$DOMAIN_ROUTE/DNS
EndOfCommands
}

case $script_type in
  up)
    parse_options
    echo "DNS: $DNS and DOMAIN_ROUTE: $DOMAIN_ROUTE"
    register_dns_macos
    echo "[up] finished registering DNS parameters"
  ;;
  down)
    parse_options
    echo "DNS: $DNS and DOMAIN_ROUTE: $DOMAIN_ROUTE"
    unregister_dns_macos
    echo "[down] finished unregistering DNS parameters"
  ;;
esac
```
