### ISSUE TITLE
OpenVPN 2.3.11

### ISSUE THREAD

**Issue by DomT4** [Tunnelblick/Tunnelblick#307]
It'd be good to update the bundled default OpenVPN to 2.3.11. Per upstream:

> This release fixes two vulnerabilities: a port-share bug with DoS potential and a buffer overflow by user supplied data when using pam authentication.

Happy to supply a PR but not sure if the process is more involved than simply replacing the bundled `third_party` tarball with the new release and doing a local build to check it compiles okay?

**Comment by jkbullard** [comment]
Thanks for bringing this up. A PR would be appreciated.

After replacing the openvpn-2.3.10.tar.gz with openvpn-2.3.11.tar.gz, you also need to rename .../third_party/openvpn/openvpn-2.3.10 folder to be openvpn-2.3.11.

Then make sure it all builds properly. Sometimes there are changes needed to the patches, or (more rarely) changes to the "configure-options.txt" file. For 2.3.11, I doubt if either would be needed.

Note: Tunnelblick patches OpenVPN releases for two purposes:
 1. It adds the "scramble" patch to implement the "scramble" option (see [Tunnelblick and openvpn_xorpatch](https://tunnelblick.net/cOpenvpn_xorpatch.html));
 2. It adds some definitions that are missing from Xcode 3.2.2 so that "utun" can be used; and
 2. For source taken from OpenVPN's git "master" branch, there is also a patch that fiddles the version number.

**Comment by DomT4** [comment]
Thanks for the detailed explanation there. Patching still applies fine on the new release and nothing jumps out from `configure` in terms of needing changes.

Running into a build failure locally but I'm 90% sure its related to my local environment. I'll set up a clean VM and check again.

**Comment by DomT4** [comment]
Filed https://github.com/Tunnelblick/Tunnelblick/pull/308.
