### ISSUE TITLE
On temporary network interruption, tunnelblick gives up too early?

### ISSUE THREAD

**Issue by nemobis** [Tunnelblick/Tunnelblick#311]
During a large file transfer from within a Windows VM in Parallels over a VPN with Tunnelblick, the connection was terminated and the VPN had to be manually re-enabled to resume the transfer. This never happened before to us, but we need such transfers to be reliably completed.

I believe https://paste.debian.net/782606/ is the relevant passage of the system logs. At 04:00 a turn of events starts, there are some "runTunnelblickd: no data available from tunnelblickd socket; sleeping" then at 4:01 "Status = 0 from tunnelblick-helper command 'killall'" and at 4:02 "Parallels networking sucessfully started".

Is there a way to make Tunnelblick wait for a few minutes before closing the VPN?

Thank you and sorry if the answer is already elsewhere. I skimmed the common issues etc. and searched forums for the various log strings, without result.

[Diagnostic info](https://github.com/Tunnelblick/Tunnelblick/files/368856/tunnelblick.txt)

**Comment by jkbullard** [comment]
(It appears you are not using the most recent version of Tunnelblick. You might want to reconsider that.)

What you posted indicates normal operation of Tunnelblick: Tunnelblick was quit, and the VPN was closed down. Tunnelblick did not quit as a result of an error or problem with the network; it quit as a result of the user asking it to quit. When Tunnelblick quits, it closes all open tunnels except for tunnels configured to connect when the computer starts. That's what it did.

It is possible that Tunnelblick was quit *inadvertently* by the user because of the way that Command-Q is processed by OS X: If the user has an open Tunnelblick window and closes it (via Command-W or by clicking the red dot in the upper-left corner) or if the last thing the user did before a Command-Q was to click the Tunnelblick menu, a Command-Q will quit Tunnelblick. That's because Tunnelblick is still the "key" application and gets all keyboard input. OS X does not indicate that Tunnelblick is the "key" application because it is an application that "lives in" the menu bar instead of the Dock, so the user can't easily tell that Tunnelblick will accept the Command-Q and quit.

Here is a detailed analysis of the Tunnelblick entries in the log fragment you posted:

The first mention of Tunnelblick in the log fragment you posted is:

> 04:01:16... Tunnelblick[10580]: applicationShouldTerminate: termination for unknown reason, probably Command-Q; delayed until 'shutdownTunnelblick' finishes

That message indicates that OS X informed Tunnelblick that it should quit. As the mesage states, it was for an unknown reason but is probably because the user typed "Command-Q" into a Tunnelblick window. (It was *not* because of an error detected by or a signal caught by Tunnelblick or anything to do with the network.)

So the Tunnelblick application was being quit. **Quitting Tunnelblick includes closing all VPN tunnels that are not "connect when the computer starts" configurations** and deleting Tunnelblick and OpenVPN logs.

The "no data available from tunnelblickd socket; sleeping..." messages are merely an indication of a delays in Tunnelblick internal processing of commands, nothing more. The two eventual "Status = 0 from tunnelblick-helper..." messages at 4:01:23 and 4:01:30 indicate that the commands succeeded, so the delays are unimportant. (One command was to kill any existing OpenVPN processes, the other to delete Tunnelblick and/or OpenVPN logs). The commands just took a long time, probably due to a lot of other activity on the system.

All of this is a normal result of quitting Tunnelblick.

**Comment by nemobis** [comment]
Thanks for your analysis.

jkbullard, 18/07/2016 14:25:
> It is possible that Tunnelblick was quit /inadvertently/ by the user

Definitely not at 4 in the morning. If someone has pressed a quit 
button, that would be someone who broke into the building against law in 
the middle of the night. So if you're right that something quit 
Tunnelblick it's more likely that another application or the OS did, but 
why?

**Comment by jkbullard** [comment]
I have never seen the "termination for unknown reason, probably Command-Q" message except from a Command-Q. If something happened that Tunnelblick knew about, it would have been logged by Tunnelblick in an earlier message. A SIGTERM, for example, would have resulted in Tunnelblick logging "Signal 15 received".

You might try the following command:

    defaults write net.tunnelblick.tunnelblick DB-SD -bool YES

which will cause Tunnelblick to do additional logging when it shuts down. That might show something.

To remove the extra logging:

    defaults delete net.tunnelblick.tunnelblick DB-SD

**Comment by nemobis** [comment]
jkbullard, 27/07/2016 21:40:
> You might try the following command:
>
> |defaults write net.tunnelblick.tunnelblick DB-SD -bool YES |
>
> which will cause Tunnelblick to do additional logging when it shuts
> down. That might show something.

Thanks. Will this stick after the machine is rebooted?

**Comment by jkbullard** [comment]
Yes. It sets a "preference", which survives reboot. It is, however, a *per-user* setting.
