### ISSUE TITLE
Can't update on macOS sierra beta

### ISSUE THREAD

**Issue by coolya** [Tunnelblick/Tunnelblick#324]
I have installed macOS Sierra Beta 4. When Tunnelblick detected the update from Tunnelblick 3.6.4a (build 4561) to 3.6.5 was available the download seemed to work but the update could not be extracted. I tried multiple times, always with the error message that the update was damaged.

Manually updating by downloading the dmg worked fine.

```
2016-08-12 17:47:53 Tunnelblick[508] Tunnelblick: OS X 10.12.0; Tunnelblick 3.6.4a (build 4561)
2016-08-12 17:47:54 Tunnelblick[508] Set program update feedURL to https://www.tunnelblick.net/appcast-s.rss
2016-08-12 17:48:23 Tunnelblick[508] Sparkle Error: An error occurred while extracting the archive. Please try again later.
2016-08-12 20:56:40 Tunnelblick[508] applicationShouldTerminate: termination because of Quit; delayed until 'shutdownTunnelblick' finishes
2016-08-12 20:56:40 Tunnelblick[508] Finished shutting down Tunnelblick; allowing termination
```

Let me know if I can somehow supply additional infos.

**Comment by jkbullard** [comment]
Thanks for your report. This problem (can't update on Sierra) is known and is being worked on.

**Comment by anomaly256** [comment]
Just adding that I see it going to 3.6.6 as well

**Comment by jkbullard** [comment]
This should be fixed in Tunnelblick 3.6.7beta04, released a few minutes ago.

**Comment by melikyuksel** [comment]
I'm getting this error trying to update from 3.6.6 to 3.6.7c.

**Comment by jkbullard** [comment]
**This issue is closed**. As it says on our home page, among other places:

<blockquote>**CRITICAL update**: Old versions of Tunnelblick will not update to later versions when running on macOS Sierra – updates will always fail. Please update to the latest stable or beta version of Tunnelblick **before upgrading to Sierra**. See [this announcement](https://groups.google.com/forum/#!topic/tunnelblick-discuss/lzAqJY7qHgg) for details.</blockquote>

Tunnelblick 3.6.6 is one such "old version" that will not update -- there have been four releases after 3.6.6.

If you are *not* using Tunnelblick 3.6.7 or higher and you are on Sierra, you need to download a recent version from the Tunnelblick Downloads page and install normally (by double-clicking) over your existing copy. Doing that will keep your existing configurations and settings.

**Comment by gandafor** [comment]
Please explain the mechanism preventing proper installation. What did Apple change in MacOS Sierra that is preventing Sparkle from dearchiving updates? Did they change permissions again, and if so, where and what was the work around?

**Comment by jkbullard** [comment]
@gandafor - Sorry, I don't know what specific feature of Sierra causes the problem. I suspect it had to do with app translocation, but didn't really investigate it, so I can't say for sure.

Tunnelblick was using a very old version of Sparkle Updater (although patched with security updates and additional security measures), and that old version has almost no logging of what specific errors occur. When I tried the current version of Sparkle, (patched with additional security measures), it worked. Updating to a newer Sparkle had been on my list for a while, so I updated to use it without trying to figure out what the specific problem was.
