### ISSUE TITLE
Mac OSX, network preferences crash

### ISSUE THREAD

**Issue by trondh** [Tunnelblick/Tunnelblick#325]
When I have a VPN active  and I want to check my DNS settings in the advanced section of the network preference tool in my Mac pro (OSX), the network preferences tool immediately crashes and an error box is displayed as shown in the attached screenshot.

The problem has survived through several Tunnelblick and OSX versions.

**Comment by trondh** [comment]
screenshot of error box attached
<img width="780" alt="screen shot 2016-08-24 at 08 05 09" src="https://cloud.githubusercontent.com/assets/18207068/17920207/51c53f2a-69d3-11e6-93aa-022435088325.png">

**Comment by jkbullard** [comment]
This could be caused by the same thing as #352 -- see my [last comment](https://github.com/Tunnelblick/Tunnelblick/issues/352#issuecomment-273840675).

If the configuration (or something pushed by the server) has something unexpected by Tunnelblick in a "dhcp-option", Tunnelblick will stick it in the wrong place in the network setup. I can see how something unexpected in the network setup could cause Network Preferences to complain.
