### ISSUE TITLE
OS X route delete command failed: external program exited with error status: 77

### ISSUE THREAD

**Issue by jakeobsen** [Tunnelblick/Tunnelblick#334]
On 10.12 macOS Sierra and latest stable version of tunnelblick, when I create a VPN tunnel, the tunnel stop working after a very short period of time. 

When I disconnect, the routes added is left in the route table, I can either manually remove them or reboot.

I have set redirect-gateway in the client config file:

> redirect-gateway def1 bypass-dhcp

This is the error log:

> 2016-09-28 10:28:14 *Tunnelblick: Disconnecting; VPN Details… window disconnect button pressed
> 2016-09-28 10:28:14 *Tunnelblick: No 'pre-disconnect.sh' script to execute
> 2016-09-28 10:28:14 *Tunnelblick: Disconnecting using 'kill'
> 2016-09-28 10:28:14 event_wait : Interrupted system call (code=4)
> 2016-09-28 10:28:14 /sbin/route delete -net 10.8.0.0 10.8.0.25 255.255.255.0
>                                         route: must be root to alter routing table
> 2016-09-28 10:28:14 ERROR: OS X route delete command failed: external program exited with error status: 77
> 2016-09-28 10:28:14 /sbin/route delete -net 188.166.164.219 10.192.136.1 255.255.255.255
>                                         route: must be root to alter routing table
> 2016-09-28 10:28:14 ERROR: OS X route delete command failed: external program exited with error status: 77
> 2016-09-28 10:28:14 /sbin/route delete -net 0.0.0.0 10.8.0.25 128.0.0.0
>                                         route: must be root to alter routing table
> 2016-09-28 10:28:14 ERROR: OS X route delete command failed: external program exited with error status: 77
> 2016-09-28 10:28:14 /sbin/route delete -net 128.0.0.0 10.8.0.25 128.0.0.0
>                                         route: must be root to alter routing table
> 2016-09-28 10:28:14 ERROR: OS X route delete command failed: external program exited with error status: 77
> 2016-09-28 10:28:14 Closing TUN/TAP interface

**Comment by jkbullard** [comment]
You didn't post the diagnostic information, but it appears that you are using the "user none" and/or "group none" options in OpenVPN. Depending on other options in your configuration, that means that OpenVPN is unable to remove the routing when a tunnel is shut down and you will see the behavior that you have described.

**Comment by kaandok** [comment]
@jkbullard what should be used in order to routes to be deleted automatically?
(there was a popup regarding a root plugin I thought it handled this as well)

**Comment by jkbullard** [comment]
The "openvpn-down-root" plugin does not help with the problem of routes not being deleted, because it only runs the "down" script as root, and it is OpenVPN itself, not the "down" script, that restores routes.

The standard recommendation to solve the problem is to remove the "user nobody" and "group nobody" options from your OpenVPN configuration file (or comment them out by prefixing them with a "#" or ";" character). OpenVPN will then run as root, and will be able to restore the routes when you disconnect.

Another method,  which sometimes fixes the problem, is to use Tunnelblick's "Reset the primary interface after disconnecting". However, not that it resets only the primary device, it does not restore the routing on all of your computer's network interfaces, so if you have Wi-Fi and Ethernet network connections, it will only restore the routing on one.
