### ISSUE TITLE
Is the XOR patch applicable under mobile side?

### ISSUE THREAD

**Issue by 2ndMessiah** [Tunnelblick/Tunnelblick#339]
Firstly thanks for creating of this nice obfuscating patch. 
I have a necessity to use openvpn on iOS. But afaik there's only an official version of openvpn. If I have patched the server side, how can I apply it on the mobile side? Adding the obfs parameters in the .ovpn client file will do?
Much obliged

**Comment by jkbullard** [comment]
Thanks, but I didn't create the patch; it was created by GitHub user [clayface](https://github.com/clayface). I did fix some bugs in the patch so it would be safe to include it in Tunnelblick. For more details about the patch, see [Tunnelblick and openvpn_xorpatch](https://tunnelblick.net/cOpenvpn_xorpatch.html).

I would assume that the [OpenVPN Connect app that is available in the iOS App store](https://itunes.apple.com/us/app/openvpn-connect/id590379981?mt=8) **does not include the patch** because the app's creator/maintainer is one of the OpenVPN developers and [the developers have taken a very strong stand against the patch](https://forums.openvpn.net/viewtopic.php?f=15&t=12605&hilit=openvpn_xorpatch&sid=05c4d721ea2058ad1d2212e91bc3d897&start=60#p49837), but I have not verified that independently. That means that **you cannot simply add the "scramble" option to your configuration file and have it work on iOS**. You need a version of OpenVPN that includes the patch.

As I understand it, the OpenVPN Connect app is not open source or free software, so it would not be easy to create a version that did include the patch.

This is really a question about OpenVPN, not about Tunnelblick, so I think you should ask your question on the [OpenVPN Connect Support Forum](https://forums.openvpn.net/viewforum.php?f=36), or the  [official OpenVPN users mailing list](https://lists.sourceforge.net/lists/listinfo/openvpn-users), or the [official OpenVPN Support Forum](https://forums.openvpn.net/index.php).
