### ISSUE TITLE
Question: OpenVPN Patch?

### ISSUE THREAD

**Issue by Geyup** [Tunnelblick/Tunnelblick#347]
Hello,

Hopefully someone can be kind enough to tell me what patch(s) is being used at present for OpenVPN 2.3.14?

I've noticed at the bottom of this page a patch;

https://tunnelblick.net/cOpenvpn_xorpatch.html

And these patches;

https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party/sources/openvpn/openvpn-2.3.14/patches

If it is the collection of the diffs to use from the above URL, does anyone have them together as one diff/patch to apply instead of several?

Thanks

**Comment by jkbullard** [comment]
The patches in the source code that you linked to are the ones that are in
the binary that is offered on the Downloads page.

As the names of the patches implies, they are each part of the xor patch.
The original patch changed five files. Some time ago, that patch was
separated into five pieces, with each piece changing only one file. That
was done to make it easier to change the patches when a new version of
OpenVPN comes out with changes to the source code that the patches change.

Because of the way that patch files work, you can just concatenate the five
files together and create one patch file that will perform the same
function as the five files do.

The webpage is out-of-date. I will put updating it to my list.

Note that git master versions of OpenVPN also include a patch that sets the
version number that OpenVPN reports to match the version number that
Tunnelblick uses to identify that version. That version number includes the
first few characters of the hash that identifies the commit to the OpenVPN
source code that the source code for Tunnelblick uses to build it's
binaries.

Also, some old versions of Tunnelblick include a patch to define some
system parameters that are not included in Xcode version 3.2.2, which is
used to build them.no

**Comment by Geyup** [comment]
I'm not using Tunnelblick, and I just wanted to know what patches to apply to OpenVPN 2.3.14 is all?

Thanks

**Comment by jkbullard** [comment]
If you want to use the 'scramble' option, then feel free to apply those patches. As it says on the page on the website, that patch is for an earlier version of OpenVPN.

**Comment by Geyup** [comment]
One last thing, if you don't mind, sorry forgot to ask before.

I'm not using a Mac and I did apply the patch in Linux to OpenVPN and it seemed to work fine, so I'm assuming patched against OpenVPN in LInux is fine?

Wasn't sure if the patch had anything specific to Tunnelblick or OSX?

Thanks

**Comment by jkbullard** [comment]
The patch is for OpenVPN and has nothing specific to Tunnelblick or OS X / macOS.

**Comment by Geyup** [comment]
Ok thank you...

**Comment by t3xtb0ok** [comment]
Hello.

I have been doing a lot of reading lately trying to find my specific answers for my specific situation, and this seems like the best place to ask my question.

Forgive me if this is too unrelated to Tunnelblick.

I and many others have been following this guide [1]-[2] to apply your updated x0r patch to our openvpn setup... However, your patches fail to apply after you split the files since 2.3.12
 [1] https://scramblevpn.wordpress.com/2016/06/25/raspberry-pi-and-patched-openvpn-server-built-from-source-code-2-3-11/
[2] https://scramblevpn.wordpress.com/2013/09/28/build-patched-windows-openvpn-client/

I am using this link [3] in an Ubuntu 14.04 VM to create my patched .exe using your patches.
[3] https://community.openvpn.net/openvpn/raw-attachment/wiki/SettingUpGenericBuildsystem/setup-generic-buildsystem.5.sh

However each time I try to apply the patches I get...
root@ubuntu:~/openvpn-build/generic/sources/openvpn-2.4.0# git apply --check 02-tunnelblick-openvpn_xorpatch-a.diff
fatal: unrecognized input
root@ubuntu:~/openvpn-build/generic/sources/openvpn-2.4.0# git apply --check 03-tunnelblick-openvpn_xorpatch-b.diff
fatal: unrecognized input
root@ubuntu:~/openvpn-build/generic/sources/openvpn-2.4.0# git apply --check 04-tunnelblick-openvpn_xorpatch-c.diff
fatal: unrecognized input
root@ubuntu:~/openvpn-build/generic/sources/openvpn-2.4.0# git apply --check 05-tunnelblick-openvpn_xorpatch-d.diff
fatal: unrecognized input
root@ubuntu:~/openvpn-build/generic/sources/openvpn-2.4.0# git apply --check 06-tunnelblick-openvpn_xorpatch-e.diff
fatal: unrecognized input

This leaves me and every person I know that is not using OSX stuck using your last working patch on OpenVPN 2.3.11.

If you or anyone else could please advise me on how to fix this I would sincerely appreciate your help.

I know OpenVPN devs do not approve of the x0r patch and do not recommend your work,... but I genuinely appreciate this patch and the work you do. Please help.

**Comment by jkbullard** [comment]
@t3xtb0ok - Sorry, but I don't think I'll be much help. I'm not familiar with the posts you link to and don't build Tunnelblick using openvpn-build.

[These patches](https://github.com/Tunnelblick/Tunnelblick/tree/master/third_party/sources/openvpn/openvpn-2.4.0/patches) are for OpenVPN 2.4.0. They apply cleanly to the source code of OpenVPN 2.4.0 after downloading it from the [OpenVPN Community downloads page](https://openvpn.net/index.php/open-source/downloads.html) and expanding it.

I'm not familiar with "git patch", so maybe there is something about it that is causing the problem. You might want to look at [All GIT patches I create throw fatal: unrecognized input](http://stackoverflow.com/questions/37347350/all-git-patches-i-create-throw-fatal-unrecognized-input) -- it's the first link in a Google search.

The only other thing I can think of is for you to consolidate the patches into a single file (just concatenate them; that's how .diff files work) so it is like the single file of the patch for 2.3.11.

**Comment by Geyup** [comment]
@t3xtb0ok hmm you're running this cmd as?

git apply --check

Just patch it the OLD FASHION way...

cd to the source /path as example;

 cd /my/home/openvpn

Then run the cmd to the patches as example;

patch -p1 < /my/home/patches/patch  :)

**Comment by t3xtb0ok** [comment]
Sorry it took a while to respond. I was able to apply the patch without any issues by simply combining all of the separate patch files into a single patch file like it was before.
