### ISSUE TITLE
maintainability of openvpn_xorpatch

### ISSUE THREAD

**Issue by mandree** [Tunnelblick/Tunnelblick#349]
Looking at https://github.com/Tunnelblick/Tunnelblick/blob/master/third_party/sources/openvpn/openvpn-2.4_rc1/patches/03-tunnelblick-openvpn_xorpatch-b.diff and in a strive for robustly maintainable and defensively programmed code, I propose to replace the constants 0 ... 4 that you assign to xormethod by an enum that gives these symbolic names, and use them in the assignments and in the switch(){case:} statements.

**Comment by jkbullard** [comment]
Sounds reasonable; I didn't do that originally because I wanted to stay as close to the original patch as possible when I ported it to Tunnelblick (although I did fix several bugs).

Please note that I have just synched a six-day-old commit ([6fe3140](https://github.com/Tunnelblick/Tunnelblick/commit/6fe3140c1a27e5b6c81f0d8daf98e0465f016e98)), replacing OpenVPN 2.4_rc1 with 2.4_rc2. So any PRs should be based on that.

**Comment by jkbullard** [comment]
Closed for lack of interest and lack of a PR.
