### ISSUE TITLE
Setting nameservers causes Mail.app to crash

### ISSUE THREAD

**Issue by Merlin83b** [Tunnelblick/Tunnelblick#352]
Using a VPN with the "Set nameserver" option causes Mail.app to crash.  This doesn't seem to be a new issue and there's a fairly comprehensive breakdown here: https://dan.langille.org/2015/12/19/osx-mail-crashes-when-using-tunnelblick-and-setting-dnswins/

From `scutil`, we can see the nameserver from the VPN being set, but looks alright to me and perhaps not matching the conclusion in the above link:

```
> show State:/Network/Global/DNS
<dictionary> {
  DomainName : mydomain.com
  ServerAddresses : <array> {
    0 : 192.168.1.1
  }
}
> # connect to VPN
> show State:/Network/Global/DNS
<dictionary> {
  DomainName : <array> {
    0 : dhcp-option
    1 : SEARCH-DOMAIN
    2 : mydomain.com  }
  SearchDomains : <array> {
    0 : dhcp-option
    1 : SEARCH-DOMAIN
    2 : mydomain.com
  }
  ServerAddresses : <array> {
    0 : 172.24.0.1
  }
}
> > show State:/Network/Global/DNS
<dictionary> {
  DomainName : mydomain.com
  ServerAddresses : <array> {
    0 : 192.168.1.1
  }
}
```

I don't know where to go next, but very willing to try suggestions!

**Comment by jkbullard** [comment]
Thanks for posting this -- the link and your scutil output are very interesting.

In the link, which is undated, it mentions Tunnelblick 3.5.5, which was released on 2015-12-04 and was superseded by 3.5.6 on 2016-02-01. So the post is pretty old and apparently hasn't been updated to indicate whether or not Viscosity has the same problem. 

I'm not sure what you mean by "not matching the conclusion in the above link". However, I do notice one very odd thing in your scutil output: The "DomainName" is an array. That is very odd because I think it should be a string. If Tunnelblick is (incorrectly) creating it as an array, that could be why Mail is crashing -- it is trying to get the length of the string that it expects, but since Tunnelblick created it as an array, Mail crashes.

I will try to see if I can figure out how it becomes an array instead of a string, and post back to this Issue if/when I have an update.

**Comment by Merlin83b** [comment]
The link is dated Dec 2015 so is out of date, but exactly matches my experience.  I'm running 3.6.10.

You're quite right on DomainName.  i was incorrectly focussing on ServerAddresses.  Hopefully client.up.tunnelblick.sh won't be too hard to modify to act correctly :)

**Comment by jkbullard** [comment]
Your configuration file either has **dhcp-option SEARCH-DOMAIN mydomain.com** or that option is being pushed by your OpenVPN server.

However, client.up.tunnelblick.sh is looking for "DOMAIN-SEARCH", not "SEARCH-DOMAIN".

Neither one appears in the online man page or in the message when OpenVPN 2.4.0 is started with no arguments.

If you change it to **dhcp-option DOMAIN-SEARCH mydomain.com**, Tunnelblick seems to handle it properly and Mail doesn't crash.

I don't know which is correct, but I think "SEARCH-DOMAIN" is more descriptive.

@Merlin83b - where did you get the idea to use "SEARCH-DOMAIN" from? That is, what told you that that was a valid option?

When I investigated this, I found a bug in the client.up.tunnelblick.sh script. The script considers any sub-command other than "DOMAIN-SEARCH" that contains the string "DOMAIN" to be interpreted as just "DOMAIN". That's a bug and is the reason this problem was not more easily seen. (You used the string "SEARCH-DOMAIN", but any string that contains "DOMAIN" would do the same thing: "FOO-DOMAIN", "DOMAIN-FOO", "THISISTHEDOMAIN", etc.)

Commit f7bef874f6885f530385dde4468d25eb58000954 fixes this bug, and also allows either "DOMAIN-SEARCH" or "SEARCH-DOMAIN" to specify a "search domain". These changes will be in the next beta release of Tunnelblick. If you need a Tunnelblick binary with these changes before the next beta release, email me at developers@tunnelblick.net and I'll send a link.)
