### ISSUE TITLE
Error on every restart: "Configuration is not secure. It should be reinstalled."

### ISSUE THREAD

**Issue by essandess** [Tunnelblick/Tunnelblick#357]
I get the error "Configuration is not secure. It should be reinstalled." every time I restart my OpenVPN server.

This problem persists after an uninstall/install fresh, and I've checked all the obvious stuff: permissions, commented out user/group nobody, and don't see ant issues with my configuration.

The `.tblk` configuration is [here](../../../essandess/osx-openvpn-server/tree/master/openvpn-server-tun.tblk).

Deleting and reinstalling the configuration work fine, and the VPN performs fine after that (until the next restart), with no relevant log messages pertaining to this error.

**Comment by jkbullard** [comment]
The problem is the "ifconfig-pool-persist ipp.txt" in your configuration file.

Because you do not specify an absolute path, the file will be created inside of the .tblk, and it will be modified as OpenVPN assigns IP addresses. .tblks should be read-only, and the creation of or changes to the ipp.txt file will be detected as a security problem.

To fix this, specify an absolute path for ipp.txt in the configuration (and that path must be outside of the .tblk).

Tunnelblick complains when you try to install a configuration that contains similar OpenVPN options such as "status" or "write-pid", but looking at the code it does not warn about "ifconfig-pool-persist". I'll fix that in a few moments. (The warning would only appear if you install the .tblk in the approved manner, by dragging/dropping it onto the Tunnelblick icon in the menu bar, and from the link you posted it looks like you are not doing that.)

**Comment by jkbullard** [comment]
Commit 82912b30089a0d9cf2acca0dc5c23fd7c08cbf5a causes Tunnelblick to warn about "ifconfig-pool-persist" with paths that are not absolute.

**Comment by essandess** [comment]
Thanks @jkbullard!
