### ISSUE TITLE
Configurations inherit default options [Feature Request]

### ISSUE THREAD

**Issue by DomT4** [Tunnelblick/Tunnelblick#358]
It would be useful to be able to set a set of default configuration options, or even a default configuration, and for all added configurations to automatically adhere to those options unless manually changed later.

Currently if you install multiple configurations you have to go through every single one and tick boxes like `Route all IPv4 traffic through the VPN` and `Advanced => Keep Connected` despite both those things being pretty reasonable defaults. It'd be really useful timesaver to have some way to centralise configuration options.

**Comment by jkbullard** [comment]
Tunnelblick has two ways of doing this:

(1) You can make changes to many configurations at one time.

When you make a change (such as checking "Route all traffic through the VPN"), it is applied to all of the configurations that are currently selected in the left side of the "Configurations" panel of the "VPN Details" window. That's true even if the change is to a setting in the "Advanced" settings window.

Select multiple configurations using standard macOS methods (click, command-click, shift-Click, and Command-A).

(2) Because almost all Tunnelblick configuration settings -- preferences -- are "defaults" (macOS jargon), they can also be manipulated by the "defaults" command. Wildcards are allowed in place of configuration names (for example, "ABCsetDNS" will set the DNS settings for the "ABC" configuration, and "*setDNS will set the DNS settings for all configurations except those with different specific defaults." The most common ones are documented.

**Comment by DomT4** [comment]
Nice, thanks @jkbullard! I was looking for something along the lines of option 2 there, but it hadn't occurred to me at all that `defaults` + wildcards would be supported.
