### ISSUE TITLE
Automating connecting with a password

### ISSUE THREAD

**Issue by t0il3ts0ap** [Tunnelblick/Tunnelblick#360]
Applescript features to provide password to login window.

I use the `connect configuration` command which brings up this window
https://ibb.co/c7mFiv

Is there anyway to provide credentials to the connect command ?

Current way:
```
#! /usr/bin/osascript
tell application "Tunnelblick"
	connect "myconfiguration"
end tell

```

**Comment by jkbullard** [comment]
Tunnelblick does not have a way to provide the password via AppleScript, but you have two other options:

 1. Save the username and password in the Keychain (using the checkboxes seen on your screenshot). After you have done that once and connected successfully, for subsequent connections Tunnelblick will automatically get the username and password from the Keychain and not pop up the window requesting them.

 2. Use the OpenVPN "--auth-user-pass" option. From the OpenVPN 2.4 man page:

 <blockquote>
--auth-user-pass [up]
    Authenticate with server using username/password. up is a file containing username/password on 2 lines. If the password line is missing, OpenVPN will prompt for one.

    If up is omitted, username/password will be prompted from the console. 
</blockquote>

If you use "--auth-user-pass", you would include the file with the username/password in the .tblk, the same way you would include a .crt or .key file. For example, if your OpenVPN configuration file includes "--auth-user-pass foo.txt", you would include a file named "foo.txt" in the .tblk. "foo.txt" would have two lines: the username on the first line, and the password on the second line. "foo.txt" should use Unix line endings (LF) and not Windows line endings (CR,LF). Unix line endings are the default on a Mac, so that shouldn't be a problem unless you try to directly move the file from a Windows environment.

**Comment by lokesh-wise** [comment]
Can we reopen this? The password for me changes every-time because I need to append an otp to the end of password to connect.

**Comment by jkbullard** [comment]
@lokesh-wise

(1) If you don't have a script that can generate the OTP, you should use Tunnelblick's new ability to ask the user for a "token", which is appended to the password.

(2) If you have a script that can generate the OTP, you could save the username and the password in the Keychain, and include a "password-append.user.sh" script in your configuration. That script would echo the OTP to stdout. Tunnelblick would append the output of the script to the password from the Keychain and provide the result to OpenVPN as if it were the password; OpenVPN would then pass it on to the server.

As far as I know, that combination (username and password saved in Keychain and a script providing what to append to the password) works, but I don't think it has been thoroughly tested, so if there are any problems, please create a new GitHub Issue about the problems.

For more info, see [Using Scripts](https://tunnelblick.net/cUsingScripts.html).
