### ISSUE TITLE
Tunnelblick does not overwrite manually set DNS. Please help.

### ISSUE THREAD

**Issue by rivaros** [Tunnelblick/Tunnelblick#371]
I have a known problem with Tunnelblick. My Wi-FI connection has static IP an DNS.
When connecting to VPN, it refuses to set DNS servers, retrieved from openvpn server
with this warning.

```
WARNING: Ignoring ServerAddresses '10.10.49.1' because ServerAddresses was set manually
```

So all resources behind VPN are not available. Ok I read somewhere I need to write 2 scripts.
Oh, I had to add 2 scipts into ~/Library/Application Support/Tunnelblick/Configurations/<somename>.tblk/Contents/Resources

1. pre-connect.sh
```
#!/bin/bash

networksetup -setdnsservers Wi-Fi empty
```

2. post-disconnect
```
#!/bin/bash

networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4
```

So I try first to remove manually set DNS servers, so Tunnelblick can set servers by DHCP and after VPN connection is closed, restore my old DNS servers back. Scripts are executed, but it does not work. As soon as I remove DNS servers I cannot connect to my openvpn.server-somewhere-in-internet.com (naturally, as it is cannot be resolved now :)), so connection even does not happen.

How can this issue be resolved? It's rather annoying since another OpenVPN client is working perfectly in this conditions and /etc/resolv.conf is perfectly changed automatically without problems.

**Comment by jkbullard** [comment]
>  I read somewhere I need to write 2 scripts.

As you saw, this won't work. You should let "somewhere" know that.

Tunnelblick has refused to modify manually-entered network settings for many years. It was a deliberate decision, but perhaps it is time to allow such modifications. I'll consider that.

Until such changes are made to Tunnelblick, your best bet would be to use a copy of Tunnelblick's standard up script modified so that the change is allowed. Put the modified script in your Tunnelblick VPN Configuration as a file named "up.sh" so it will be used instead of the standard script. Remember to remove your pre-connect.sh and post-disconnect.sh scripts.

**Important:** Tunnelblick VPN Configurations can be located in different places (depending on whether they are shared or private), so `~/Library/Application Support/Tunnelblick/Configurations/.tblk/Contents/Resources` is not always the correct place for them. Let Tunnelblick manage configurations: change a copy of the configuration and then install that changed configuration. (Install by dragging/dropping the copy onto the Tunnelblick icon in the menu/status bar.)

Attached is a .zip of such a modified version of Tunnelblick's standard "up" script that allows changing manually-entered DNS entries. After expanding the .zip, rename the script to "up.sh" before adding it to your configuration. The only changes to the standard script are that lines 330-333 and line 358 are commented out so manually entered DNS entries are ignored. (Note: other manually-set entries such as the domain will still not be changed; you'd have to make similar changes to the script for each such entry.)

**Please reply if this modified file fixes the problem.**

[allow-override-of-manually-set-dns-up.sh.zip](https://github.com/Tunnelblick/Tunnelblick/files/942723/allow-override-of-manually-set-dns-up.sh.zip)

**Comment by jkbullard** [comment]
After thinking about it, I have decided to allow changes to all manually-entered network settings, but not by default.

At least initially, it will require the user to set a per-configuration preference ("-allowChangesToManuallySetNetworkSettings") either via Terminal's "defaults" command or by an Info.plist entry in a Tunnelblick VPN Configuration.

I expect that to be included in the next beta release of Tunnelblick.

At some point I may add a checkbox to control this, probably in the Advanced settings window. Post here if you want that so I can see how many people are interested.

**Comment by rivaros** [comment]
@jkbullard thank you so much for reacting. I had upvoted the feature to have DNS change possible.

About up.sh script - it worked for me, but the process of deploying the script is unclear for me - so I just copied the script to ~/Library/Application Support/Tunnelblick/Configurations/.tblk/Contents/Resources and reconnected.

Could not find any way to do it through GUI. Only .ovpn files can be dragged-dropped, scripts not.
Maybe missing something?

**Comment by jkbullard** [comment]
Sorry for the confusion. The .sh file(s) must be put into a complete Tunnelblick VPN Configuration (.tblk), and then that .tblk can be dragged/dropped onto the Tunnelblick icon.

Changes to manually-set network setting can now be enabled by a new "Allow changes to manually-set network settings" checkbox on the "Advanced" settings window. The checkbox is unchecked by default to preserve current behavior.

I have committed changes to do this as 4a0ac46233d2ec5a8c42a36d784801560963ae5c and 1c6ce143ed71b1d4bbc7fba5170df2fa12600828.

**Comment by BernhardLenz** [comment]
@jkbullard I see you were somewhat hesitant to add this functionality. Now since the "Allow changes to manually-set network settings" checkbox is here, what are the drawbacks of enabling "Allow changes to manually-set network settings"? 

My use case is that on a Mac, I have multiple VPNs to e.g. AWS production and non-production, for which I have to point the dns resolver to the VPC internal DNS. Both VPNs should be able to run in parallel. 

For example:
Production VPC/VPN: 
  VPC CIDR: 10.0.0.0/16
  VPC Internal DNS: 10.0.0.2
  VPN Server conf file contains: push "dhcp-option DNS  10.0.0.2"
Non-Production VPC/VN: 
  VPC CIDR: 10.0.1.0/16
  VPC Internal DNS: 10.1.0.2
  VPN Server conf file contains: push "dhcp-option DNS  10.1.0.2"

**Comment by jkbullard** [comment]
The drawback is that you are allowing the changes : ) 

The reason for my reluctance was that one of the guidelines for OpenVPN, going back to it's peer-to-peer days, is that the server should not be able to do anything to the client that the client doesn't explicitly allow. A client using DHCP is implicitly allowing "someone else" to set its IP address, subnet mask, DNS, etc. So if you are set to use DHCP, we allow that "someone else" to be the VPN server and allow it to change DNS. But if you've set DNS manually, you are not letting anyone else change it, so we refuse to let the VPN server change it. To provide maximum flexibility, we allow you to override that, and let the VPN server change DNS, by checking the "Allow changes to manually-set network settings" box on a per-configuration basis.

Note that Tunnelblick's built-in scripts do not support multiple simultaneous VPN connections or multiple DNS resolvers. You may need to use additional scripts, perhaps your own or perhaps modified versions of Tunnelblick's built-in scripts. See [Using Scripts](https://tunnelblick.net/cUsingScripts.html).
