### ISSUE TITLE
Latest Tunnelblick beta can't connect - running macOS 10.13

### ISSUE THREAD

**Issue by majuss** [Tunnelblick/Tunnelblick#380]
Using the latest macOS 10.13, if I press "connect" a error message pops up. The content of the log is:
```

  Contents of the OpenVPN log:
     
          Options error: Temporary directory (--tmp-dir) fails with '/var/folders/t7/mpyl9v9d3hb1q435455w2d_h0000gp/T/': Operation not permitted
          Options error: Please correct these errors.
          Use --help for more information.
```

Note that 10.13 got a new filesystem and the permissions on these tmp directories seems to got changed.

**Comment by JJJ** [comment]
Disabling System Integrity Protection will allow Tunnelback to work. It will also disable System Integrity Protection, which is a bad idea.

https://www.imore.com/el-capitan-system-integrity-protection-helps-keep-malware-away

But don't do that.

`/var/folders/` needs to be changed to `/var/tmp/` or something else with adequate permissions to allow file system writes to occur.

**Comment by jkbullard** [comment]
I agree that turning off SIP is a bad idea.

It isn't clear to me what OpenVPN is using the temporary directory for. The OpenVPN 2.4 man page says:

```
--tmp-dir dir
    Specify a directory dir for temporary files. This directory will be used by openvpn processes and script to communicate temporary data with openvpn main process. Note that the directory must be writable by the OpenVPN process after it has dropped it's root privileges.

    This directory will be used by in the following cases:

    * --client-connect scripts to dynamically generate client-specific configuration files.

    * OPENVPN_PLUGIN_AUTH_USER_PASS_VERIFY plugin hook to return success/failure via auth_control_file when using deferred auth method

    * OPENVPN_PLUGIN_ENABLE_PF plugin hook to pass filtering rules via pf_file 
```
but that all looks like server stuff to me. (Maybe the man page is wrong and it is used for other things, too.)

Tunnelblick doesn't specify a temporary folder to OpenVPN, so OpenVPN is apparently using '/var/folders/t7/mpyl9v9d3hb1q435455w2d_h0000gp/T/' as a default. (That is, it is apparently using some system call that returned that as a temporary folder, or is figuring it out for itself.)

You could try overriding that using the --tmp-dir option in the OpenVPN configuration file. I don't know what it should be set at, but Tunnelblick uses /tmp for some things (which gets mapped to /private/tmp by macos), and for others it uses a system call which provides a temporary folder.

**Comment by sunstarfire** [comment]
Simple solution.
Find your configuration (either you still have the files, or you use the ones stored on your system in `/Library/Application Support/Tunnelblick/Shared/<name>.tblk` (right click on that, "Show Package Contents")
Open the vpn-config file you are using for the connection. Add the line "`tmp-dir /<dir>`" close to the beginning (I did it in the second line). <dir> can point to something you can write to, like `/tmp`.
Install this configuration
Works.

**Comment by jkbullard** [comment]
Thanks, @sunstarfire.

But your solution will only work for a shared configurations.

For private configurations, select the configuration in the list on the left side of the "VPN Details" window, then click the little "gear" icon below the list, and select "Edit OpenVPN Configuration file...". That will open the configuration file in TextEdit.

(Then, add the "tmp-dir" line as @sunstarfire describes.)

**Comment by JJJ** [comment]
What @jkbullard suggests is by far a better idea, and one that could be implemented into the configuration files themselves if this becomes more of an issue for macOS users.

**Comment by jkbullard** [comment]
It should not be necessary to modify everyone's configuration files.

I assume this is a bug in 10.13 beta; if I'm wrong and "it's a feature, not a bug" I will add code to Tunnelblick itself to set --tmpdir to something appropriate (but be overridden if --tmp-dir is in the configuration file), or put in PRs to OpenVPN to use a better default or not check the directory if it will not be used.

Currently, OpenVPN sets the default --tmpdir to the environment variable $TMPDIR, which Tunnelblick sets to the path returned by [NSTemporaryDirectory()](https://developer.apple.com/documentation/foundation/1409211-nstemporarydirectory). There are (at least) two issues:
 1. Why does OpenVPN check the writability of that directory even when it will never be used? According to the [OpenVPN man page](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage), it is only used in certain unusual situations. Maybe it is also used in other situations, or maybe it is always checked because nobody bothered to add code to see if it will be used.

 2. Why does the 10.13 beta not allow OpenVPN running as root write to the directory? Perhaps in 10.13 "root" cannot access a different user's directory (although it seems odd to restrict root in this way, it also seems odd to restrict it using SIP instead of or in addition to access control).

It might help clarify things if @majuss or someone else with this problem could verify that they are not running an OpenVPN server (that is, not using the specific OpenVPN features listed in my earlier post which quoted the man page), and get a "ls -l@e" of the specific folder that is being complained about. (Note that the folder will change periodically, maybe with each login or something.)

**Comment by jkbullard** [comment]
@majuss, @JJJ, @sunstarfire:

Thanks for your reports.

I have not been able to reproduce this problem; perhaps my test configurations do not require OpenVPN to use the temporary directory.

Can anyone confirm that it still is present in High Sierra Developer Beta Version 7? If so, please post your configuration and maybe I'll be able to see what is causing the use of the temporary folder.

**Comment by user3587412** [comment]
Hello, I just wanted to report that I am no longer having this issue on macOS High Sierra (non-beta) with Tunnelblick 3.7.2.
