### ISSUE TITLE
weird logic behind "public IP address check"

### ISSUE THREAD

**Issue by chipitsine** [Tunnelblick/Tunnelblick#382]
we are running corporate VPN, so we do not distribute "redirect-gateway def1" neither in client config, nor in server push options.

there's no reason for changing "public IP address" in our case. however, Tunnelblick keeps bothering our users with

"This computer's apparent public IP address was not different after connecting to"

I think that check only makes sense in public VPN installation, where "redirect-gateway def1" is proposed, but not in corporate installation. Depending on how Tunnelblick observe that setting or not, it could either perform or not perform that check.

thank you!

**Comment by jkbullard** [comment]
Thanks for your suggestion, but it is my understanding that "redirect-gateway def1" can be "pushed" by the server, so Tunnelblick can't just examine the configuration file to see if it is being used. Parsing the OpenVPN log to see if the option is in effect can't be done if logging is disabled and would be difficult if it were.

Users can disable IP address checking in the GUI (for existing configurations) by selecting all configurations and then un-checking "Check if the apparent public IP address changed after connecting" on the "Setting" tab. Or they can disable it for all configurations via the command line:

defaults write net.tunnelblick.tunnelblick *-notOKToCheckThatIPAddressDidNotChangeAfterConnection -bool yes

Distributors of configurations can include an Info.plist in each configuration which sets that preference on the configuration. See https://tunnelblick.net/cPkgs.html#preferences. (Note that the preference name to include in the Info.plist would be "-notOKToCheckThatIPAddressDidNotChangeAfterConnection", without the "*".)

**Comment by chipitsine** [comment]
it is way complicated.

can we consider some config based way of turning that off ?

like "setenv CLIENT_CERT 0" (which is interpreted by iOS) ?

so, it would allow to turn of that setting by admin of corporate vpn (which is not supposed to set default route)

**Comment by jkbullard** [comment]
I'm sorry you find it so complicated.

If I understand you correctly, you want to have an option in the OpenVPN configuration file that sets an environment variable that the "up" and "down" scripts can see (but the Tunnelblick GUI cannot) and have that control whether or not the GUI performs the IP address check. That would require a new mechanism for the "up" and "down" scripts to communicate with Tunnelblick and would require the use of Tunnelblick's standard "up" and "down" scripts. I can't see doing that.

Or maybe it could be done as a comment in the OpenVPN configuration file that Tunnelblick interprets as some sort of directive, e.g. "#Tunnelblick IpAddressChecking off". Tunnelblick has always used the macOS "defaults" mechanism for controls such as this, and I'm reluctant to introduce a new mechanism to do that, especially since it can be controlled as I described before.

**Comment by chipitsine** [comment]
Comment would be just fine

**Comment by jkbullard** [comment]
The Tunnelblick website now includes a bash script that creates .tblks from OpenVPN configuration files. Each .tblk includes an Info.plist that disables IP address checking.

See [Example Script to Create .tblks with IP Address Checking Disabled](https://tunnelblick.net/cPkgs.html#bash-example-script-create-a-.tblks-with-ip-address-checking-disabled).

**Comment by chipitsine** [comment]
Thank you for your efforts.

However, from my point of view tblk is not a comfortable way.
For corporate vpn (login / password auth) we supply users with ovpn (server cert invluded), which is placed on website. It is easy to download ovpn file. As for tblk, I'm afraid we cannot place it on website, tblk is folder, right?

**Comment by jkbullard** [comment]
A .tblk is a folder; just compress it and have your users download the .zip file. Depending on their browser and its settings, the .zip will be un-zipped automatically after being downloaded. At most they would have to double-click the downloaded file to un-zip it.

**Comment by chipitsine** [comment]
zip seems to solves the issue, thanks.
we tested, works as expected
