### ISSUE TITLE
Google 2-factor authentication possible?

### ISSUE THREAD

**Issue by rivaros** [Tunnelblick/Tunnelblick#383]
Is it possible with tunnelblick? No popup comes up.
Switched to Viscosity for now.

**Comment by joshcoughlan** [comment]
We have this working wherein the 2fa just gets appended to the end of the password. However, this is super annoying because muscle memory has me hitting enter after typing my password. It would be really nice to be able to have a separate prompt for the 2fa code if 2fa is configured in the connection settings. Or even just a separate text field for 2fa in the existing login dialog would be a huge improvement.

So, +1 on this enhancement request.

**Comment by hryamzik** [comment]
@joshcoughlan how did you make it working this way? I tried to add 2fa code to the end of password, it doesn't work for me.

**Comment by bechampion** [comment]
Is this any update on this?
Thank you!

**Comment by hryamzik** [comment]
I'm using code from this PR #430 and it solves the issue for me.

**Comment by bechampion** [comment]
Thanks mate ill recompile !

**Comment by FlorinAndrei** [comment]
@joshcoughlan What's your configuration? `/etc/pam.d/openvpn`

**Comment by jkbullard** [comment]
Closed because static and dynamic challenge/response are implemented in 4c1dbde99314ab0b67c70f3f8e4b13572fc0ca58 and 2d9f0e4159c66288600a468c468f9729869d025a, respectively.

**Comment by faucct** [comment]
When will the new build be available?

**Comment by changyuheng** [comment]
Hi @faucct, the latest [build](https://github.com/Tunnelblick/Tunnelblick/releases/tag/v3.7.7beta03) has this feature.
