### ISSUE TITLE
Replace OpenVPN 2.4.2 with 2.4.3 and 2.3.16 with 2.3.17

### ISSUE THREAD

**Issue by l2dy** [Tunnelblick/Tunnelblick#385]
OpenVPN v2.4.2 was analyzed closely using a fuzzer by Guido Vranken. In the process several vulnerabilities were found, some of which are remotely exploitable in certain circumstances. We recommend you to upgrade to OpenVPN 2.4.3 or 2.3.17 as soon as possible.

https://community.openvpn.net/openvpn/wiki/VulnerabilitiesFixedInOpenVPN243

**Comment by jkbullard** [comment]
Yes. However, as is being discussed on the OpenVPN developers mailing list, there have been problems with the downloads (perhaps CloudFlare problems) and I have not yet successfully downloaded a good copy of 2.4.3 (that is, a copy whose PGP signature verifies correctly). 2.3.17 isn't affected by this problem.

When that problem is fixed (as of a couple of minutes ago it wasn't) and the new OpenVPN  versions have been tested in Tunnelblick, new releases of Tunnelblick will be available with the updated versions. Typically testing takes several hours, sometimes up to a day or so.

**Comment by l2dy** [comment]
[openvpn-2.4.3.tar.gz](https://github.com/Tunnelblick/Tunnelblick/files/1091963/openvpn-2.4.3.tar.gz)

**Comment by jkbullard** [comment]
We don't download from GitHub or SourceForge; we download from the official OpenVPN site, https://openvpn.net/index.php/open-source/downloads.html.

**Comment by l2dy** [comment]
You can verify the PGP signature. I'm just mirroring the file.

**Comment by jkbullard** [comment]
The problem is not downloading the file, the problem is with verifying the signature. The file I download does not verify using the signature that I download. I don't know if the file itself is the problem or the signature is the problem (or both), and until that is resolved I won't be using the downloaded file.

**Comment by l2dy** [comment]
Here's the signature I downloaded. I hope you have their PGP public key.
```
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAABAgAGBQJZSkgnAAoJENcq80SMwrA0qGUP/0njOCqGADVTrK2gLz3owZpP
rAQRs+eBcjR+XlwQ0ejeMRuJ0HS7nSw7Y1vKpddgZDO5POscSTtR86uBizqizGfU
s7Y40oJgFvyVsaHKbGrR8XvwjjCfEcevUbhbz+2v1u4IHkB4wfk/a0keX/mDbeRf
VYAI/jyahzAlnBS0YdidmA6TL/aL2kmmN4JooDUKolwbox7jw7VfhKpNMRRHfxQX
COsNOQ1Bv9/FpHuas7mEfAuYtn+tczjLeX7xMy1oq9MW5L5/VB6pOMujIA6qoJEX
kmKmm2W+XZq8CV5WcqudwjbJqF0G6fWIaspmf21M+EXiUyAesql9ajMLT3IZ6tA4
5Cu3RSIiFE2Izwb9hGiOS6NzLdlrzObMb4k1tN1L3WXJaLGj8OaUqfsR+khwK5e4
o5+PBXyOTQ444pywehM5l939OGVsnaIjQk6U0oqsTAOWLPH/B4wYV8+G2irOjFKD
ctyjgiH2unZilIXwIIHqGp55x2LAAS+CY/ZIAaqFBhbDdOrAhHjD4ubF5rqb9ClR
vFDLcmQeasGADZzwv+SeI+cmRcMfYGXDpCIlZcAFsHrWRkWKiakhGOMBKwBWVx4L
w+y/WDT3xtX8U0kfyrxfl+pUWOfmulBDGWGSj4TJ8Kot+3B/j0YMigAhfv9tDfws
Yi03PkitVylBQ07jI1jO
=d52d
-----END PGP SIGNATURE-----
```

```
gpg: Signature made Wed Jun 21 10:19:19 2017 UTC
gpg:                using RSA key D72AF3448CC2B034
gpg: Good signature from "OpenVPN - Security Mailing List <security@openvpn.net>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: F554 A368 7412 CFFE BDEF  E0A3 12F5 F7B4 2F2B 01E7
     Subkey fingerprint: B596 06E2 D8C6 E10B 80BE  2B31 D72A F344 8CC2 B034
```

**Comment by jkbullard** [comment]
Thanks, but as I wrote earlier, I am going to wait until the OpenVPN folks get everything working properly. I assume that will happen within the next day or so; if not then I will reconsider.

**Comment by jkbullard** [comment]
Things seem to be OK now, so expect new Tunnelblick releases later today or tomorrow. As usual, they will be announced on the [Tunnelblick Announce list](https://groups.google.com/forum/#!forum/tunnelblick-announce).

**Comment by jkbullard** [comment]
New Tunnelblick releases that include the new versions of OpenVPN are now available on the Tunnelblick Downloads page.
