### ISSUE TITLE
When the VPN server hard crashes or dies, client waits for too long to disconnect

### ISSUE THREAD

**Issue by diwu1989** [Tunnelblick/Tunnelblick#389]
Repro steps:
- connect to a server via UDP
- pull the plug on the server
- disconnect tunnelblick client
- wait for a minute or so until the client times out

To be more friendly to the user, please make the client disconnect timeout much shorter by default, something like 5s would make tunnelblick more usable.

Right now sometimes i get so frustrated waiting for the disconnect that I just reboot the client machine.

Likewise, when auto-reconnecting, if the server isn't responding within a reasonable time (5s), please allow disconnect vs being stuck in reconnecting state.

**Comment by jkbullard** [comment]
Thanks for your report.

> To be more friendly to the user, please make the client disconnect timeout much shorter by default, something like 5s would make tunnelblick more usable.

This is probably caused by your OpenVPN setup. If the OpenVPN configuration contains (or the OpenVPN server "pushes") the "--explicit-exit-notify" option, OpenVPN will attempt to notify the server that the client is disconnecting. OpenVPN then waits for the server to acknowledge that notification. If the server isn't responding, the client will never get the acknowledgement, and OpenVPN will wait for some timeout period (30 seconds?) before deciding that it really is disconnected. I don't know if you can change that timeout period; please consult OpenVPN experts for that.

> Likewise, when auto-reconnecting, if the server isn't responding within a reasonable time (5s), please allow disconnect vs being stuck in reconnecting state.

This could the same problem: OpenVPN is waiting for the acknowledgement of the disconnect part of the reconnect request.

Or it could be waiting to connect to the OpenVPN server. That timeout appears to be controlled by OpenVPN's "--server-poll-timeout"  and "--connect-timeout" options. I'm not clear on what, if any, difference there is between the two options; please consult OpenVPN experts for that, too.

See the [OpenVPN man page](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage) for details on these options.

**Comment by diwu1989** [comment]
great, thanks for the tip
modifying the ovpn client configuration file to be tighter about timeouts and keepalives shortened the span im waiting on disconnect

**Comment by Cattywampus-** [comment]
diwu1989 can you tell me what I need to add to ovpn config file to change the timeout please?

 I get frequent timeouts and although Tunnelblick does eventually drop the connection and reconnect, it would be great if it was a shorter time before it realised it need to do this. Thanks!
