### ISSUE TITLE
Logic for detection of DHCP gateway under TAP is not accurate (client.up.tunnelblick.sh)

### ISSUE THREAD

**Issue by mpsrig** [Tunnelblick/Tunnelblick#402]
````	
	bRouteGatewayIsDhcp="false"
	if [ -z "${route_vpn_gateway}" -o "$route_vpn_gateway" == "dhcp" -o "$route_vpn_gateway" == "DHCP" ]; then
		bRouteGatewayIsDhcp="true"
	fi
````

Why do we assume that it's a DHCP gateway in the absence of that environment variable? `-z "${route_vpn_gateway}"`  

This breaks under my config, which is a pretty basic LAN only TAP config where I want to set the nameserver.  A static IP and DNS IP is pushed from the OpenVPN server, but Tunnelblick incorrectly thinks it needs to use DHCP due to the absence of a "route_vpn_gateway".  Well, in this config there is no gateway being used! It's LAN-only.

**Comment by mpsrig** [comment]
May related to https://community.openvpn.net/openvpn/ticket/668
Since I know this used to work for me

**Comment by rubin55** [comment]
I ran into this probem because of a couple of reasons. 

1. route_gateway and route_vpn_gateway variables are never initialized, hence dhcp setup on a tap device will always be done.
2. I'm pushing a static ip from my server to the client, without any dhcp.
3. The result of the two items above is two ip addresses on your tap0 device.

I created a patch that checks the device for any ip setup. if a previously set-up ip is detected on the device, don't do DHCP setup (previously set-up for example, by my static ifconfig-push on server to client). The patch:

```
--- /Users/rubin/Downloads/client.up.tunnelblick.sh.orig	2017-11-22 16:45:03.000000000 +0100
+++ client.up.tunnelblick.sh	2017-11-22 16:37:07.000000000 +0100
@@ -1475,6 +1475,13 @@
 		bRouteGatewayIsDhcp="true"
 	fi
 
+	# Check if $dev already has an ip configuration, which could be because of a static config push by the server.
+	hasIp="$(ifconfig ${dev} | grep inet | cut -d ' ' -f 2)"
+	if [ "${hasIp}" ]; then
+		logMessage "Setting bRouteGateway to false because ${dev} already has an ip configuration.."
+		bRouteGatewayIsDhcp="false"
+	fi
+
 	if [ "$bRouteGatewayIsDhcp" == "true" ]; then
 		logDebugMessage "DEBUG: bRouteGatewayIsDhcp is TRUE"
 		if [ -z "$dev" ]; then

```
