### ISSUE TITLE
Add authentication from users through Touch ID.

### ISSUE THREAD

**Issue by ericpardee** [Tunnelblick/Tunnelblick#407]
Haven't looked how to implement in Tunnelblick,
 but it seems that The Local Authentication framework provides facilities to request that a user may authenticate using only Touch ID, i.e.
 during installation. (https://developer.apple.com/documentation/localauthentication)

**Comment by tmthecoder** [comment]
@jkbullard Hello, I'm looking into adding this feature and submitting a PR in the future. Do you mind giving me a bit of a rundown through different instances of User Authentication? I just want to make sure I don't miss anything when covering my bases.

**Comment by jkbullard** [comment]
Is the idea to:
 1. Have Tunnelblick optionally require a fingerprint to connect a VPN?
or
 2. Have Tunnelblick accept a fingerprint for authorization for installing itself (and configurations, etc.)?

The first one seems doable, but it wouldn't interact with the existing authentication, which, being managed by OpenVPN, is username/password based and/or certificate based. It would just be an additional step (optionally) required while starting a connection. (Would it be required for restarts, too?)

However, I don't understand why the second one would be necessary or how Tunnelblick could do it. For installations, Tunnelblick isn't asking the user to identify himself/herself. Instead, Tunnelblick asks macOS to authorize it to have "root" privileges for certain operations (e.g., installing Tunnelblick itself, installing configurations, making a change to a configuration, etc.). macOS then puts up a prompt asking for the username/password of a computer administrator. if they are correct, macOS then gives Tunnelblick an authorization token that Tunnelblick uses when it needs to perform a privileged operation. Because the authorization is done by macOS, I assume that on a Touch ID mac, you can use a computer administrator's fingerprint instead of his/her username/password. Is that not the case?

**Comment by tmthecoder** [comment]
@jkbullard My initial start was to do an optional one as you stated in the beginning, and that I have a plan laid out(going to implement soon) as it does not interact with any existing authentication. The second one was what I thought might be possible, as we may be able to use touchID for whatever operations Tunnelblick needs to run as admin, which I have to do more research on, but if it runs through keychain you can use touchID to do it(some things touchID does not allow over password entry to my belief, I have yet to see what specifically)

**Comment by jkbullard** [comment]
The second one does not have anything to do with Keychain. To get the authorization, Tunnelblick uses a system call, AuthorizationCopyRights(), in Tunnelblick's SystemAuth class's checkAuthorizationRef:prompt:interactionAllowed:reactivationAllowed: method.

**Comment by jkbullard** [comment]
Note also that Tunnelblick isn't necessarily getting the authorization from the currently-logged-in user. It is getting authorization from a system administrator.

**Comment by tmthecoder** [comment]
Okay. Then I will primarily try to implement touchID as an option for connecting to VPNs and then check other needs it may have. Thanks for the info!

**Comment by jkbullard** [comment]
OK, I look forward to reviewing your PR. Please break it into small commits.

**Comment by tmthecoder** [comment]
Ill break it into small commits, but how do I deal with the LocalizedStrings as I do not have aa localized string made for the option I will add to the .xib... Should I use a literal as of now?

**Comment by jkbullard** [comment]
Tunnelblick was written before macOS and Xcode did much with localization, so we developed our own mechanism. Basically, placeholder text is put in the xib, and then it is replaced at run time with the localized version (usually in an "awakeFromNib" method . Sometimes that means that spacing of other elements need to be adjusted dynamically.

In addition, there are two xibs for most windows, one for left-to-right languages such as English, and another for RTL languages such as Arabic and Hebrew. The appropriate xib is loaded at run time based on the language in use when Tunnelblick launches.

Take a look at how localization is done, for example in UI >> Preferences >> Preferences >> GeneralView.h (which is for the "Preferences" tab of the "VPN Details" window).

**Comment by tmthecoder** [comment]
Okay. Thanks! Also, should I be modifying from El Capitan(10.11) or will there be any changes if I use Catalina? I can whip up a vm if needed.

**Comment by jkbullard** [comment]
There's a further, minor complication, in that options such as Touch ID should probably be per-configuration. And the place to put that would be in the Advanced window's "Connecting and Disconnecting" tab. (UI >> Preferences >> SettingsSheetWindowController and Resources >> xibs >> SettingsSheet.xib).

That tab is pretty full, so you will have to make the window taller to accommodate whatever you add. (Adding items to the right of existing items is problematic because then you have to adjust the positions of the item to the right or left, depending on the size of the localized text vs. the placeholder text, and because sometimes the localized text is much wider than the placeholder text.

Best for development is a VM set up as described in "Building Tunnelblick from Source Code.markdown", which is included in the source code.

**Comment by tmthecoder** [comment]
Okay, I can do that. I'll get working once the VM is all set with the XCode version listed on the building file. It should be done relatively soon as it is not much of a complication adding touchID, but I'll make sure to break it up into small commits.

**Comment by jkbullard** [comment]
Another complication. For security reasons, the option (preference) must be protected and only changed by a system administrator, like the ""Require administrator authorization for key and certificate changes" checkbox on the "Preferences" panel. It isn't a regular preference stored in ~/Library/Preferences/net.tunnelblick.tunnelblick. The code for that is in also in UI >> Preferences >> Preferences >> GeneralView.m.

(The methods invoked when a checkbox in the VPN Details window is clicked, or a button pushed, etc. are in MyPrefeWindowController.m, which is in UI >> Preferences.)

**Comment by tmthecoder** [comment]
Do I need to call a special method to change the preference then? Just to enable whether touchID is needed for a VPN?

**Comment by jkbullard** [comment]
Yes. Look at the code in MyPrefsWindowController for the checkbox I mentioned to see how it is done.

**Comment by tmthecoder** [comment]
Okay. will do. If anything else is needed, just let me know

**Comment by tmthecoder** [comment]
Also, a problem. I'm installing a 10.11 installer, but all apple installers that have not been re-signed are declared invalid, meaning I cannot verify the install. It means that I can't instantiate and create a VM.

**Comment by jkbullard** [comment]
Set the VM's clock back to, say, January 1, 2019. See if that helps.

(You're doing it in an El Capitan VM, right?)

**Comment by tmthecoder** [comment]
I just tried that, makes no difference. It gives me a validation error as the root ca expired I believe.

**Comment by tmthecoder** [comment]
Just worked, but I had to change the date all the way back to 2015

**Comment by tmthecoder** [comment]
There's a problem. We can't use the LocalAuthentication framework on a device lower than macOS SDK 12 as touchID is not available in El Capitan. We can keep backward compatibility but would need to change the build SDK to 12 over 11 as it currently does not allow LocalAuthentication to be used for macOS. Is this possible to do? If not, it makes a huge block towards any biometric authentication features as we cannot use the built-in framework under OSX 12.

**Comment by tmthecoder** [comment]
The code is all set and done across a variety of small commits. I'll be submitting a PR soon!

**Comment by tmthecoder** [comment]
I submitted a PR last night, but it's my first one ever, so if I need to fix anything or change anything, let me know as I've never submitted a PR before and I'm not sure if I did anything wrong within my commit flow

**Comment by jkbullard** [comment]
Thanks. I've seen it and will look at it and comment later tonight or tomorrow.

**Comment by jkbullard** [comment]
I've made extensive comments on PR #585, but I want to mention some things that became clear to me while reviewing it:

There are several ways to require authorization before connecting:
 1. Require authentication by a computer admin. This defeats a main purpose of Tunnelblick, which is to allow normal users to connect the VPN.
 1. Require authentication by the logged-in user, using a password or TouchID (or FaceID or whatever comes in the future). This can prevent prevent a "maid in the hotel room" from connecting the VPN. It's what PR #585 does.
 1. Require authentication by the logged-in user, using biometric ID (TouchID or FaceID or whatever comes in the future) but not allowing authentication by password. This makes it possible to prevent the VPN from being connected if the user gives the password to someone, or if the password is otherwise compromised. I think this is what PR #585 did originally, before commit 26c7c63121d8b7ca0186cb7135c1a011dd23f0bc.

I think it is worth _considering_ adding option 3. That could be done after PR #585 is accepted and merged. I'm not sure it is that helpful, though: if the user's login password is compromised, all sorts of mischief can be done, so I'm not sure 3. would provide much more actual benefit. So maybe 2. (which is what I think PR #585 does) is the best.

Thoughts, anyone?

**Comment by tmthecoder** [comment]
Currently I am doing 2, but 3 may not be possible given Tunnelblick's build system on Xcode 7.3.1 as the LAContext framework does not support a biometric-only method until after macOS sdk 12 (to my belief) and the corresponding Xcode version (8, I think).

**Comment by jkbullard** [comment]
Yeah, 2 is fine for now. I'm a bit ambivalent about 3 anyway and am hoping someone else will express their opinion.

There are ways to use methods that aren't in the SDK, but maybe we should update to SDK 10.12. I don't want to do that yet, but if we do 3, that may be the time to do it (first, as a separate PR).

**Comment by tmthecoder** [comment]
In order to update, would you need to use Xcode 8 and above? Or will 7 still work with sdk 10.12

**Comment by jkbullard** [comment]
I don't know. Often Apple lets the last point version of Xcode have the SDK for the next version of macOS, so it probably does. But it's not worth looking into unless we decide to proceed with implementing 3. (And sometimes an SDK removes methods, so we might need to deal with that.)

**Comment by tmthecoder** [comment]
That's true. I guess if people want 3 or there are other opinions then there's a reason to move forward

**Comment by jkbullard** [comment]
Closing this. If someone wants to require biometric instead of also allowing passwords, they should create a new Issue.
