### ISSUE TITLE
Uninstall script doing "secure erase" on SSD shows lack of understanding of SSDs

### ISSUE THREAD

**Issue by zslg01** [Tunnelblick/Tunnelblick#415]
The Uninstall utility (version 1.8) takes some time since it does a secure erase. When using an SSD this is an unnecessary step since the underlying SSD flash layer moves data around and there is NO GUARANTEE that any data "overwritten" with zeros will even be touched. The only way to insure a secure erase is for the OS to interact with custom flash firmware to somehow force a deletion of a block. I doubt even Apple's new APFS does that. With current technology this erase is just a time wasting effort. Sorry SSD users - your data may be recoverable by some TLA.
I would recommend moving the deleted files to the trash and let the user decide if a secure erase is needed.

**Comment by jkbullard** [comment]
I don't think it does do any harm to do the "secure erase" other than taking longer. (Maybe it's a bit more wear and tear on the SSD, but I don't think it that's significant.)

I'd rather always do a secure erase so that gets done on an HDD, instead of introducing additional steps that the user must think about and then undertake manually if they want to.

If there is a backward compatible (to OS X 10.4) way to know that a device is an SSD, the uninstall script could do a secure erase only for non-SSDs, I would be happy to consider a PR for that. It would have to work with external drives, though, which might be a complication.

**Comment by zslg01** [comment]
Maybe just an addition to the note about secure erase reminding people that an SSD has no such thing as an 100% secure erase. 
I would imagine any MacBook Pro 2015 or newer is only SSD (unless you pry open the case and unsolder the chips :-) ) I am note sure about MacBooks.
Anyway just a suggestion.

**Comment by jkbullard** [comment]
> Maybe just an addition to the note about secure erase reminding people that an SSD has no such thing as an 100% secure erase.

Good idea, thanks!

**Comment by jkbullard** [comment]
I've updated the Uninstaller. Version 1.9 does a secure erase only on non-SSDs. It has some other changes; see the [Release Notes](https://tunnelblick.net/cRlsNotes.html#uninstaller).
