### ISSUE TITLE
VPN removed from menu should not appear on window pop-over

### ISSUE THREAD

**Issue by fedelibre** [Tunnelblick/Tunnelblick#423]
Let's say I have 3 VPN connections. They will appear alphabetically sorted under Settings:

- Alberta
- Brian
- Cindy

Let's say that I want to make it "visible" only one, that is Cindy.
There's the option "Do not show in Tunnelblick menu". Fantastic, I check this option for Alberta and Brian. What it happens?

1. When I click on Tunnelblick icon in the system tray, I see only Cindy. So far so good.
2. but if I hover on it, I see Alberta (that is, the first VPN in the list)

I would expect that "Do not show in Tunnelblick menu" served the purpose of choosing the default VPN to connect to. IMO the current behaviour is not consistent and VPNs which have this setting checked should not appear in the pop-over window.

This has been tested on Tunnelblick version 3.7.4b (build 4921) on Mac Os Sierra.

Thanks for this software, it's pretty cool! (though I don't use it myself, I set it up for my dad)

**Comment by jkbullard** [comment]
@fedelibre - Thanks for your report.

When you say "if I hover on it, I see Alberta", I assume you mean you see _the status window for Alberta_ -- that is, the dark-background window with I/O statistics for Alberta.

If that's what you mean, **Alberta's status window appeared because it it was the last VPN you tried to connect to.**

The "Do not show in Tunnelblick menu" does just that -- hide the configuration so it does not appear on the Tunnelblick menu. That's all it does.

It does not hide the status window associated with the configuration, nor does it hide the configuration in the list on the "Configurations" panel of Tunnelblick's "VPN Details" window.

The status window for a configuration appears only if (A) you have tried to connect to the configuration since launching Tunnelblick, or, (B) it is the last configuration to which you tried to connect (if you haven't tried to connect to any configurations since launching Tunnelblick).

That way, if there is a single status window, it is for the last VPN you tried to connect to; if you have connected to several VPNs since launching Tunnelblick, the status window for each one will be displayed and you can choose among them.

Note that there are several other settings that control status windows; you'll find them on the "Appearance" panel of Tunnelblick's "VPN Details" window.

**Comment by fedelibre** [comment]
You are right, I did not test it carefully.
Yes, it's the status window and I see now that it displays the latest VPN I connected to.

Everything works as expected, I'm closing this.
