### ISSUE TITLE
Killswitch should disallow all internet traffic *any time* a user isn't connected to VPN

### ISSUE THREAD

**Issue by shamilovtim** [Tunnelblick/Tunnelblick#428]
Currently, the killswitch waits for disconnect in order to engage. There are a number of issues with this approach:

1. On initial computer startup before connection to the VPN, this can leak data outside the VPN and expose the user.
2. Since the killswitch seems to be operate by disabling network connectivity in System Preferences between disconnects, it's likely that it's creating a window where traffic can occur between when the wifi is enabled and the VPN client connects to a server. This doesn't seem to actually provide the security that is necessary from a killswitch. 

Simply disabling/enabling network connectivity through System Preferences will never be adequate for a killswitch. The killswitch when enabled must **filter and deny all internet traffic when the user is not connected to the VPN.**

For reference please see the way Windscribe's client implements a killswitch. Their client is available for free download.

**Comment by jkbullard** [comment]
> Simply disabling/enabling network connectivity through System Preferences will never be adequate for a killswitch. The killswitch when enabled must filter and deny all internet traffic when the user is not connected to the VPN.

For some uses it would be better to block all Internet access from the time the computer starts up, but that might make it unable to connect to resources that are needed for starting up the computer (such as policy restrictions on corporate networks or DHCP).

If you want to be "protected" as you surf the Internet or download torrents (both are typical uses), Tunnelblick's implementation works fine: connect to the VPN, start your torrent client and/or browser, and do stuff. If the VPN is interrupted, network access will be blocked until you un-block it. Quit your torrent client and/or browser, start the VPN, and continue. I admit it isn't ideal if your VPN is unreliable and you have to do it over and over, but that's a separate problem.

Denying all _Internet_ traffic is not necessarily sufficient; you may want to block all traffic even on the local network, which Tunnelblick's implementation does. (Windscribe's descriptions don't indicate that it's implementation does that; they only talk about Internet traffic.)

Windscribe can block all traffic except through the VPN because their application knows the IP addresses of its OpenVPN servers, so it can avoid using DNS to look them up. Tunnelblick doesn't  know the IP addresses of the OpenVPN servers, so it must allow OpenVPN to access DNS to get the servers IP addresses, and must allow OpenVPN to then access the servers.

[Windscribe's website says](https://windscribe.com/features/firewall):
> The "kill switch" is a snake oil feature and offers absolutely zero protection because it's a reactive measure. Between your VPN disconnecting and the program detecting that it did, packets can leave your computer over the default gateway (your ISP).

That is not true, at least for Tunnelblick's implementation of a "killswitch" and assuming the VPN is configured properly. Tunnelblick disables network access before any traffic can leak. (It does it in the middle of the process of disconnecting the VPN; "disconnecting" has several steps.)

**Comment by shamilovtim** [comment]
> That is not true, at least for Tunnelblick's implementation of a "killswitch" and assuming the VPN is configured properly. Tunnelblick disables network access before any traffic can leak. (It does it in the middle of the process of disconnecting the VPN; "disconnecting" has several steps.)

At a minimum it seems that Tunnelblick's implementation exposes the user when the computer first starts. To reproduce:

1. Have Tunnelblick configured to start on startup.
2. Upon startup, MacOS auto connects to a Wifi network and begins sending packets
3. Applications and services which use network connectivity are freely able to send packets prior to the user connecting to a VPN configured on Tunnelblick.

**Comment by shamilovtim** [comment]
I believe that one workaround would be to use a firewall like Little Snitch in tandem with Tunnelblick. That being said, Little Snitch is ~$50, can be complicated to configure for less advanced users and it would be a fantastic feature to have the packet filtering / denial built right in to Tunnelblick.

**Comment by jkbullard** [comment]
> At a minimum it seems that Tunnelblick's implementation exposes the user when the computer first starts.

Maybe, but haven't tried it. If a restart with all network access disabled results in all network access being disabled at the start, then there would not be any leak.

But there can definitely be leakage in the time between re-enabling network access and the time the VPN is established.

> it would be a fantastic feature to have the packet filtering / denial built right in to Tunnelblick.

I agree. I'd be happy to look at a PR.

**Comment by jkbullard** [comment]
> Maybe, but haven't tried it. If a restart with all network access disabled results in all network access being disabled at the start, then there would not be any leak.

OK, I tried it: I disconnected a VPN, causing Tunnelblick to block all network access. Then I restarted the computer (running High Sierra) and all network access was still blocked when it restarted. (I didn't use Wireshark or anything, but assume that if the Network System Preferences say it's blocked, it's blocked.)

So leaks should only be possible from the time you re-enable network access to the time the VPN is connected.

**Comment by shamilovtim** [comment]
Have you tried simply restarting your computer as normal without disconnecting a VPN and blocking network access? That's how I produce the problem.

**Comment by shamilovtim** [comment]
> I agree. I'd be happy to look at a PR.

I don't know C so I couldn't help with this feature. If the relevant SDKs were available and well documented in Swift I could take a look.

**Comment by jkbullard** [comment]
> Have you tried simply restarting your computer as normal without disconnecting a VPN and blocking network access? That's how I produce the problem.

You expect the computer to block network access when restarted even though it wasn't blocked before the restart? I wouldn't want to do that.

If I connect a configuration that's set to block on disconnect and then restart the computer, it works as I would expect: network access is blocked upon restart. Doing that, though, I found a bug: in that situation, Tunnelblick fails to show the "Re-enable network access" menu command. I've filed Issue #429 for that.

**Comment by shamilovtim** [comment]
I would expect the logic to be: Is Tunnelblick open? Is killswitch enabled? Is Tunnelblick connected to a VPN? If so, allow packets. If not, do not allow packets. And within the toolbar menu give the user the option to turn this feature off/on on the fly. This would completely automate the process and put it behind a simple setting: killswitch on/off.

Here's how Windscribe handles it: 
![image](https://user-images.githubusercontent.com/3495974/35356232-ccf224e6-011d-11e8-8792-70dc7a55d1de.png)

If "firewall" setting is on, the user's machine cannot send packets unless the VPN connects. And if you have Windscribe open at system start, you're never exposing packets unless they're through the VPN. It would be excellent if Tunnelblick could do the same.

**Comment by jkbullard** [comment]
See [Tunnelblick's Kill Switch](https://tunnelblick.net/killSwitch.html).

I agree that a true "firewall" would be better for some uses, but that's not what we have now.
