### ISSUE TITLE
Dropdown menu rendering takes very long

### ISSUE THREAD

**Issue by dszakallas** [Tunnelblick/Tunnelblick#447]
I have about 2000 configurations. At this size the dropdown menu take 7 seconds to render, even though I use subfolders, and the topmost size is very small.

**Comment by jkbullard** [comment]
Thanks for reporting this.

This long delay is because each time you click on the Tunnelblick icon, Tunnelblick recreates the menu. That currently involves scanning all of the configurations -- not just the items that appear at the top level of the menu.

I'll fix that by caching the secction of the menu that shows configurations (and folders of configurations). The fix will be included in the next beta release.
