### ISSUE TITLE
Do not warn about unrecognized option in pushed options

### ISSUE THREAD

**Issue by schwabe** [Tunnelblick/Tunnelblick#449]
My server pushes some Windows only options, e.g.:

    2018-04-06 11:21:00 Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:4: dhcp-pre-release (2.4.4)

Since a normal user cannot really fix the server config and also does not know that you can manually workaround this by using:

    pull-filter ignore "dhcp-pre-release "

it would be nice to have the UI not raise the big dialog box on lines that contain [PUSH-OPTIONS]

**Comment by jkbullard** [comment]
@schwabe - Thanks for your report.

The underlying problem is that Tunnelblick assumes an "Unrecognized option" message in the log means that the connection will fail, so it can display its long explanation of that message even before the actual failure occurs.

That's wrong: if the option is on the `--ignore-unknown-option` list (whether or not it was pushed), the connection will succeed.

I think Tunnelblick should  "remember" these message(s) and display them to the user only if the connection fails. That would work better whenever `--ignore-unknown-option` is being used.
