### ISSUE TITLE
Possible Team ID issue for Tunnelblick KEXTs

### ISSUE THREAD

**Issue by jelockwood** [Tunnelblick/Tunnelblick#450]
High Sierra 10.13.4 introduces a new security feature for loading Kernel Extensions called 'Secure Kernel Extension Loading' - SKEL.

This requires third-party KEXTs to be approved by the user of a Mac before they are loaded, as such this impacts Tunnelblick which uses KEXTs for TUN and TAP interfaces.

In a corporate environment it is possible to 'whitelist' these KEXTs so that individual users do not need to worry about remembering to do this. This is done by pushing a Configuration Profile via an MDM server to the client Mac. To do this you need to add either or both the 'Team ID' and the individual KEXT identifier to the Configuration Profile.

Each developer has their own unique Team ID. It turns out that the Team ID for Tunnelblick is - Z2SG5H3HC8.

However I get the impression that not all of the Tunnelblick KEXTs are being properly labelled with that Team ID. If you go to this web page - [https://www.richard-purves.com/2017/11/09/mdm-and-the-kextpocalypse-2/](https://www.richard-purves.com/2017/11/09/mdm-and-the-kextpocalypse-2/) there is a script which does the hard work for you of finding both the Team ID and individual KEXT identifiers so that you can add them to your MDM system. I have run this on a Mac and found the details for all the KEXT.

Note: Even on a freshly formatted/installed Mac has a number of third-party KEXTs as standard as these are provided by Apple, e.g. ATTO and Promise.

When I run this script on a Mac with Tunnelblick installed it lists the results like this -

Team ID: Z2SG5H3HC8  Bundle ID: net.tunnelblick.tun
Team ID:   Bundle ID: net.tunnelblick.tun
Team ID:   Bundle ID: net.tunnelblick.tap
Team ID:   Bundle ID: net.tunnelblick.tap
Team ID:   Bundle ID: net.tunnelblick.tun
Team ID: Z2SG5H3HC8  Bundle ID: net.tunnelblick.tap

As you can see only the first and last lines have a Team ID included. If I compare this with the Sophos KEXTs you will see my concern -

Team ID: 2H5GFH3774  Bundle ID: com.sophos.nke.swi
Team ID: 2H5GFH3774  Bundle ID: com.sophos.driver.devctrl
Team ID: 2H5GFH3774  Bundle ID: com.sophos.kext.oas
Team ID: 2H5GFH3774  Bundle ID: com.sophos.kext.sfm

What may possibly be relevant is that on this test Mac I have installed and removed Tunnelblick a few times. Perhaps this is leaving the additional entries.

**Comment by jkbullard** [comment]
I don't think there is a problem. I think the script is seeing two signed kexts and four unsigned kexts. Tunnelblick includes six kexts in Tunnelblick.app/Contents/Resources – two are signed and four are not signed. Each kext has a bundle ID of net.tunnelblick.tun or net.tunnelblick.tap.

On macOS 10.9 and higher, Tunnelblick will only use "tun-signed.kext" and "tap-signed.kext". (Usually only "tap-signed.kext" would be used, because if a tun device is required, Tunnelblick usually uses the built-into-macOS "utun" device and so "tun-signed.kext" is not used.)

On MacOS 10.8 and lower, Tunnelblick will use only "tun-20111101.kext" and "tap-20111101.kext", both of which are unsigned. (Again, usually only the "tap" version is usually used.)

Two other kexts, "tun.kext" and "tap.kext" are not used at all anymore and should be removed from the application. I have a PR to remove them ready and will commit and sync it sometime in the next week or two.

**Comment by jelockwood** [comment]
Yes your explanation does make sense. Is the inclusion of unsigned Kexts needed for 10.8 or older?

I will have to see but even though the unsigned Kexts would not be used on High Sierra I am concerned that they would still be flagged in System Preferences -> Security & Privacy and nag for approval.

**Comment by jkbullard** [comment]
Yes, the unsigned kexts are needed for the older versions of macOS. As I recall, the signatures required for macOS 10.9 and higher are not compatible and don't work on 10.8 and lower.

I doubt the mere presence of the kexts in the application would be a problem. Tunnelblick does its own loading of kexts dynamically as needed and thus does not copy them into any system folder – it loads them from within itself. I doubt that macOS looks at kexts until they are loaded, and then would only look at the kext being loaded.

Let's leave this Issue open until that's been verified.

**Comment by jkbullard** [comment]
Yes, as I recall, newer versions of macOS require v2 signatures, but older versions of macOS do not accept v2 signatures. They do accept unsigned kexts (or kexts with v1 signatures). To have a single binary that works on older systems and newer systems, we include an unsigned version of each kext and a version signed with V2. (And two other unsigned copies which will be removed in the next beta release of Tunnelblick.)

Because Tunnelblick never copies the kexts to a system folder (it loads them from within its own Resources folder), I'd be surprised if macOS will complain about the unsigned kexts. (Then again, Apple does surprise me – unhappily – fairly regularly.)

If/when Apple does start complaining about such kexts, it will probably be time for Tunnelblick to require macOS 10.9 or higher, and include only v2 kexts. Pessimistic prediction: by then a new macOS will require v3 signatures, which won't work on older versions : (

**Comment by jkbullard** [comment]
Closing this Issue; b743b911e46a01f931496ca0fa94f431d8a64408 removed the unused kexts.

Only "tun-signed.kext" and "tap-signed.kext" would need to be whitelisted because only they can be used on macOS 10.9 and higher.

If your corporate VPNs use TUN connections, you don't need to whitelist "tap-signed.kext".

If your corporate VPNs allow OpenVPN to use the built-into-macOS "utun" driver, you don't need to whitelist "tun-signed.kext".
