### ISSUE TITLE
whichopensslcnf file from easy-rsa has incorrect permissions

### ISSUE THREAD

**Issue by bpharriss** [Tunnelblick/Tunnelblick#451]
The whichopensslcnf file in Contents/Resources/easy-rsa-tunnelblick has incorrect file permissions. The file is -rw-r--r--; it should be -rwxr-xr-x.

**Comment by jkbullard** [comment]
Execute permissions are not included because the file should not be executed from that location.

When Tunnelblick is installed, the "easy-rsa-tunnelblick" folder and its contents, including whichopensslcnf, are copied into ~/Library/Application Support/Tunnelblick/easy-rsa and the ownership and permissions on the new folder and its contents are adjusted. The permissions on that copy of whichopesslcnf are r-x------, which is correct.
