### ISSUE TITLE
CFBundleShortVersionString includes build number

### ISSUE THREAD

**Issue by bwmorales** [Tunnelblick/Tunnelblick#461]
Build number should be in `CFBundleVersion` only. This makes it tricky to automate deployment in some scenarios.

**Comment by jkbullard** [comment]
Apple has changed their description of both `CFBundleVersion` and `CFBundleShortVersionString ` in the years since Tunnelblick first started using them.

Originally, `CFBundleShortVersionString` was a "marketing" string and was meant to be human-readable. There were no restrictions on its format or contents. Now Apple says that it must be a string of exactly three period-separated numbers in the form "major.minor.maintenance".

Originally, `CFBundleVersion` was a machine-readable string meant to specify the version of the application and could consist of from one to three period-separated numbers, with no specific meanings attributed to the numbers. Now at least two numbers are required and Apple specifies meanings to the numbers ("major.minor.maintenance"). They allow a suffix that can include a build number, but that build number is limited to a maximum of 255.

I'm not sure we want to change this in Tunnelblick.
 * We (and others) have built infrastructure based on Tunnelblick's longstanding formats, and changing the formats might mean added complexity to deal with both the old and new formats.
 * Since our build numbers are high (in the 5000's) to allow for comparisons to any Tunnelblick build (this is a requirement of the Sparkle Updater software that we use for updating Tunnelblick), it isn't clear how we could include them because Apple limits them to a maximum of 255.
 * Including a "b" suffix with a build number to `CFBundleVersion` might break comparisons of versions.
 * There is no way to specify a beta build in `CFBundleShortVersionString`.

Can you share some scenarios that you want to automate that Tunnelblick's formats for these strings makes tricky?

**Comment by bwmorales** [comment]
Thank you for the reply; that's good information to have. The tools we're using for mass deployment do version comparisons automatically, based on the results of a query on `CFBundleShortVersionString`. The current method breaks some of the automation, but it's easily fixed with `sed`. We can make the exception without too much work; I just figured the project would want to embrace what appears to be the most current standards from Apple. It's all a trade-off, though, and if the community has infrastructure built around the legacy standards, then it makes sense that the change would bring unwelcome complexity.
