### ISSUE TITLE
How to make own application ?

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#465]
Hi Guys,

You are doing really great application and we are very impressed and appreciate for your doing. 
I have built all source successfully. It works great. 

Now I am moving to next step. Can you provide us direction what we should do on following items ?

1. We want to change application name. Is it possible ? How to do that ? Now if we change the application, it wont get it run.

2. We would like to upload the application to AppStore under your license. We are thinking we need to make text "Powered by Tunnelblick" in some appear of the app. 
When we archive the app, XCode throws below error in ExternalBuildCleanScript:

`error: Invalid action. Must be empty or 'clean'`

Do you any experience archiving the app and uploading to AppStore ?

Thank you guys.

**Comment by jkbullard** [comment]
1. Yes, you can change the name. See [Rebranding Tunnelblick](https://tunnelblick.net/cRebranding.html). That page hasn't been updated in a long time, so the search/replace procedures may change for newer versions of Xcode.

2. The problem archiving the app was fixed in 1b648574ff1c1b6b1d89ecce723c5b3d7c3fc2e3.

However, you cannot put Tunnelblick in the app store. It does things that app store apps are not allowed to do, so Apple won't allow it.

**Comment by tugsjargal1** [comment]
Thank you @jkbullard  
You are awesome! :)
