### ISSUE TITLE
How to add to the Dock when installing from .dmg ?

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#473]
Hi guys,

Actually I am newer one for MACOS development. 
Do you have an experience about how to add to the Dock when installing the from .dmg ?
If so, please share us.

Thank you.

**Comment by jkbullard** [comment]
If you mean showing a Tunnelblick icon in the Dock while Tunnelblick is running, that's not needed because the Tunnelblick icon appears in the menu bar (technically, in the status bar, the right side of the menu bar).

If you mean adding Tunnelblick's icon to the dock "permanently", so it is there even when Tunnelblick isn't running, don't do that! It's impolite to make changes to the user's Dock. It's also not usually needed: most users just leave Tunnelblick running all the time, even when they're not connected to a VPN.

**Comment by tugsjargal1** [comment]
@jkbullard 
Thank you.

**Comment by bbrk24** [comment]
> If you mean showing a Tunnelblick icon in the Dock while Tunnelblick is running, that's not needed because the Tunnelblick icon appears in the menu bar (technically, in the status bar, the right side of the menu bar).

@jkbullard That just opens a small menu at the top of the screen. If I've lost the main window with the logs and whatnot, how do I find it again? I generally use the dock icon for other applications, and it always leaves me a bit confused when I can't find Tunnelblick in the dock even though it is running.

Sorry for pinging you on such an old issue but I couldn't find any other relevant pages.

**Comment by jkbullard** [comment]
> That just opens a small menu at the top of the screen.

That menu includes a "VPN Details…" item. Click that and you get Tunnelblick's main window.

See [Using Tunnelblick](https://tunnelblick.net/czUsing.html).

**Comment by swaty007** [comment]
Move it from applications to dock
