### ISSUE TITLE
Uninstaller application is not responding

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#480]
Hi guys,

I have re-branded Tunnelblick. We can not get work Uninstaller application.
When we click "Uninstall" button, it asks authorizing. After enter the password, the app freezes. 
It is not responding. 

Last line of the log file(/tmp/MyApp Unsintaller Log.txt) is 
 
```
Problem: Error (1) trying to remove bad links inside /
Problem: Error (1) trying to remove uchg and/or uappnd flags on or inside /

```

How to fix this issue ? I am using Mac Book Pro 10.13.2.

Thank you.

**Comment by jkbullard** [comment]
I don't know, but it looks like something very bad is happening, since the uninstaller is trying to do something in / (instead of in /Applications/Rebranded.app). Make sure you don't have any spaces in the name of your rebranded application. That's something that I imagine could cause such a problem.

The other thing you can try is to use the regular Tunnelblick uninstaller (not your rebranded one) by following the instructions under *To uninstall an earlier version of Tunnelblick which is not located in /Applications or the Trash, or to uninstall RaptorVPN, Urban Shield VPN, or some other rebranded version of Tunnelblick:* on the Tunnelblick website [Uninstalling Tunnelblick page](https://tunnelblick.net/cUninstall.html). That might tell you if something is wrong with the uninstaller script, or something went wrong when you rebranded.

**Comment by tugsjargal1** [comment]
Hi @jkbullard 

There is no any space in the name of my rebranded application.
Also test functioning works well. This function throws the message : 
`The MyApp uninstall test succeeded. `

I am launching Uninstaller application from the MyApp Uninstaller.dmg file.

Below a few lines are written In the log file:

```
2018-08-28 09:53:04:      >>> Does not exist: /U
2018-08-28 09:53:04:      >>> Does not exist: 
2018-08-28 09:53:04:      >>> Does not exist: r
2018-08-28 09:53:04:      >>> Does not exist: /tug
2018-08-28 09:53:04:      >>> Does not exist: j
2018-08-28 09:53:04:      >>> Does not exist: rg
2018-08-28 09:53:04:      >>> Does not exist: l/Libr
2018-08-28 09:53:04:      >>> Does not exist: ry/Log
2018-08-28 09:53:04:      >>> Does not exist: /Di
2018-08-28 09:53:04:      >>> Does not exist: gno
2018-08-28 09:53:04:      >>> Does not exist: ticR
2018-08-28 09:53:04:      >>> Does not exist: port
```

This message reads like: 
/Users/tugsjargal/Library/Log/DiagnosticR port

Seems that our uninstall script is having some issue. 

Thanks.

**Comment by tugsjargal1** [comment]
Hi @jkbullard 

Do you have any suggestion ?

Thank you.

**Comment by jkbullard** [comment]
@tugsjargal1 - My only suggestion is that you need to debug your rebranded uninstaller, but that seems so obvious that I didn't think it worth mentioning.

**Comment by tugsjargal1** [comment]
Thank you @jkbullard 
Seems that related broken MACOS computer.
