### ISSUE TITLE
Tunnelblick hangs when OSX wakes up from sleep

### ISSUE THREAD

**Issue by muzzah** [Tunnelblick/Tunnelblick#482]
If I have closed the lid while tunnelblick is connected, then later come back after the laptop has slept, I find that 70-80% of the time, tunnelblick will hang and I have to SIG KILL it.

Then sometimes, the openVPN process hangs and even if i kill all the processes associated with tunnelblick, upon restarting, it wont event think there is a network active and just loop saying reconnecting.

Using MacOS 10.13.6 & Tunnelblick 3.7.6a (build 5080)

**Comment by jkbullard** [comment]
Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by muzzah** [comment]
Apologies, please find the diagnostic text [here](https://pastebin.com/f72CUJKu)

This was the log after following that info, connecting to my vpn then putting my laptop to sleep last night by closing the lid. It turns out my battery died so the laptop would have gone beyond hibernate mode I suspect but not sure how OSX handles that.

Once the laptop booted, the wifi connected but the tunnelblick process hung and when I put my mouse over the tunnelblick icon on the menu bar, i get the beach ball. To access the diagnostic text, I had the kill the tunnelblick process and then restart it.

I also took a sample and spindump of the process through Activity Monitor though I would prefer to send that privately due to the private info in there.

**Comment by jkbullard** [comment]
Thanks for your report.

 1. Try the latest Tunnelblick beta, which fixes some problems disconnecting a VPN.

 1. Try removing the "sndbuf 0", "rcvbuf 0" lines from your configuration. The are almost never needed and can interfere with normal operation of the VPN.

 1. Please restart your computer before doing a new test, to make sure that the network setup is back to normal and isn't in an inconsistent state (which can happen when the OpenVPN process is killed unexpectedly because OpenVPN may not be able to completely "undo" the VPN setup). The new test should consist of a normal successful connect/disconnect sequence _without sleeping the computer_.

If these steps don't resolve the problem, a spindump/sample can be sent to developers@tunnelblick.net.
