### ISSUE TITLE
Building just third_party with "make all" command, results in error of LZO

### ISSUE THREAD

**Issue by jalanga** [Tunnelblick/Tunnelblick#488]
I am trying to build the third party libraries for Tunnelblick. I tried on MacOS 10.12 and 10.13, I tried with Xcode 7.3.1, 8.3 and 10. gcc is installed, I accepted the xcode license, but when I try to build it, on all systems I get the following error when is building lzo library:

```
THIRD_PARTY: Building LZO...
for a in x86_64; do \
    cd /Users/new/Desktop/Tunnelblick/third_party/build/lzo-2.10 ; \
    echo "Clean LZO for $a" ; \
    /Users/new/Downloads/Xcode.app/Contents/Developer/usr/bin/make clean; \
    echo "Configure LZO for $a" ; \
    CC=gcc \
    CFLAGS="-isysroot  -Os -mmacosx-version-min= -arch $a" \
    ./configure --build=$a-apple-darwin \
                --prefix=/Users/new/Desktop/Tunnelblick/third_party/build/staging/lzo-2.10_$a/ \
                --includedir=/Users/new/Desktop/Tunnelblick/third_party/build/staging/lzo-2.10/include/ \
                --disable-dependency-tracking \
                --disable-asm ; \
    echo "Build LZO for $a" ; \
    /Users/new/Downloads/Xcode.app/Contents/Developer/usr/bin/make; \
    echo "Install LZO to /Users/new/Desktop/Tunnelblick/third_party/build/staging/lzo-2.10_$a" ; \
    /Users/new/Downloads/Xcode.app/Contents/Developer/usr/bin/make install; \
    cd "/Users/new/Desktop/Tunnelblick/third_party"; \
done
Clean LZO for x86_64
make[2]: *** No rule to make target `clean'.  Stop.
Configure LZO for x86_64
configure: Configuring LZO 2.10
checking build system type... x86_64-apple-darwin
checking host system type... x86_64-apple-darwin
checking target system type... x86_64-apple-darwin
checking whether to enable maintainer-specific portions of 
Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/new/Desktop/Tunnelblick/third_party/build/lzo-2.10':
configure: error: C compiler cannot create executables
See `config.log' for more details
Build LZO for x86_64
make[2]: *** No targets specified and no makefile found.  Stop.
Install LZO to 
/Users/new/Desktop/Tunnelblick/third_party/build/staging/lzo-2.10_x86_64
make[2]: Nothing to be done for `install'.
mkdir -p /Users/new/Desktop/Tunnelblick/third_party/build/staging/lzo-2.10/lib
lipo /Users/new/Desktop/Tunnelblick/third_party/build/staging/lzo-2.10_*/lib/liblzo2.a -create -output /Users/new/Desktop/Tunnelblick/third_party/build/staging/lzo-2.10/lib/liblzo2.a
fatal error:
/Users/new/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Users/new/Desktop/Tunnelblick/third_party/build/staging/lzo-2.10_*/lib/liblzo2.a (No such file or directory)
make[1]: *** [built-lzo] Error 1
Install LZO to /build/staging/lzo-2.10_x86_64
make[1]: *** No rule to make target `install'.  Stop.
mkdir -p /build/staging/lzo-2.10/lib
lipo /build/staging/lzo-2.10_*/lib/liblzo2.a -create -output /build/staging/lzo-2.10/lib/liblzo2.a
fatal error: /Users/new/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /build/staging/lzo-2.10_*/lib/liblzo2.a (No such file or directory)
make: *** [built-lzo] Error 1
```

I think is from ```checking whether the C compiler works... no``` this line. But I tried everything I found on the internet to pass that line without success.

**Comment by jkbullard** [comment]
@jalanga - Are you following the instructions in "Building Tunnelblick from Source Code.markdown" at the root level of the source code?

**Comment by jalanga** [comment]
@jkbullard, almost I installed all the things, and I run from the terminal the make all command, I will try to build the all app from Xcode

**Comment by jkbullard** [comment]
@jalanga - Three ways to get Tunnelblick's versions of OpenVPN that you can use from the command line:

 1. If you just want to run OpenVPN from the command line, install Tunnelblick and then use one of the OpenVPN binaries contained within it from the command line. The binaries are located in subfolders of Tunnelblick.app/Contents/Resources/openvpn that are named for the OpenVPN and SSL version of the OpenVPN binary they contain. (Each subfolder also contains an "openvpn-down-root.so" binary matched to the OpenVPN binary.) This has the advantage that when you update Tunnelblick, your version of OpenVPN will be updated. (There's a symlink named "default" in the "openvpn" folder which points to the folder containing Tunnelblick's default version of OpenVPN, currently a version of 2.4 using OpenSSL.)

 2. If you want only an OpenVPN binary and don't want Tunnelblick installed, copy the binary you want from the Tunnelblick.app contained in a downloaded copy of Tunnelblick.dmg.

 3. If you want to build it yourself (because you don't trust our binaries), 90% (that's just a guess) of the build time is spent building OpenVPN or the components that are static-linked to it (OpenSSL, LibreSSL, lzo, lz4), so it wouldn't help much for you to just build OpenVPN. You can build all of Tunnelblick, then extract and use the binary for the version of OpenVPN/SSL that you want. The binaries are located in subfolders of tunnelblick/build/Release/Tunnelblick.app/Contents/Resources/openvpn (assuming you built a "Release" version of Tunnelblick, and not a "Debug" version).

**Comment by jalanga** [comment]
Thank you for you time and answer, I just wanted the openvpn binary, now I have it. You are the best, sorry for this issue, I am new to MacOS world, I am an Linux and Windows buy who just bought a mac. Have a nice day.
