### ISSUE TITLE
OpenVPN Server Breaks Port Forwarding after Disconnect on  Fast User Switching 

### ISSUE THREAD

**Issue by essandess** [Tunnelblick/Tunnelblick#493]
I observe that Tunnelblick breaks **all** port forwarding settings if a [server](../../../../essandess/macos-openvpn-server/tree/master/openvpn-server-tun.tblk) is configured to disconnect on Fast User Switching. 

Yes, the obvious [solution](https://github.com/essandess/macos-openvpn-server/blob/master/README.md#tunnelblick-configuration) is "Don't go like that if it hurts!", Henny Youngman.

But this is still some kind of bug that took me a while to track down, so here's the issue.

Setup:
1. Tunnelblick OpenVPN [Server](../../../../essandess/macos-openvpn-server/tree/master/openvpn-server-tun.tblk) connected to Airport Extreme router with port forwarding.
2. Default disconnect on Fast User Switch
3. Launch tunnelblick and the OpenVPN server.
4. Switch users.

Observe (`nmap`, `wireshark`, `tcpdump`) that packets sent to the server on **all** ports forwarded to the server by the router (e.g. 22, 80, 443, etc.) are not routed back to the requesting client. This breaks the LAN. Services on ports not handled by router port forwarding continue to work. My best guess is that this is some routing table or NAT-within-a-NAT issue.

Aside from configuring Tunnelblick correctly as shown below, the quick fix on the macOS server is to toggle the network Location in System Preferences>Network.

I'm posting this in case anyone else encounters this issue, or if it points to any larger or related routing table issues.

Here are the recommended standard and advanced Tunnelblick settings for a server:

| [Tunnelblick](../../../../Tunnelblick/Tunnelblick) Settings |  Advanced… |
:------------------------------------------------------------:|:-------------------------:
![Tunnelblick Settings](../../../../essandess/macos-openvpn-server/blob/master/images/Tunnelblick%20Settings.png)|![Tunnelblick Advanced Settings](../../../../essandess/macos-openvpn-server/blob/master/images/Tunnelblick%20Advanced%20Settings.png)

**Comment by jkbullard** [comment]
This sort of symptom is usually caused by a problem disconnecting a configuration. What happens when you just disconnect, instead of doing a fast user switch?

The info described in [Before You Post](https://tunnelblick.net/cBeforeYouPost.html) might help pinpoint any such problem.

> the quick fix on the macOS server is to toggle the network Location in System Preferences>Network.

Does setting "On expected disconnect" and "On unexpected disconnect" to "Reset primary interface" clear the symptom? (It may not if there are multiple active network interfaces.)

**Comment by essandess** [comment]
I (believe that I) observed that this issue occurs whether or not the OpenVPN server is up.

I’m also trying to see if these setting changes fix #340, but I haven’t had a chance to reboot the server.

If I “Never load tun driver” as per the link above, how will this affect the “reset primary interface“ settings?

**Comment by jkbullard** [comment]
@essandess - The first thing to do is to get the configuration working properly (both connecting and disconnecting without errors) when **not** set to connect when the computer starts. I assume you've done that.

The "Never load tun driver" setting does not affect "reset primary interface". But it is also not necessary. "Load Tun driver automatically" should be fine; Tunnelblick will not load the driver if it is not needed (i.e., it will not load unless it is a tun connection and the configuration file includes"dev-type tun"). OpenVPN will use the macOS-built-in "utun" driver unless "dev-type tun" is in the configuration, so thats the only situation in which the tun driver needs to be loaded.)

**Comment by jkbullard** [comment]
@essandess - OK, thanks.

 * I've addressed the multiple utun interfaces in more detail in a private email to you. Briefly, my hypothesis is that OpenVPN creates a utun interface each time it starts, and although it deletes the interface when it exits normally, if OpenVPN crashes it doesn't delete the interface, and when started again it creates a new one. If OpenVPN crashes five times, there will be five "leftover" utun interfaces. The solution is to avoid having OpenVPN crash.

 * "**dev** tun" (not to be confused with "**dev-type** tun") tells OpenVPN to use a tun device and not a tap device. OpenVPN will use a "tun" device (which needs a non-macOS driver/kext to be loaded) if there is a "dev-type tun" option in the configuration files. Otherwise, OpenVPN will use a "utun" device. A utun driver/kext has been built into macOS since 10.6.8.
