### ISSUE TITLE
Leaving Tunnelblick running on an OSX User Account completely disables internet for other OSX User Accounts on the machine, forcing the user to reboot

### ISSUE THREAD

**Issue by tugsjargal1** [Tunnelblick/Tunnelblick#497]
When a user enables Tunnelblick on one OSX User Account, logging out and entering another OSX account will disable the internet entirely. 

For example, given this scenario, there are two people using one MacBook, named [USER1] and [USER2]. 

[USER1] enables Tunnelblick on their OSX User Account/Profile. Later, without exiting Tunnelblick, they log out of their OSX Account, and [USER2] logs into their OSX User Account/Profile. [USER2] does not open Tunnelblick, instead they go to open their browser. Their browser will instead not connect to the internet. There is no way to access the internet again unless [USER2] reboots the machine entirely. 

Do you have any idea to fix this issue ?
How to solve this issue ?

Thank you.

**Comment by jkbullard** [comment]
When you logout, Tunnelblick will disconnect from all VPNs that you have used it to connect to*, and should restore the computer's network settings to the way they were before the VPN was connected in the first place. Thus the second user should have no problem accessing the Internet.

I suspect what is happening here is that the disconnection is not completing correctly. To test this, restart the computer, log in as [USER1], connect the VPN, then disconnect the VPN and examine the Tunnelblick log for errors during the connection process.

There are several things that can cause errors during the disconnection process. The most common one is the use of "user none" and "group nogroup" with configurations that require OpenVPN to make routing changes. OpenVPN makes the routing changes when it connects the VPN because it is running as root and has the privileges to do so. However, it stops running as root (and runs as nobody) after the VPN is connected and is then unable to restore the routing when it disconnects the VPN. Thus the network setup is left with everything routed to a VPN server which will not respond because the VPN is disconnected.

* That doesn't happen for VPNs set up to connect "when computer starts". Such VPNs are left alone when the user logs out.
