### ISSUE TITLE
config property useShadowConfigurationFiles has no effect

### ISSUE THREAD

**Issue by aashh** [Tunnelblick/Tunnelblick#509]
**Describe the bug**
Tunnelblick Preferences [documentation](https://tunnelblick.net/cBeforeYouPost.html) describes the boolean `useShadowConfigurationFiles` which turns off the creation of config shadow config copies. However turning off the boolean does not have the described effect.

**To Reproduce**
1. Quit Tunnelblick
2. Run `defaults write net.tunnelblick.tunnelblick useShadowConfigurationFiles -bool no`
3. Remove shadow with `rm -rf /Library/Application Support/Tunnelblick/Users/*/*.tblk`
4. Start Tunnelblick
5. Use or install a user-specific VPN configuration (i.e., under `$HOME/Library/Application Support/Tunnelblick`)
6. Observe that the configuration is copied into `/Library/Application Support/Tunnelblick/Users/...`

**Expected behavior**
Per [documentation](https://tunnelblick.net/cBeforeYouPost.html): "useShadowConfigurationFiles: … If cleared or not present, the original of each configuration file will be used"

**Diagnostic information**
Tunnelblick 3.7.8 (build 5180)
Apple macOS 10.13.6

**Comment by jkbullard** [comment]
@aashh - Thanks for pointing this out.

The `useShadowConfigurationFiles` preference is obsolete and no longer used. It was introduced when "shadow copies" were first introduced many years ago. Shadow copies **must** be used for security reasons, so they are **always** used, no matter what the value of this preference is.

This issue has been fixed by revising the [preferences documentation](https://tunnelblick.net/cPreferences.html).

That document is not well maintained; there are many missing preferences and some that are listed but no longer used.  The best list of preferences is in the [defines.h source](https://github.com/Tunnelblick/Tunnelblick/blob/master/tunnelblick/defines.h), starting at line 550. There are two lists, one for application preferences, the other for per-configuration preferences.
