### ISSUE TITLE
Text from two settings screens is displayed

### ISSUE THREAD

**Issue by dandaka** [Tunnelblick/Tunnelblick#522]
**Describe the bug**
When switching between settings windows, content from previous window is still displayed when new one is shown.

**To Reproduce**
1. Open settings
2. Click on tabs
3. See error like screenshot

**Expected behavior**
No overlay

**Screenshots**
![image](https://user-images.githubusercontent.com/2384694/55166341-9c7e6d00-5177-11e9-84d2-9e6450610ed0.png)

**Log**
I don't include log, since it is not related to VPN connection. If information is needed, you can take it here https://github.com/Tunnelblick/Tunnelblick/issues/521

**Comment by robertleeblairjr** [comment]
I had posted about this same experience, that I was having, in the tunnelblick-discuss group.
[https://groups.google.com/forum/#!topic/tunnelblick-discuss/okCCxodKXC0](url)

I uploaded some videos of the fade transition problem and screenshots of my system information when I posted the cosmetic issue. Also, I'veThey're below if you'd like to view them.

Fade Transition Videos for Internal, External, and Dual Display.
[https://mega.nz/#!HYE2gSzZ!_WebALEWi_S3RF8ni8vrsbPAkqPWsMTG4VYeKCB-wyo](url)

Screenshots of System Information for Internal, External, and Dual Display.
[https://mega.nz/#!iU80TAYK!95C2KFjiw7xnCNEnvQLdVG5p-x7nHwEGIzpp7e0lVfU](url)

Another discrepancy that I had reported was the screen resolution reported by the app in the Appearance menu was based on the "UI Looks Like" entry for system_profiler instead of the actual display resolution. However, this may be intended by the developers.

**Comment by robertleeblairjr** [comment]
@m5o Would it be very difficult for the developers to include an enable/disable animations function for the user interface? Does TB use system animations or have custom? I would think this enable/disable animations would include the fade transition for menu items. I'm willing to test a build. I'm not familiar with Obj-C so it would take a tremendous amount of work for me to fork, learn, and incorporate this feature.

**Comment by jkbullard** [comment]
@robertleeblairjr wrote:
> Would it be very difficult for the developers to include an enable/disable animations function for the user interface? Does TB use system animations or have custom? I would think this enable/disable animations would include the fade transition for menu items.

Tunnelblick uses system animation for changing panels of the "VPN Details" window and the menu icon darkening/lightening.

I think it would be a bad idea to get rid of the menu item transition and only show connected or disconnected status. It isn't appropriate because VPN connections can take a long time to establish, just like Wi-Fi connections. So having an enable/disable animations in the user interface isn't very useful for the menu item.

For "VPN Details" panel switching, I would feature-accept (and prefer) a PR that fixed it by fading the old panel out before fading the new panel in. Or one that makes the fading optional, either via a checkbox or via a preference that must be set by Terminal.

> Another discrepancy that I had reported was the screen resolution reported by the app in the Appearance menu was based on the "UI Looks Like" entry for system_profiler instead of the actual display resolution. However, this may be intended by the developers.

 @robertleeblairjr wrote:

> Another discrepancy that I had reported was the screen resolution reported by the app in the Appearance menu was based on the "UI Looks Like" entry for system_profiler instead of the actual display resolution. However, this may be intended by the developers.

Please file this as separate Issue; don't clutter this Issue with other problems.

**Comment by robertleeblairjr** [comment]
> @robertleeblairjr wrote:
> 
> > Would it be very difficult for the developers to include an enable/disable animations function for the user interface? Does TB use system animations or have custom? I would think this enable/disable animations would include the fade transition for menu items.
> 
> Tunnelblick uses system animation for changing panels of the "VPN Details" window and the menu icon darkening/lightening.
> 
> I think it would be a bad idea to get rid of the menu item transition and only show connected or disconnected status. It isn't appropriate because VPN connections can take a long time to establish, just like Wi-Fi connections. So having an enable/disable animations in the user interface isn't very useful for the menu item.
> 
> For "VPN Details" panel switching, I would feature-accept (and prefer) a PR that fixed it by fading the old panel out before fading the new panel in. Or one that makes the fading optional, either via a checkbox or via a preference that must be set by Terminal.
> 
> > Another discrepancy that I had reported was the screen resolution reported by the app in the Appearance menu was based on the "UI Looks Like" entry for system_profiler instead of the actual display resolution. However, this may be intended by the developers.
> 
> @robertleeblairjr wrote:
> 
> > Another discrepancy that I had reported was the screen resolution reported by the app in the Appearance menu was based on the "UI Looks Like" entry for system_profiler instead of the actual display resolution. However, this may be intended by the developers.
> 
> Please file this as separate Issue; don't clutter this Issue with other problems.

Yep, sorry about that. It was just on my mind at the time when I was responding to the fade transition issue.

I did finally get this to build in Xcode 10.2.1 with 10.0 compatibility for target 10.10 on 10.14.5. It seemed to fail quite a bit from the initial compiling of the third-party tools. Sparkle was definitely a hassle and I've not fully tested my unsigned build but for connecting, logs, and other general use it seems to be fine. However, I just applied the patch that was suggested by m5o, which effectively disables it through nullifying the timing. I understand the use of animations which look nice but if they don't work then it loses the entire purpose. Considering that it's only candy to the interface. It would be nice if there was a function to enable/disable the fading until it's more operational with macOS 10.14+. However, I know little about ObjC. BTW. Thanks for replying.

**Comment by jkbullard** [comment]
This has been fixed by 341725f3.

**Comment by m5o** [comment]
Thank you @jkbullard 🙇
