### ISSUE TITLE
apply Apple’s Human Interface Guidelines to Preferences

### ISSUE THREAD

**Issue by m5o** [Tunnelblick/Tunnelblick#528]
Hey Tunnelblick Team 👋 

**Describe the “bug"**
I use Tunnelblick on a regular basis and have to open the settings from time to time. 
Coming from a design background my eyes cannot unsee some of the unaligned labels, backgrounds, and checkboxes in the preference window. Sorry 🙈

Before, I would like to ask if such contributions are welcome? 
I don’t know any ObjC and would mainly tweak the `*.xib` files with Xcode.

**Expected behavior**
Polish and refine spacing and position of Tunnelblick preferences.
📝 https://developer.apple.com/design/human-interface-guidelines/macos/app-architecture/preferences/

No changes to behavior and wording, only polishing the arrangement.

🤓✌️

**Comment by jkbullard** [comment]
Such contributions would be very welcome.

However, please understand that the window contents are arranged to enable us to replace the English strings with strings in any of the 40 languages to which Tunnelblick is translated.

Instead of using the standard scheme of creating a .xib for each language, which means that translators must work with .xibs, Tunnelblick has a single .xib for each window [1]. When the window is loaded, Tunnelblick dynamically replaces each English string in the .xib with the corresponding string from the language currently being used. This means our translators only need to work with strings (using [Crowdin](https://crowdin.com)) – they don't need to know how to edit .xibs.

We leave a lot of space for strings because a string in English may be translated to a longer string in some other language. (And yes, this makes our windows much larger than they need to be in ideographic languages such as Chinese, whose translated strings are much shorter than the English strings they are based on.)

[1] Technically, we have two .xibs per window, one for left-to-right languages such as English, and one for right-to-left languages such as Arabic. The .xibs are more-or-less mirror-images of each other. And the .xibs themselves do not contain the English strings; they just contain placeholder strings that are used for layout. When Tunnelblick loads a window, it replaces these placeholder strings with the appropriate string from the current language, which might be English or might be some other language.

**Comment by m5o** [comment]
Would it possible to use [Previewing Localizations in Interface Builder](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/TestingYourInternationalApp/TestingYourInternationalApp.html) to test these 40 available localizations?

<img width="562" alt="Screenshot 2019-04-12 at 13 39 31" src="https://user-images.githubusercontent.com/26371/56034727-6ff65380-5d28-11e9-8ddc-05749b050c9c.png">

**Comment by usercase** [comment]
I think the proposal is a good idea and I hear the problem of localization. 

**1. Pure English tunnelblick**
Maybe a simple solution would be to build a pure English tunnelblick, I am a non-english and I prefer to use the app in this language because I can easierly find help in English than in my own language. Most of my tech app remain in English : I want to be able to check the official documentation and  their forum or github repo.

**2. Char limitation**
Otherwise, the translator could get a char limitation per string, thanks to info bubble (tooltip) system on the GUI, nobody will be lost. The tooltips are pretty clear.

**Big thanks to all developers**

**Comment by jkbullard** [comment]
@usercase -

**Re Pure English tunnelblick**: If you want to use Tunnelblick in English instead of your system's default language, you can enter the following command in Terminal:

`defaults write net.tunnelblick.tunnelblick AppleLanguages '("en-US")'
`

To undo that, enter:

`defaults delete net.tunnelblick.tunnelblick AppleLanguages
`

This isn't particular to Tunnelblick or English; it's part of the macOS language system. You can do it with any application and you can specify any language.

**Re: Char limitation**: Because of proportional spacing, limiting the number of characters in a string doesn't work well. The translators try to minimize the size of their translations so they fit, but that's sometimes difficult.

Also, please remember that you can usually adjust the size of a window to see more if text is being cut off. That doesn't always help, but often it does.

**Comment by m5o** [comment]
ℹ️ I got an VM with [macOS 10.11.6 and Xcode 7.3.1](https://github.com/Tunnelblick/Tunnelblick/pull/529#issuecomment-487754647) running - and try to submit some improvements.

**Comment by jkbullard** [comment]
@m5o - 👍
