### ISSUE TITLE
leak IP when connecting to vpn

### ISSUE THREAD

**Issue by glglgl123** [Tunnelblick/Tunnelblick#535]
**Describe the bug**
Hello sorry for my bad English, im new on macOS and tunnelblick, at the moment of connecting to the VPN server - the real ip is getting leaked.

**To Reproduce**

when im picking "connect to the server" and the dialogue menu with yellow text - "Getting configuration ","Authorization" appears - i can get on any site (for example to check my ip) and theres will be my real IP.

**Screenshots**

the moment when the leak occurs

![unknown2](https://user-images.githubusercontent.com/47640759/57961349-0b29ac80-7917-11e9-9149-747fd0061431.png)
![unknown3](https://user-images.githubusercontent.com/47640759/57961350-0b29ac80-7917-11e9-9904-7c0ac9435c6f.png)

**Comment by jkbullard** [comment]
That is as it should be. When you click "Connect", the connection does not take place immediately. It takes time, often several seconds or even tens of seconds, for the VPN to connect.

Until the VPN is connected, you are not using the VPN, and your "real" IP address will show up if you go to a website such as whatismyipaddress.com. It's the same if you go to such a website before clicking "Connect".

When the VPN is connected, the text in the window will turn from yellow to green. This is shown in the following screenshot:

![Screen Shot 2019-05-17 at 8 57 34 PM](https://user-images.githubusercontent.com/127273/57962581-a9e9e500-78e6-11e9-887c-9568ace17380.png)

If you are not _ever_ connecting to the VPN, that is a different problem. Please create another issue for that.

When the VPN is connected, there are two ways that your IP address can leak:
 1. If all IPv4 traffic is not going through the VPN; or

2. If you allow IPv6 traffic, even if it goes through the VPN. Some IPv6 addresses contain your IPv4 address, and if the VPN server does not filter them, they can leak your IPv4 address.

To be sure no IPv4 leak will occur (1, above), you can put a check in the **Route all IPv4 traffic through the VPN** checkbox on the Settings tab. Make sure to select the configuration in the list on the left side of the window before putting a check in the box. (This may not be necessary because the VPN configuration or the server may force this, but by putting a check in the box you can be sure no IPv4 traffic will be leaked).

To be sure no IPv6 leak will occur (2, above), you can put a check in the **Disable IPv6" (tun only)** checkbox on the Settings tab. Make sure to select the configuration in the list on the left side of the window before putting a check in the box.

**Comment by glglgl123** [comment]
maybe should make a function? to block all outgoing traffic while connecting to VPN

**Comment by jkbullard** [comment]
Do you mean we should have one checkbox instead of two? There are two different checkboxes because they do two different things. Depending on why you you using a VPN and how your VPN server is set up, you may want to have both checked, only one checked, or neither checked. That can't be replaced with a single checkbox.

Do you mean blocking all outgoing traffic after you have clicked "Connect" but before the VPN is connected? Outgoing traffic will not be blocked _before_ you start connecting, so why does allowing a few seconds more matter?

(Also, it is not easy to do that: if you block _all_ outbound traffic you can't communicate with the VPN server, or with DNS to get the server's IP address if it isn't given. What VPN server you communicate with is determined dynamically, so we can't just "allow traffic to/from IP address XXXXX).

Note: Tunnelblick does have a way to block all traffic when a VPN _disconnects_ -- after it has successfully connected -- either when the disconnection is expected or when it is unexpected. (See the "On expected disconnect" and "On unexpected disconnect" buttons on the Settings tab.) That's something completely different, though.

**Comment by glglgl123** [comment]
a few seconds is important because some programs during the connection can leak a real IP

example: 

tunnelblick connects to the server I need when I turn on my computer
at the same time, the program starts where the IP leak is undesirable and due to the fact that VPN connects for these 3-10 seconds, the IP leak occurs

now do you understand what I mean?

if I'm not mistaken this problem can be solved with the help of a firewall at least on Windows I solved this problem so blocked all outgoing traffic and allowed access only for VPN I recently (couple of days) switched to macOS and then it's different and I thought could be implemented in tunnelblick

forgive me, my English very bad, hope, you I'll understand

Best regards

**Comment by jkbullard** [comment]
OK, I understand now. (Your English is fine.)

This can be done on macOS, too, using a firewall. I think the "pf" firewall is what most people use on macOS.

Setting up a firewall for one specific use (your specific VPN setup, for example) is not too difficult.

But having Tunnelblick set up a firewall so that it that works with all of the different ways that Tunnelblick is used is complicated. That is not something that is built into Tunnelblick.

**Comment by glglgl123** [comment]
ok thanks

**Comment by shamilovtim** [comment]
@jkbullard If I could contribute this as a PR in Swift at some point would it be a possibility?

**Comment by shamilovtim** [comment]
@glglgl123 look into Little Snitch. it's $50 but it does what you want, and if this level of privacy is important to you then it's probably your only option on macOS. 

https://www.obdev.at/products/littlesnitch/index.html

**Comment by jkbullard** [comment]
@shamilovtim - Thanks for asking. What would your PR do?

**Comment by shamilovtim** [comment]
if I have the time and am capable of doing it I would like to eventually add a feature that provides full privacy until the user is connected to the VPN. So until the VPN connection is made, no packets should pass between the machine and the rest of the internet. If the user has this feature on, he cannot access the internet (and conversely is invisible to the internet) until he connects to the VPN.

**Comment by shamilovtim** [comment]
As far as use case I would imagine this is a use case: imagine User John Doe has Dropbox installed on his machine, and Dropbox has a backdoor for some sort of government spy apparatus. John Doe connects to Wifi, and wants to connect to his VPN. But after he connects to Wifi and between connecting to VPN, Dropbox has synced to its cloud server and has exposed John Doe. I'm sure there are dozens of others but the point is exposing the user in between offline and VPN connection isn't a total level of privacy

**Comment by shamilovtim** [comment]
> @shamilovtim - Thanks for asking. What would your PR do?

I just went ahead and set this functionality up in PF. seems super simple if you can interface with applescript to build some simple PF functionality into the client and connect it to the VPN connections.
