### ISSUE TITLE
Vain alert in regards of resolver on 127/8 (loopback)

### ISSUE THREAD

**Issue by poige** [Tunnelblick/Tunnelblick#542]
![image](https://user-images.githubusercontent.com/600779/58687173-1c5cc980-83ab-11e9-82aa-b946574f93b9.png)

P. S. Black color text glyphs aren't specially readable with Mojave's dark theme.

**Comment by jkbullard** [comment]
I am not planning to do anything about this.

I think the warning is reasonable. localhost may use a recursive resolver, which could route outside of the VPN, so it is good to know that this is happening. And the checkbox makes it easy to prevent the warning from appearing again.

P.S. The black text on a dark background was fixed in 4227216bb1f736daca5887262244b2ed37e8981f (Fix #543 "Unreadable alert text on Dark Mode").

**Comment by poige** [comment]
> And the checkbox makes it easy to prevent the warning from appearing again.

Would checkbox effectively prevent that warning for all other private address space IPs?

**Comment by poige** [comment]
> I think the warning is reasonable.

Warning's text says "127.0.0.1 is private space but it's not routed through VPN".
But 127.0.0.0/8 is loopback, actually, and thus it's expected _to be not routed anywhere at all_.
That's why it's unreasonable, actually.

> localhost may use a recursive resolver, which could route outside of the VPN, so it is good to know that this is happening.

Of course it could (or _couldn't_) but this doesn't make the warning text I've already cited any valid and reasonable.

**Comment by jkbullard** [comment]
> Warning's text says "127.0.0.1 is private space but it's not routed through VPN".
But 127.0.0.0/8 is loopback, actually, and thus it's expected to be not routed anywhere at all.
That's why it's unreasonable, actually.

I agree that the warning's language is not accurate, so I will change it to read "is not a public IP address and is not being routed through the VPN" instead of "is a private address but is not being routed through the VPN". I'm using the language "public IP address" per Wikipedia's description of it as "a globally routable unicast IP address" [1].  (That includes IPv6 "unique local addresses", too.)

With that change, the warning will stay:
 1. It is true: the address is NOT a public address and is NOT routed through the VPN [2]; and
 1. The message describes this as a _possible problem_. It isn't saying it _is_ a problem, it is saying that it _might be_ a problem. And that's true, too.

If anyone is bothered by this warning, they can just check the box and never see it again.

[1] https://en.wikipedia.org/wiki/IP_address#Public_address
[2] If it is being routed through the VPN, this warning will not appear.
