### ISSUE TITLE
Use two lines for current network connection

### ISSUE THREAD

**Issue by m5o** [Tunnelblick/Tunnelblick#547]
The context menu of `Tunnelblick` is displaying the current Network in a long single line, which expands the context menu very large. What do you think to shrink this by using two lines?

###### Status Quo: Single Line

* `Disconnect All (<CONFIG NAME>) - apparent public IP address (<IP ADDRESS>)`

<img width="573" alt="Screenshot_2019-06-03_at_16_50_52" src="https://user-images.githubusercontent.com/26371/58811659-83cf7f00-8620-11e9-86a5-0b6c8599ce9e.png">

###### Proposal: Two lines E.G.

```
Disconnect All (<CONFIG NAME>) \n
apparent public IP address (<IP ADDRESS>)
```

**Comment by jkbullard** [comment]
(It would be implemented as a second menu item since as far as I know macOS doesn't have multi-line menu items, i.e., we can't just add a "\n" to the string.)

Or what about removing "apparent public IP address" and just showing the address, e.g.

Such as **Disconnect All (USA-Miami) 192.68.222.111**

?

Advantage: trivial to do (just delete some text!).
Disadvantage: some users won't know what it is.

**Comment by m5o** [comment]
💡 `Disconnect All (USA-Miami) IP: 192.68.222.111`

**Comment by PSNAppz** [comment]
Is this still open for contribution?

**Comment by jkbullard** [comment]
@PSNAppz - Yes. A PR would be appreciated.
