### ISSUE TITLE
No edit option for file configuration in the dropdown

### ISSUE THREAD

**Issue by ZanMarolt** [Tunnelblick/Tunnelblick#555]
**Describe the bug**
No ability to edit configuration file.

**To Reproduce**
1. Open tunnelblick
2. Select any of your configurations
3. See that no edit configuration option is available

**Expected behavior**
Edit configuration should be available

**Screenshots**
![2019-06-24_14-47-32](https://user-images.githubusercontent.com/7118268/60019918-367a8680-968f-11e9-8470-0f76458c7cd9.png)

**Comment by jkbullard** [comment]
As the "?" button (round button with a "?") says:
> Only "private" configurations may be edited; shared and Deployed configurations may be examined.

**Comment by ZanMarolt** [comment]
@jkbullard thanks for the quick reply. Could you share with me the difference between private/shared configurations?

**Comment by jkbullard** [comment]
@ZanMarolt - Sure : )

A **private** configuration is one that only the user who installed it can use. A **shared** configuration can be used by any user of the computer. (macOS comes with one user but you can add other users as you wish; most people don't set up any additional users.)

When you install a configuration, you are asked if you want it to be installed "so that all users can use it, or so only you can use it". Your answer determines whether it is shared or private.

You can switch a configuration from shared to private or private to shared by selecting the configuration in the list on the left side of the "Configurations" panel of Tunnelblick's "VPN Details" window, clicking the little "gear" icon at the bottom of the list, and clicking "Make Configuration Private…" or "Make Configuration Shared…".

**Comment by ZanMarolt** [comment]
@jkbullard Just what I needed, thank you so much! Also thank you for the insightful explanation, appreciated.
