### ISSUE TITLE
Tunnelblick 3.8.1 build 5400 inappropriate warning message

### ISSUE THREAD

**Issue by jelockwood** [Tunnelblick/Tunnelblick#576]
**Describe the bug**
After updating to Tunnelblick 3.8.1 build 5400 on a Mac running Mojave and launching the new version it immediately displayed a message saying (along the lines of) 'This version is x days old and out of date, you should check for a new release.'

Since 3.8.1 was only released 4 days ago this is clearly absurd. It would seem the checking is making an incorrect calculation of how old it is.

**To Reproduce**
1. Install 3.8.1
2. Launch 3.8.1
3. Tunnelblick displays inappropriate warning. (This has happened on multiple machines, all are running Mojave not that that I believe that to be the cause.)

**Expected behavior**
In view of the extremely recent release of version 3.8.1 I expect it to launch with no warning. If 3.8.1 had been issued months ago then the warning would be appropriate.

**Screenshots**

**Additional context**

**Diagnostic information**
Please paste or attach the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) here.

**Comment by jkbullard** [comment]
@jelockwood - Thanks for reporting this. I haven't seen it before. It doesn't seem to be a widespread problem, and I didn't see any problems after eyeballing the code in warnIfOutOfDateBuild which starts at line 4857:  https://github.com/Tunnelblick/Tunnelblick/blob/b6dc395734e6264dc5a68d6f630a2e44663c1c16/tunnelblick/MenuController.m#L4857

How do your computers set their data and time? (For example, System Preferences > Date & Time > Date & Time might show a check in "Set date and time automatically:" and an Apple timeserver or your own timeservers, or the systems may have their dates/times set manually.)

On one of the affected systems, what is the output from the following command?

    date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s" ; date "+%Y-%m-%d %H:%M:%S"

On my computer, it just showed the following:

    1568633339
    2019-09-16 07:28:59

(The first line is the number of seconds since the Unix "epoch", 1970-01-01 00:00:00 UTC. The second line is the date and time in the "local" time zone in YYYY-MM-DD HH:MM:SS format. Tunnelblick uses the UTC value, so it is independent of the time zone; the second line is shown just to make it easy to see that the systems have the correct date. )

**Comment by jkbullard** [comment]
@jelockwood - Thanks for reporting this. I haven't seen it before. It doesn't seem to be a widespread problem, and I didn't see any problems after eyeballing the code in warnIfOutOfDateBuild which starts at line 4857:  https://github.com/Tunnelblick/Tunnelblick/blob/b6dc395734e6264dc5a68d6f630a2e44663c1c16/tunnelblick/MenuController.m#L4857

How do your computers set their data and time? (For example, System Preferences > Date & Time > Date & Time might show a check in "Set date and time automatically:" and an Apple timeserver or your own timeservers, or the systems may have their dates/times set manually.)

On one of the affected systems, what is the output from the following command?

    date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s" ; date "+%Y-%m-%d %H:%M:%S"

On my computer, it just showed the following:

    1568633339
    2019-09-16 07:28:59

(The first line is the number of seconds since the Unix "epoch", 1970-01-01 00:00:00 UTC. The second line is the date and time in the "local" time zone in YYYY-MM-DD HH:MM:SS format. Tunnelblick uses the UTC value, so it is independent of the time zone; the second line is shown just to make it easy to see that the systems have the correct date. )

**Comment by jelockwood** [comment]
@jkbullard 
The Macs are all set to use time.euro.apple.com as the network time server and to set date and time automatically. They are all configured to UK region and London timezone aka GMT/BST time zone.

Your date command as listed causes an error in the first half when I try it. 

```
date -j -f "%a %b %d %T %Z %Y" "`date`" "+%s" 
Failed conversion of ``Mon 16 Sep 2019 13:21:55 BST'' using format ``%a %b %d %T %Z %Y''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

The second half works and gives -

```
date "+%Y-%m-%d %H:%M:%S"
2019-09-16 13:19:25
```

Using just the following as a replacement first half works

```
date "+%s"
1568636780
```

**Comment by jkbullard** [comment]
@jelockwood - Thanks.

I think I see the problem. Does it go away if you execute the following?

    defaults delete net.tunnelblick.tunnelblick buildExpirationTimestamp

**Comment by jelockwood** [comment]
@jkbullard 
On my own Mac I also clicked the 30 day ignore button. How do I reset that so as to trigger the date problem again?

**Comment by jkbullard** [comment]
Use the same command:

    defaults delete net.tunnelblick.tunnelblick buildExpirationTimestamp

But I think that will make the problem go away, if the problem is what I think it is.

**Comment by jelockwood** [comment]
@jkbullard 
Ok I executed that command and relaunched Tunnelblick 3.8.1 and no message appeared. As long as my previously clicking the 30 day skip button has been reset as well then the problem has been cleared.

**Comment by jkbullard** [comment]
@jelockwood - Thanks again for reporting this problem, and for confirming my suspicion about the cause. As I wrote earlier, I expect to have a fix in the next beta. In the meantime, anyone with this problem can make it go away by executing the following in Terminal:

    defaults delete net.tunnelblick.tunnelblick buildExpirationTimestamp

**Comment by jkbullard** [comment]
This was "fixed" by removing the functionality. Tunnelblick will no longer warn about out-of-date versions.
