### ISSUE TITLE
Sidecar stop working when tunnelblick vpn connected

### ISSUE THREAD

**Issue by towingie** [Tunnelblick/Tunnelblick#580]
**Describe the bug**
New os x catalina feature Sidecar (screen sharing to iOS devices) stoped working while Tunnelblick openvpn is connected.

**To Reproduce**
- share screen to ios (ipad for example) with sidecar feature
- connect to vpn

**Comment by jkbullard** [comment]
@towingie - Does this happen if you connect the VPN first?

Perhaps it is a configuration issue – for example, maybe Sidecar requires IPv6 and you have disabled it. Otherwise, it seems to me that it is a problem with Sidecar, not Tunnelblick.

**Comment by towingie** [comment]
seems fixed after os x upadte.

**Comment by michbsd** [comment]
I am having this issue too .. 
Last Tunnelblick and latest MacOS Catalina - any idea on how to fix this ?

**Comment by christopherg** [comment]
I'm also having this issue with build 5400 and beta 5320 on MacOS Catalina 10.15.1 running the latest updates available as of today (Sun 11/3/2019).

This happens when I attempt to start sidecar with the VPN connected or disconnected. I have also tried with tunnelblick application not open and opening after connecting sidecar. I end up getting a "Connecting Switching to wireless" error and it cannot reconnect while the VPN is connected.

**Comment by jkbullard** [comment]
@christopherg - Thanks. I have updated [Tunnelblick and macOS Catalina](https://tunnelblick.net/cCatalina.html) to include a description of this problem and the dangers of enabling IPv6 when connected to a VPN.

**Comment by marc-h38** [comment]
>  the dangers of enabling IPv6 when connected to a VPN.

I'm taking the risk of failing to summarize these risks:

Most operating systems and applications now support both IPv4 and IPv6 at the same time and they tend to prefer IPv6. However most VPN services support only IPv4. Most users have no idea what "dual-stack" means: they just turn on their IPv4 VPN expecting better "privacy". They don't realize that using their IPv4-only VPN service makes zero privacy difference to all their applications that prefer IPv6.
