### ISSUE TITLE
Unnecessary password prompts (elevated rights)

### ISSUE THREAD

**Issue by ekreutz** [Tunnelblick/Tunnelblick#582]
**Describe the bug**
Tunnelblick asks for the master password even when it doesn't have to. It's quite shady when an app wants the user to insert their account password into a custom prompt. Especially for a security-related app, what's up?

___

**Example 1:** Installing

This doesn't require admin rights, you can just move the app to /Applications. Drag-drop like any macOS app works just fine. Why ask for the password?

<img width="555" alt="Screenshot 2019-11-04 at 10 52 12" src="https://user-images.githubusercontent.com/9801173/68108848-aaf0ec00-fef1-11e9-8fdc-af123e59dc9c.png">

___

**Example 2:** Opening Tunnelblick for the first time

<img width="555" alt="Screenshot 2019-11-04 at 10 52 52" src="https://user-images.githubusercontent.com/9801173/68108819-9d3b6680-fef1-11e9-9f72-a24f7724c853.png">

What permissions do you want? Can I just give those permissions without the shady password prompt?

___

**To Reproduce**
1. Install Tunnelblick
2. Custom/shady password prompts shown

**Expected behavior**
1. Remove unnecessary password prompts, like the installation one.
2. Be transparent when elevated rights are needed. At a minimum, show a system password prompt and explain why elevated rights are needed. Don't show the custom one! It would be great if the _user was allowed to give the permissions themselves_, and not have Tunnelblick do it automatically.

**Diagnostic information**
Tunnelblick 3.8.1
macOS Catalina 10.15

**Comment by jkbullard** [comment]
@ekreutz wrote:
> Tunnelblick asks for the master password even when it doesn't have to.

It doesn't; see below for details.

@ekreutz wrote:
> It's quite shady when an app wants the user to insert their account password into a custom prompt.

**Tunnelblick does not ask for the password (it is not a "custom prompt")**

It is actually a macOS prompt window that asks for the password, not a Tunnelblick "custom prompt" window. Tunnelblick uses a call to macOS that asks macOS to (a) present a window with a Tunnelblick-specified icon and text (the bold text shown in your example) and (b) return a system administrator's "authorization" to Tunnelblick. (The "authorization" is a temporary, opaque code.) The "authorization" is then used by Tunnelblick when asking macOS to perform operations that require root access. The password is not seen by Tunnelblick – macOS returns only the "authorization" to Tunnelblick, not the password.

@ekreutz wrote:
> 1. Remove unnecessary password prompts, like the installation one.

As explained in more detail below, the password prompts are necessary.

@ekreutz wrote:
> 2. Be transparent when elevated rights are needed. At a minimum, show a system password prompt and explain why elevated rights are needed. Don't show the custom one!

As explained in more detail below, Tunnelblick *does* show a system prompt, not a custom one, and it attempts to be "transparent" by explaining why it needs a system administrator's authorization.

It isn't practical to include all of the explanation that's detailed below in an authorization request, so it is condensed into "must be installed in /Applications", "must be secured", and other, similarly brief phrases.

@ekreutz wrote:
> It would be great if the user was allowed to give the permissions themselves, and not have Tunnelblick do it automatically.

A system administrator could "give permissions themselves" by setting Tunnelblick's ownership and permissions so it is secure, and by installing the "daemon" that Tunnelblick uses to perform privileged operations during normal operation. If that is done, Tunnelblick will not ask for authorization. However, it is a complicated process, so Tunnelblick does it for you automatically and includes a command-line tool ("installer") which can be used by app distribution and control systems such as Munki to install and secure Tunnelblick and/or VPN configurations so the user is not prompted for authorization.

<hr>

**Tunnelblick needs elevated rights to create VPN connections and prevent "escalation of privileges" attacks**

Tunnelblick requires elevated rights (root access) to start OpenVPN as root, which is required so that OpenVPN can perform some of the operations needed to set up a VPN, e.g., perform changes to the system's routing tables.

Because OpenVPN runs as root and has the ability to run scripts specified in the VPN configuration as root, the entire OpenVPN-Tunnelblick program set, and all VPN configurations, must be protected from being modified without a system administrator's authorization. Otherwise, a regular (non-admin) user could change a configuration file and cause OpenVPN to run a user-provided script as root. That is what is known as an "elevation of privilege" attack and must be avoided to prevent a regular user from making changes that only a system administrator should make.

**How Tunnelblick protects against "elevation of privilege" attacks**

To protect the program and configurations from being modified without a system administrator's authorization, Tunnelblick makes both the Tunnelblick program (which includes OpenVPN) and the VPN configurations be owned  by root and modifiable only by root and requires that the Tunnelblick application be located in the system's "Applications" folder.

(There are additional safeguards built into recent versions of macOS, for example System Integrity Protection and the read-only system volume in macOS Catalina, but earlier versions of macOS do not have these safeguards, and the safeguards do not prevent a malicious program running as root from performing other operations that could compromise a system. So Tunnelblick has kept its protection mechanism in place even as these new macOS safeguards have made some of the protections less necessary because (a) it is simpler to _always_ provide the protections, (b) it provides "defense in depth" in case one of the macOS mechanisms fails, and (c) the macOS safeguards do not provide complete protection.)

As additional protection, each time Tunnelblick is launched, it checks that it is located in /Applications, that everything that needs to be owned and only modifiable by root is in fact owned and only modifiable by root, that its privileged daemon is installed, and that the Tunnelblick application (including OpenVPN) has not been modified. If any of these conditions are not met, Tunnelblick gets authorization to fix them or by notifies the user of the problem.

**How Tunnelblick's protects itself no matter how it is installed**

 * If you install Tunnelblick normally (by double-clicking the Tunnelblick application on the disk image or anywhere outside of the "Applications" folder), Tunnelblick will get authorization and will copy itself to /Applications, secure itself (by changing it's ownership to root and modifiable only by root), and set up a similarly-secured privileged daemon to perform operations which require elevated privileges.

 * If you copy the Tunnelblick application to /Applications yourself, macOS may or may not ask for authorization, depending on whether you are logged in as a system administrator. But the first time you launch Tunnelblick after such a copy, Tunnelblick will notice that it is not secured (not owned by root, etc.) and will ask for authorization to secure itself.

 * When you install a configuration, or attempt to connect a configuration that has been modified after it was initially installed or last used, Tunnelblick will ask for authorization to secure the configuration.

<hr>

Because Tunnelblick is free software, anyone can examine the source code to confirm any or all of the above.
