### ISSUE TITLE
write UDP: Can't assign requested address (code=49)

### ISSUE THREAD

**Issue by normads** [Tunnelblick/Tunnelblick#610]
**Describe the bug**
If you change the connected network, tunnelblick won't connect through the new network without a reboot or a `sudo route flush`

**To Reproduce**
Connect to openvpn server through a wifi network
Change connected wifi network
Tunnelblick won't connect (write UDP: Can't assign requested address (code=49))

**Expected behavior**
Tunnelblick should reconnect via the new network

**Screenshots**
<img width="659" alt="Screenshot 2020-03-23 at 11 28 42" src="https://user-images.githubusercontent.com/3591654/77286843-2c5ae680-6cfa-11ea-9734-6dff41106f32.png">

**Additional context**
This is a known issue with mac but apparently only happens to some configurations. 
https://support.bolehvpn.net/hc/en-us/articles/115002185643-Mac-OS-Connection-Issues-write-UDP-Can-t-assign-requested-address-code-49-
So i was wondering if i could,
1) change the configuration to side step this issue
2) create a post disconnect script to automatically flush routes

**Comment by benjefferies** [comment]
I'm also seeing this issue after updating this morning to `Tunnelblick 3.8.2`

**Comment by jkbullard** [comment]
@normads:

 1. Changing your OpenVPN configuration or Tunnelblick settings can usually solve this problem, which can have many causes. Without the diagnostic info I can't be more specific. Often the problem is caused by including "user nobody" and "group nogroup" in the OpenVPN configuration file. On macOS they cause routing to not be restored when the VPN is disconnected.

 2. Tunnelblick lets you run post-disconnect scripts. See [Using Scripts](https://tunnelblick.net/cUsingScripts.html) for details.

@benjeffries: As described above, this is usually a configuration issue. If you want help, post the diagnostic info as per https://tunnelblick.net/cBeforeYouPost.html.

**Comment by normads** [comment]
Thanks @jkbullard. I'll try removing the user and group configurations first.

**Comment by xiaocaoh** [comment]
> Thanks @jkbullard. Commenting out "user nobody" and "group nogroup" works!

can you tell me how dou you Commenting out "user nobody" and "group nogroup"？thanks！

**Comment by jkbullard** [comment]
To "comment out" something in an OpenVPN configuration file, put a "#" character or a ";" character at the start of the line. For example, if the configuration file contains

```
remote blah blah blah
user nobody
group no group
```
You can "comment out the "user nobody" and "group nogroup" to make it contain

```
remote blah blah blah
#user nobody
;group no group
```

**Comment by xiaocaoh** [comment]
> To "comment out" something in an OpenVPN configuration file, put a "#" character or a ";" character at the start of the line. For example, if the configuration file contains
> 
> ```
> remote blah blah blah
> user nobody
> group no group
> ```
> 
> You can "comment out the "user nobody" and "group nogroup" to make it contain
> 
> ```
> remote blah blah blah
> #user nobody
> ;group no group
> ```

ok thanks！
