### ISSUE TITLE
Option to disable admin authentication all-together or allow Touch ID everywhere

### ISSUE THREAD

**Issue by WoodpeckerBaby** [Tunnelblick/Tunnelblick#612]
**Describe the bug**
Reference #585
So far, I cannot find any indication of where the option is to enable Touch ID authentication. I have traversed every menu in the app, in the documentation, and on GitHub. It is mentioned in the release notes, but that's about it. Where that option is is a mystery to me...

I am currently on macOS 10.15.3 (19D76), Tunnelblick 3.8.2 (build 5480). 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'anywhere that requires authentication like "enter admin mode"'
2. See the username and password window as the only authentication option. 

**Expected behaviour**
When `1.` is invoked, the equivalent of the following window should come up before falling back to `2.`
<img width="1053" alt="Screen Shot 2020-03-24 at 9 01 24 PM" src="https://user-images.githubusercontent.com/14303318/77428390-f65d5580-6e12-11ea-8506-905abadbb47a.png">

**Additional context**
If that's too much work, then please add an option to "enter admin mode" forever... not just 5 min. It's my mac and no one is touching it but myself.

If in a multi-user environment, add an option to install for the current user only or enable admin mode based on macOS login user, but you should probably not bother with this and just add a warning of this implication when someone enables "admin forever". 

**Diagnostic information**
N/A for not-a-bug

Thank you all for the great work!

**Comment by jkbullard** [comment]
@WoodpeckerBaby - Thanks for your report and suggestions.

First, I want to make sure that everyone understands that a computer admin's authorization is only needed to perform security-sensitive operations (mostly, operations that could end up with arbitrary scripts running as root). Most Tunnelblick settings can be changed without such authorization. Some people think they have to enter Admin mode to make _any_ changes, which is incorrect.

Also, the ability to install or modify "safe" configurations without a computer admin's authorization can reduce the number of situations in which a computer admin's authorization is needed. (See [Standard Users Installing or Replacing Configurations](https://tunnelblick.net/cNonAdminInstalls.html).)

<hr>

OK, on to @WoodpeckerBaby's comments/proposals:

The recent change to allow "Touch ID" was for one very specific purpose: to allow Touch ID to be used when authentication is required by the (new) checkbox "Authenticate before connecting", which is on the "Advanced" settings panel.

We do not currently accept the use of Touch ID for authorizations to do "protected" operations (such as entering Admin mode).

I don't understand why Touch ID isn't used automatically by macOS. We don't actually ask for the username/password itself, we ask macOS to get a computer admin's authorization and return us a token which we then use when asking macOS to perform protected operations. So macOS should (in my opinion) use whatever method is appropriate to get the authorization: Touch ID, Face ID, or username/password. I will add looking into this to my (long) to-do list – perhaps we just need to add a parameter to our existing request to macOS or something like that. (But knowing Apple, it will be much more complicated : )

<hr>

I don't want to make it too easy to be in Admin mode forever. It would open up a gaping hole in the computer -- anyone who had physical access for a few minutes could do anything they wanted, which seems like a really bad idea for most people.

But I recognize that it would be nice in some situations, so I will consider adding an "Admin only" preference named "AdminModeTimeoutInMinutes" to let you change the 5 to an arbitrary number. The change would affect all users of the computer. You could set it to 0 minutes to disallow Admin mode, or to a number like 52,560,000 (the number of minutes in 100 years). I wouldn't add that preference to the GUI, though: you'd have to set it manually by editing the protected XML file at /Library/Application Support/Tunnelblick/forced-preferences.plist. I'd also have Tunnelblick always create that file if it doesn't exist when installing or securing Tunnelblick, so you wouldn't have to create the file yourself.

**Comment by WoodpeckerBaby** [comment]
@jkbullard 

The cases where I'm repeatedly hit with admin authentication is when I click `duplicate configuration`, and `edit OpenVPN configuration file`. Then, I get hit with another admin authentication when I `connect` this configuration file for the first time. Usually, I do this to add a different `port` option to the same server, or to config the standby servers that are only off by 1 digit. 

I am not sure how configuration sharing is implemented. By wild guesses, since I didn't `make configuration shared`, I think it wouldn't be of security concerns. Though, I think anyone who has my macOS unlocked and logged into my account would mean game-over for me anyway... The attack surface is just too wide. Across user accounts? I'm not sure, because that depends on the implementation. I also noticed that a `shared configuration` cannot be edited.

**Comment by jkbullard** [comment]
@WoodpeckerBaby wrote:
> I am not sure how configuration sharing is implemented. By wild guesses, since I didn't make configuration shared, I think it wouldn't be of security concerns.

The security concern is because _any_ OpenVPN configuration (even private configurations) can run arbitrary commands and scripts as root when the configuration is used by Tunnelblick. That's because:
 1. OpenVPN configurations can tell OpenVPN to run scripts. (Technically, OpenVPN runs a command, but a command can, and typically does, run a script.)

 1. The scripts run as the same user that OpenVPN itself is running as.

 1. Tunnelblick starts OpenVPN running as root so that macOS will allow it make the routing changes that are needed to set up the VPN.

If you can modify the configuration file, you can run programs as root. And if you can do it, so can malware that runs as you. Preventing the possibility of such [privilege escalation](https://en.wikipedia.org/wiki/Privilege_escalation) is an important goal of Tunnelblick, and should be an important goal for any software that itself uses escalated privilges.

<hr>

I've thought Admin mode more, and am going go get rid of the timeout altogether. Admin mode will be in effect until either the unlock button is clicked or the "VPN Details" window is closed (including when it is closed when Tunnelblick quits).

I think that's a reasonable balance between security and ease-of-use: as long as Admin mode is active, the unlocked lock icon will clearly show that. I considered stopping Admin mode if the window were minimized or if the lock icon were shifted to be out of the display area, but I think that's overkill.

I realize it isn't ideal for @WoodpeckerBaby, who would like to use Touch ID, or, as an alternative, only authorize once. But it will help, and I'll see if I can find a quick way to use Touch ID now. But if I can't, it will go back on my (long) to-do list.

**Comment by WoodpeckerBaby** [comment]
@jkbullard
Thank you, that would be a good balance. 

I am not 100% certain what changes need to be put in place for it to use touchID. However, I know that you can very easily tell the MacOS Terminal app to accept TouchID or `tid` as a `sufficient` level of authentication by just adding a line in the config file. 

``sudo vim /etc/pam.d/sudo``
Then add this line too the (typically 4) other options
``auth sufficient pam_tid.so ``

**Comment by jkbullard** [comment]
@WoodpeckerBaby: Yes, Apple-suppled programs like sudo can use Touch ID for authorization. But [it's possible that non-Apple programs are not allowed to do it] (https://forums.developer.apple.com/message/323327#323327) (!).

I've filed a Technical Support Incident with Apple to see if they will confirm this restriction or help me get this implemented.

**Comment by jkbullard** [comment]
I've removed the code that disabled Admin mode after 5 minutes.

I will leave this Issue open until I've heard from Apple and either given up on using Touch ID or implemented it.

**Comment by jkbullard** [comment]
- Apple tech support has confirmed that only apps signed by Apple can use Touch ID in a way that lets the app save and later reuse the authorization, which is what Tunnelblick's Admin mode does. I plan to file an enhancement request with Apple to have macOS allow apps not signed by Apple to do that, but I don't expect a positive response.<br><br>Although it is possible for Tunnelblick to use Touch ID to authorize individual operations when not in Admin mode, that causes the dialog box to say that "osascript wants to make changes" instead of "Tunnelblick wants to make changes", and I think that would be too confusing for users, so I'm not planning on implementing it.

- As I wrote earlier, 02878853865237cae0cdc725d030740737db0148 made changes so Tunnelblick no longer exits from Admin mode after five minutes and is only exited when the "VPN Details" window is closed or the user clicks the "Exit Admin mode" button. This will be included in the next beta release of Tunnelblick.<br><br>I am open to adding back a way for users to specify a timeout for Admin mode, but that depends on user feedback, and even if it is added, Admin mode will also be exited when the "VPN Details" window closes or the user clicks the "Exit Admin mode" button. Anyone who wants this added back should comment on 02878853865237cae0cdc725d030740737db0148.

For these reasons, I am closing this issue.

**Comment by WoodpeckerBaby** [comment]
@jkbullard

I'm a bit confused after upgrading to Tunnelblick 3.8.3beta01 (build 5490). 

Reference commit 02878853865237cae0cdc725d030740737db0148

The timer doesn't seem to go away. 

<img width="1019" alt="Screen Shot 2020-04-03 at 12 56 28 AM" src="https://user-images.githubusercontent.com/14303318/78277619-63759700-7547-11ea-9afb-966b9855c392.png">

And it does indeed lock after the countdown

<img width="989" alt="Screen Shot 2020-04-03 at 1 00 05 AM" src="https://user-images.githubusercontent.com/14303318/78278374-88b6d500-7548-11ea-84a4-51a044b0cedf.png">

**Comment by jkbullard** [comment]
02878853865237cae0cdc725d030740737db0148 is not included in 3.8.3beta01 because it was committed and merged after 3.8.3beta01 was released. It will be included in the next beta.

**Comment by jkbullard** [comment]
@WoodpeckerBaby - Previously I wrote that
> …0287885 made changes so Tunnelblick no longer exits from Admin mode after five minutes and is only exited when the "VPN Details" window is closed or the user clicks the "Exit Admin mode" button. This will be included in the next beta release of Tunnelblick.

I apologize. Testing has revealed that 0287885, which removed Tunnelblick's five minute time limit on Admin mode, does not work. Although the commit removes Tunnelblick's timer and removes Tunnelblick's deauthorization, macOS itself forces a deauthorization after 5 minutes. There does not seem to be any way to prevent that, so I will be reverting that commit and restoring Tunnelblick's five-minute timer, which at least shows you how much time is left.

So I'm afraid that neither of your requests is allowed by Apple. Tunnelblick can neither allow the use of Touch ID for authorization nor extend the time limit for Admin mode.

I'm going to leave this issue closed, however, because I don't think there's much chance that Apple will remove the restrictions that would need to be loosened to implement your requests.
