### ISSUE TITLE
Make use of System Root Certificates while verifying SSL certificates.

### ISSUE THREAD

**Issue by kishorv06** [Tunnelblick/Tunnelblick#625]
**Describe the bug**
Tunnelblick no longer trusts certificates with AddTrust External CA Root as the root certificate as the root certificate expired on May 30, 2020.

**To Reproduce**
Steps to reproduce the behaviour:
1. Configure OpenVPN to use any certificate having AddTrust External CA Root as the root authority
2. Try connecting with Tunnelblick
3. Tunnelblick will hang with "Waiting for server response" message
4. Check log to see "Certificate has expired" error message

**Expected behaviour**
Tunnelblick verifies the certificate by using USERTRUST RSA Certification Authority Certificate, which is already present in the System Root Certificates.

**Additional context**
https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020

**Diagnostic information**

> 2020-05-31 21:46:54.116584 VERIFY ERROR: depth=3, error=certificate has expired: C=SE, O=AddTrust AB, OU=AddTrust External TTP Network, CN=AddTrust External CA Root
> 2020-05-31 21:46:54.116780 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
> 2020-05-31 21:46:54.116802 TLS_ERROR: BIO read tls_read_plaintext error
> 2020-05-31 21:46:54.116816 TLS Error: TLS object -> incoming plaintext read error
> 2020-05-31 21:46:54.116829 TLS Error: TLS handshake failed

**Comment by jkbullard** [comment]
OpenVPN VPNs use their own PKI, not the PKI used by the Internet (e.g., https:), so Tunnelblick, OpenVPN, and OpenSSL (which is what actually does the certificate validation) do not and should not use "System Root Certificates".

If you have set up your VPN expecting the ability to "fall back" on the https: PKI, that's an error on your part. You didn't do [the first step in building an OpenVPN… configuration](https://openvpn.net/community-resources/setting-up-your-own-certificate-authority-ca/).

**Comment by kishorv06** [comment]
Yes, I haven't followed the PKI infrastructure guide to create the certificate. Instead I have purchased a certificate for the domain on which OpenVPN is running and added the CA bundle in the ``.ovpn`` file. I don't need client certificates as I have configured plugin based authentication.

Now my question is, If OpenVPN Clients are supposed to work only with their own PKI, why does OpenVPN Connect ( Official version ) works fine, but TunnelBlick doesn't ?

**Comment by jkbullard** [comment]
@kishorv06 wrote:
> Now my question is, If OpenVPN Clients are supposed to work only with their own PKI, why does OpenVPN Connect ( Official version ) works fine, but TunnelBlick doesn't ?

It isn't that OpenVPN won't work with the https: PKI, it's that the best practice is to use your own PKI. If you use the https: PKI, you are trusting each of the more-than-a-hundred Certificate Authorities, each of which has the ability to intercept VPN traffic and/or impersonate your OpenVPN server or clients. Many VPN users do not want _anyone_ to have that ability, and in fact may be using a VPN specifically to avoid such actions.

As to why OpenVPN Connect works, I'd guess that it uses the version of OpenSSL/LibreSSL provided by macOS, which (since Mavericks) uses the system's root certificate store, which is updated with macOS and does not include expired certificates. Tunnelblick includes multiple versions of "standard" OpenSSL/LibreSSL. "Standard" OpenSSL/LibreSSL does not use the system certificate store, it uses a fixed set of certificates augmented by certificates stored in a folder. (Until now I've never looked at what folder is used by Tunnelblick's OpenSSLs/LibreSSLs, but they may use a fixed path on the system on which we build binaries, which would be a bug.)

**An unlikely but easy-to-fix possibility** is that you are using an old version of OpenSLL and that your VPN will work if you use a different version. You can specify which OpenSSL/LibreSSL version to use in the "OpenVPN version" entry of Tunnelblick's "Settings" tab. Remember to select the configuration(s) you want to change before making the change.

**Another unlikely but easy-to-fix possibility** is that /private/etc/ssl includes the expired certificate and it is being used by Tunnelblick's binaries. Rename "cert.pem" in that folder and see what happens. If it doesn't work, restore the filename.

Assuming your VPN worked with Tunnelblick before the certificate expired, the best way to avoid this problem (and similar problems from "curl" and other programs) is to get and use new certificates which do not include the expired intermediate certificate.

**Comment by kishorv06** [comment]
@jkbullard Thank you for the detailed explanation. I have managed to get Tunnelblick working by using another chain of CA certificates which doesn't leads to the expired AddTrust External CA Root.

Just posting this here, so that it might help someone else. https://www.agwa.name/blog/post/fixing_the_addtrust_root_expiration
