### ISSUE TITLE
Do not try to reconnect after return from sleep

### ISSUE THREAD

**Issue by tomilov** [Tunnelblick/Tunnelblick#626]
After wake up Tunnelblick tried to reconnect to a server using old credentials. The server uses TOTP as a part of password and after a while, when connection is lost, it requires new password. The number of attempts is limited to a small number. One decrement of number of attempts made by Tunnelblick unconditionally, which is very very bad.

**Expected behavior**
Do not try to reconnect using old credentials after waking up.

**Comment by jkbullard** [comment]
The behavior you describe shows a problem with your OpenVPN configuration. If your VPN disconnects for any reason other than a click on "Disconnect", the same thing would happen. (OpenVPN can disconnect and reconnect for many reasons, including a bad connection to the server or timeouts of cryptographic keys. When you "disconnect" using Tunnelblick, Tunnelblick actually shuts down OpenVPN completely, and creates a new instance of OpenVPN when you "connect", so the problem doesn't happen.)

You didn't provide your OpenVPN client configuration, but removing "persist-tun" may fix the problem. If not, consult OpenVPN documentation and experts for help.

As to your "expected behavior", you can control whether Tunnelblick disconnects on sleep and reconnects on wake on a per-configuration basis in Tunnelblick's "Advanced" settings.

**Comment by tomilov** [comment]
Problem on OpenVPN side.

**Comment by jkbullard** [comment]
@tomilov - It might help other people if you described the problem and how you fixed it.
