### ISSUE TITLE
Tunnelblick on Mac freezes after update to Catalina 10.15.6

### ISSUE THREAD

**Issue by vansickle** [Tunnelblick/Tunnelblick#641]
Tunnelblick 3.8.3 (build 5520)

**Describe the bug**
After updating to Mac OS 10.15.6 Tunnelblick:

1) Showing on start:

```
The usr system folder (/usr) is not secure.

Tunnelblick and other programs may not work properly until this problem is fixed.

The Console Log has details.
```

Even though:

```
sudo chmod 0755 /usr

chmod: Unable to change file mode on /usr: Read-only file system
```

2) After Macbook is awake from sleep - Tunnelblick freezes and blocks all outgoing connections (basically looks like no internet connection while wifi is connected)

**To Reproduce**
1. Have MacOS 10.15.6, SIP had been disabled
2. Start Tunnelblick - Should see the message
3. Connect to any VPN
4. Put laptop to sleep (close it)
5. Wake laptop.
6. No internet connection.
7. When hover over Tunnelblick icon - it shows spinner cursor and no reaction. In Activity Monitor - "Application is not responding"

**Comment by vansickle** [comment]
The information may be not full, I'll follow up on the issue later, as I have more time to investigate

**Comment by jkbullard** [comment]
@vansickle - Two separate problems:

 1. **/usr is not secure**: As the message says, please look in the [Console Log](https://tunnelblick.net/cConsoleLog.html) for a detailed explanation of the problem. I just verified that on a pristine 10.15.6 install, /usr is owned by root:wheel with permissions 0755 and is "com.apple.rootless". / is owned by root:admin with 0755 permissions.

 2. **Freeze after waking up**: This is usually caused by OpenVPN being unable to reconnect to the VPN server, which is usually a symptom of an OpenVPN configuration problem. (OpenVPN is trying to connect – and failing – so quickly that it overwhelms Tunnelblick's ability to keep up. Bou can probably avoid the problem by un-checking "Disconnect when computer goes to sleep" on the "Advanced" settings page. Be sure to select the configuration(s) that you want to change before you un-check the checkbox.

**Comment by vansickle** [comment]
@jkbullard Thanks for explanation, 2 seems to fix my issue and as of 1 - I have no clue why /usr is 777 for me and I'm unable to change it due to "read-only file system", I'll update/close the issue when I investigate the 1.

**Comment by jkbullard** [comment]
[This stackoverflow discussion](https://stackoverflow.com/questions/60469031/create-directory-dotenv-on-macos-read-only-file-system) has two answers which might help you correct the problem:

The first way is to use `usr`, not `/usr`, when referring to the folder:
<pre>
     cd /
     sudo chmod 0755 usr
</pre>

That doesn't work on my pristine 10.15.6, but it might work on a system with SIP disabled, so it's worth a try.

The second way (with SIP disabled) is to reboot normally, and _before doing anything else_, do
<pre>
     sudo mount -uw /
</pre>

to mount the filesystem as read-write. Fix the permissions, then reboot to restore the read-only status of the filesystem.

Notes:
 1. Although the answer for the second way says to reboot normally, it might be necessary to reboot in safe mode. Otherwise some third-party program might do something that would cause the `sudo mount -uw /` to not work because it would not be done _"before doing anything else"_.

 2. Make sure the owner of /usr is root:wheel; if not, correct that, too.

**Comment by jkbullard** [comment]
@vansickle - Did you solve the problem? If so, please describe how, so others may benefit from your experience.
