### ISSUE TITLE
Feature request: Updatable Configurations with private key

### ISSUE THREAD

**Issue by ikreb7** [Tunnelblick/Tunnelblick#646]
I want to use the updatable configuration ``.tblk``. But if each user has its own client certificates in the ovpn file, you couldn't make them public accessable. Is it maybe possible that you could only update certain lines. Like 1-50 and after is the certificate.

@jkbullard What do you think about this feature?

**Comment by jkbullard** [comment]
@ikreb7 - You have several options:

 1. You can store the client key in a separate file instead of having it imbedded in the OpenVPN configuration file. You then distribute a .tblk containing the client key file, an OpenVPN configuration file that references the client certificate file, and an Info.plist (so the OpenVPN configuration file can be updated using [simple updatable configuration](https://tunnelblick.net/cNewUpdatableConfigurations.html)). The updates you publish would not include the client key file. If the user was set up to not require a computer administrator's authorization, their original key file would be preserved when they updated.

 2. You can store the client key in a separate file and use the [old method of updating configurations](https://tunnelblick.net/cUpdatableConfigurations.html). Include the user's key file in the `TBKeepExistingFilesList` Info.plist entry and publish updates without the user's key file.

 3. You could "hide" the configuration updates for each user in a folder named with a UUID or a large random number. The `TBConfigurationUpdateURL ` in the Info.plist would include a folder name with the random number, e.g. `https://example.com/updatable-configs/123456789012345678901234567890`. Assuming attackers can't enumerate  the webserver folders, I think that would be reasonably secure.

 4. I don't remember if it will work or not, but you can try protecting the folder in which your webserver stores the update files using [basic accessauthentication](https://en.wikipedia.org/wiki/Basic_access_authentication). You'd put the username and password in the URL used to access the update, e.g. "https://username:password@example.com/updatable-configs/..."

**Comment by ikreb7** [comment]
Thanks for the very detailed answer.
