### ISSUE TITLE
Problem with connections

### ISSUE THREAD

**Issue by johannesrue95** [Tunnelblick/Tunnelblick#647]
[fehlerprotokoll.pdf](https://github.com/Tunnelblick/Tunnelblick/files/5502062/fehlerprotokoll.pdf)
Hello,

I’m not really sure  on how to address the issue because I’m able to have a steady VPN connection, well what tunnelblick tells me. 
However, I get request timeouts with ip addresses that I  suppose to connect to.

I need to connect to databases for my internship. My supervisor already got in contact with his admins and they tried to help, but were not able to. They said the up addresses are going through the tunnel, but the ping is not working. With that I’m unable to connect to the databases.

I’ve installed the beta version of tunnelblick. When I’m connected to the vpn the apparent IP address changed.
I’ll attach the diagnosis 

I hope someone is able to help me.

**Comment by jkbullard** [comment]
First, a question: do you mean that you cannot connect to the databases at all, or that it _sometimes_ does not connect to them?

Comments, in no particular order:

1. You're using a beta version of macOS, which could be a problem.

2. The log (please don't post it as a PDF, it's just plain text!) shows a problem with routing:

```
route: writing to routing socket: File exists
add net 2001:4ca0:2204:ff22::: gateway utun2: File exists 
```

That could be a problem in the routing sent by the OpenVPN server, or it could be a problem on your computer. **Try restarting your computer to see if the problem persists**.

3. You have another VPN (L2TP). I don't think that should affect this, but can't be sure.

4. There's a mix of IPv4 and IPv6 DNS addresses. I don't think that should affect this, but can't be sure.

5. The OpenVPN configuration file includes the "tun-ipv6" option, which seems to indicate that the configuration was written for older versions of OpenVPN. **You could try setting Tunnelblick to use OpenVPN 2.3.18 (and 2.5.0) to see if either of them work better.**

6. "ping" on Macs should only be used on IP addresses, not on names requiring DNS lookup, because ping (and many other command line tools such as dig) do not use the standard macOS mechanism for DNS resolution.

**Comment by johannesrue95** [comment]
Yes. I cannot connect to the databases given by my supervisor at all. It always gives me unable to connect to localhost. 

1. I restored Catalina 
2. sorry, I will do this in the future
3. I deleted the VPN (L2TP)

4 How can I change this?

I still have the same issue after I restored my machine to Catalina. 
here is another protocol


[protokoll.txt](https://github.com/Tunnelblick/Tunnelblick/files/5507042/protokoll.txt)
