### ISSUE TITLE
Feature request: Autoconnect on unknown WiFis

### ISSUE THREAD

**Issue by error401de** [Tunnelblick/Tunnelblick#648]
I would appreciate a feature that connects to unknown/insecure WiFis a lot (and does not autoconnect on whitelisted ones).
Is there any chance this feature could be considered?
Thanks!

**Comment by jkbullard** [comment]
It was considered years ago but rejected because there were third-party programs such as ControlPlane which could detect such things and then tell Tunnelblick to connect a VPN. ControlPlane was abandoned several years ago, but there may be similar programs that still work.

Another reason, more relevant now, is that Wi-Fi network names (SSIDs) can be spoofed, so there isn't any assurance that the Wi-Fi network you are connected to is the one that is whitelisted. So this feature would give a false sense of security.
