### ISSUE TITLE
"self signed certificate" error connecting to AWS VPN on v3.8.4 (works on 3.8.3a)

### ISSUE THREAD

**Issue by molomby** [Tunnelblick/Tunnelblick#649]
After upgrading to 3.8.4 (build 5600), connections to our AWS VPN failed with:

```
2020-11-13 12:43:51.999793 VERIFY ERROR: depth=0, error=self signed certificate: O=Thinkmill, CN=vpn.thinkmill.cloud
2020-11-13 12:43:51.999834 OpenSSL: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed
2020-11-13 12:43:51.999844 TLS_ERROR: BIO read tls_read_plaintext error
2020-11-13 12:43:51.999851 TLS Error: TLS object -> incoming plaintext read error
2020-11-13 12:43:51.999857 TLS Error: TLS handshake failed
```

Downgrading to 3.8.3a (build 5521) fixed the problem, now logs:

```
2020-11-13 12:59:55.545227 VERIFY OK: depth=1, O=Thinkmill, CN=vpn.thinkmill.cloud
2020-11-13 12:59:55.545594 VERIFY KU OK
2020-11-13 12:59:55.545606 Validating certificate extended key usage
2020-11-13 12:59:55.545613 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2020-11-13 12:59:55.545619 VERIFY EKU OK
2020-11-13 12:59:55.545624 VERIFY OK: depth=0, O=Thinkmill, CN=vpn.thinkmill.cloud
2020-11-13 12:59:55.567520 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
```

As far as I know this is a pretty standard AWS client VPN endpoint. The client config (.ovpn) we're using is downloaded from the AWS console.

Note also `self signed certificate` in the connection error – our certs are aren't self signed – so that maybe hints at the the cause..?

**Comment by jkbullard** [comment]
You're correct: the "self signed certificate" error message is misleading and doesn't necessarily mean what it says – it just means there is a problem with the certificate.

My guess is that the certificate verification failure is caused by the version of OpenSSL that's being used. OpenSSL 1.1.1 is more strict about validating certificates than 1.0.2 was.

Tunnelblick 3.8.3a included a copy of OpenVPN 2.4.9 built with OpenSSL 1.0.2u and another copy build with OpenSSL 1.1.1g; Tunnelblick 3.8.4 includes only an OpenVPN 2.4.9 built with OpenSSL 1.1.1h. (OpenSSL 1.0.2u is "out of support and should not be used" according to [the OpenSSL Downloads page](https://www.openssl.org/source/).)

Try using OpenVPN 2.4.9 - OpenSSL 1.1.1g in Tunnelblick 3.8.3a.

 * If it fails, then the problem is that 1.1.1 is more strict (and there is something wrong with the certificates. To resolve this, you should try getting more help from OpenSSL experts; you can find some links for that on the [Tunnelblick Support page](https://tunnelblick.net/support.html).

 * If OpenVPN 2.4.9 - OpenSSL 1.1.1g works, but OpenVPN 2.4.9 - OpenSSL 1.1.1h (in Tunnelblick 3.8.4) fails, then the problem could be that, in 1.1.1h, "Certificates with explicit curve parameters are now disallowed in verification chains if the X509_V_FLAG_X509_STRICT flag is used", according to [the OpenSSL 1.1.1 changelog](https://www.openssl.org/news/changelog.html#openssl-111). I have no idea what that means, so, again, you'd have to consult OpenVPN experts, or perhaps OpenSSL experts.

**Comment by molomby** [comment]
Thanks @jkbullard. I've tested several combinations now and can confirm the issue coincides with the switch to `OpenSSL 1.1.1h` in Tunnelblick `3.8.4beta05 (build 5570)`:

| Tunnelblick | OpenVPN | OpenSSL | Works |
|---------|---------|---------|---------|
| `3.8.3a (build 5521)` | `2.4.9` | `v1.0.2u` | ✔️ |
| `3.8.3a (build 5521)` | `2.4.9` | `v1.1.1g` | ✔️ |
| `3.8.3a (build 5521)` | `2.5 beta3` | `v1.0.2u` | ✔️ |
| `3.8.3a (build 5521)` | `2.5 beta3` | `v1.1.1g` | ✔️ |
| `3.8.4beta04 (build 5560)` | `2.4.9` | `v1.1.1g` | ✔️ |
| `3.8.4beta04 (build 5560)` | `2.5 beta4` | `v1.1.1g` | ✔️ |
| `3.8.4beta05 (build 5570)` | `2.4.9` | `v1.1.1h` | ❌  |
| `3.8.4beta05 (build 5570)` | `2.5 rc1` | `v1.1.1h` | ❌ |
| `3.8.4 (build 5600)` | `2.4.9` | `v1.1.1h` | ❌ |
| `3.8.4 (build 5600)` | `2.5.0` | `v1.1.1h` | ❌ |
| `3.8.5beta01 (build 5610)` | `2.4.9` | `v1.1.1h` | ❌ |
| `3.8.5beta01 (build 5610)` | `2.5.0` | `v1.1.1h` | ❌ |

**Comment by bishtawi** [comment]
Hi @molomby, I am curious if you have solved this issue? I believe I am running into the same problem. I am connecting to AWS Client VPN and it works fine with TunnelBlick 3.8.3a but fails on 3.8.4a. I was also able to narrow it down to OpenSSL v1.1.1h but cant figure out what exactly is wrong with my VPN setup.

**Comment by jkbullard** [comment]
@bishtawi - I think the problem is this, from the [OpenSSL change log](https://www.openssl.org/news/changelog.html#openssl-111):

> **Changes between 1.1.1g and 1.1.1h [22 Sep 2020]**
> 
> Certificates with explicit curve parameters are now disallowed in verification chains if the X509_V_FLAG_X509_STRICT flag is used.

(That is, it  isn't really a problem that there is a "self signed certificate", there is a problem with the certificate itself.

I could be wrong, but that's the only relevant change between OpenSSL 1.1.1g and 1.1.1h.

The solution would be to regenerate the certificates without explicit curve parameters.

**Comment by bishtawi** [comment]
Thought I would give an update to this just in case other people come across this issue. My setup was using RSA not ECDSA so I didnt have a curve parameters (explicit or not).

In my case, the "self signed certificate" error turned out to be because both my CA and my server had the same `common_name` for their certs. Once I regenerated new certs for my CA and server with different `common_name`, I was able to connect with the latest version of TunnelBlick.
