### ISSUE TITLE
Installation fails on Big Sur 11.0.1 (20B29)

### ISSUE THREAD

**Issue by jorycz** [Tunnelblick/Tunnelblick#650]
**Describe the bug**
Installation latest beta or stable version (3.8.4) can not be completed.

**To Reproduce**
1. Perform standard installation of latest beta. Download latest beta Tunnelblick 3.8.5beta01
2. Open (double-click) dmg, double-click on icon of Tunnelblick to start installation
3. Window appear about permissions _The tmp system folder (/private/tmp) is not secure._, click Continue ...
4. Enter Password for user ...
5. Window appear with _The installation or repair took too long or failed. Try again?_ and this message appears in console system.log:

Nov 13 12:11:32 mb Tunnelblick[2755]: Tunnelblick needs to:
	  • Be installed in /Applications as Tunnelblick
	  • Change ownership and permissions of the program to secure it
	  • Secure configurations
Nov 13 12:11:32 mb Tunnelblick[2755]: Beginning installation or repair
Nov 13 12:11:32 mb Tunnelblick[2755]: Unable to create flag file /tmp/tunnelblick-authorized-running
	Error was 'Permission denied'
Nov 13 12:11:32 mb Tunnelblick[2755]: Failed to execute /Volumes/Tunnelblick/Tunnelblick.app/Contents/Resources/installer: (
	    23
	)

6. If you click Retry, this one appears:

Nov 13 12:12:25 mb Tunnelblick[2755]: Retrying execution of installer
Nov 13 12:12:25 mb Tunnelblick[2755]: Unable to create flag file /tmp/tunnelblick-authorized-running
	Error was 'Permission denied'
Nov 13 12:12:25 mb Tunnelblick[2755]: Failed to execute /Volumes/Tunnelblick/Tunnelblick.app/Contents/Resources/installer: (
	    22
	)

**Expected behavior**
Finish installation.

**Additional context**
Happened after installation of 11.0.1 when installation Tunnelblick beta version is recommended. I removed my configurations from ~/Library folder and tried again but same result.

**Diagnostic information**
N/A

**Comment by jkbullard** [comment]
@jorycz - Please post the result of the following command in Terminal:

```
ls -le@d /tmp ; ls -le@d /private/tmp
```

**Comment by jorycz** [comment]
`lrwxr-xr-x@ 1 root  wheel  11 Jan  1  2020 /tmp -> private/tmp`
`	com.apple.rootless	 0 `
`drwxr-xr-x  9 root  admin  288 Nov 13 12:08 /private/tmp`

**Comment by jkbullard** [comment]
/private/tmp should have permissions of 777, not 755, and it should be owned by root:wheel.One of the early beta versions of Big Sur had it owned by root:admin, but it had the correct permissions of 777. My guess is that some software installer (perhaps even one of Apple's own installers) is setting incorrect permissions.

See [System Folder Security](https://tunnelblick.net/cSystemFolderNotSecure.html) for more info, but note that it has not been updated for 10.15 or 10.16 or 11.0 because none of the ownership or permissions of system folders have changed.

I don't know if just fixing the permissions will correct everything or if the wrong permissions are a symptom of a failed install of macOS.

**Comment by jorycz** [comment]
When I updated permissions like you said, installation completed. Thanks.
`sudo su - && cd /private/ && chmod 1777 tmp/ && chown root:wheel tmp/` fixed it.
