### ISSUE TITLE
mac m1 版本目前可以使用吗？

### ISSUE THREAD

**Issue by linyi-0** [Tunnelblick/Tunnelblick#663]
Can MAC M1 be used at present?

**Comment by Hambaobao** [comment]
Seems like no. But you can contact the developer for kexts used in beta version.[here](https://tunnelblick.net/cAppleSilicon.html).

**Comment by jkbullard** [comment]
@linyi-0 and @Hambaobao - Tunnelblick runs fine on M1 Macs using Rosetta 2. However, if your configuration uses a TAP connection, the released versions of Tunnelblick will not work because they cannot load the required system extension on an M1 Mac. We are testing a version that runs natively on M1 Macs and works with TAP connections.

For more information, see [Tunnelblick and Apple Silicon](https://tunnelblick.net/cAppleSilicon.html) and  [Tunnelblick and macOS Big Sur](https://tunnelblick.net/cBigSur.html).
