### ISSUE TITLE
【help】tunnelblick The picture quality is very fuzzy

### ISSUE THREAD

**Issue by li215065046** [Tunnelblick/Tunnelblick#672]
my：
![image](https://user-images.githubusercontent.com/48702493/111962827-c764e700-8b2d-11eb-8539-be6ef11a4b1d.png)
their：
![image](https://user-images.githubusercontent.com/48702493/111962889-dba8e400-8b2d-11eb-910d-2995271eb379.png)

help me！How to configure！

**Comment by rawtaz** [comment]
@li215065046 What you write makes no sense at all. If you are having an actual problem, please fill out the issue template you were presented with when opening this issue, and answer the questions properly. Otherwise please close this issue, because there's nothing in it showing an actual problem or feature request.
