### ISSUE TITLE
Import tunnelblick configuration to OpenVPN on iOS

### ISSUE THREAD

**Issue by salarai** [Tunnelblick/Tunnelblick#673]
Is there any way to import exisiting tunnelblick configuration to OpenVPN on iOS?
Getting this error while importing the config file 
![image](https://user-images.githubusercontent.com/60181463/112354645-30cf2c00-8ccd-11eb-851e-8115431311be.jpeg)

**Comment by jkbullard** [comment]
Whether or not a particular Tunnelblick or OpenVPN configuration can be imported into "OpenVPN on iOS" apparently depends on the particular options in the OpenVPN configuration file and "OpenVPN on iOS" doesn't allow you to import that particular configuration because it is a "tap" configuration.

It would be best to ask questions about what "OpenVPN on iOS" can import to the developers of "OpenVPN on iOS".
