### ISSUE TITLE
OpenVPN version 2.3.18 is listed but cannot be selected

### ISSUE THREAD

**Issue by olegueret** [Tunnelblick/Tunnelblick#678]
**Describe the bug**
If I try to choose an OpenVPN version 2.3.18 from the dropdown it immediately reverts to 2.4.10 - OpenSSL v1.1.1k.
This happens with both "2.3.18 - OpenSSL v1.0.2u" and "2.3.18 - LibreSSL v2.7.1" options.

Also a warning badge appears in the Tunnelblick icon. When opening the message it says something about using future versions of Tunnelblick and in the window that opens after that it says it will use OpenVPN 2.4.10 instead of requested version 2.3.18 (but doesn't explain why).

**To Reproduce**
1. Go to 'Configurations', choose a configuration and then the Parameter tab
2. Click on the 'OpenVPN version' dropdown
3. Choose one of the 2.3.18 options

**Expected behavior**
It should me let choose either 2.3.18 version. If the options are listed there I assume they can be used.
In the website docs (cOpenvpnVersions.html) it warns about using 2.3 versions, but it says "OpenVPN 2.3, which is past its end-of-life and is included only for those who need to connect to old versions of OpenVPN.", which is my case.

**Screenshots**
![Captura de Pantalla 2021-04-19 a les 19 58 22](https://user-images.githubusercontent.com/49993/115284577-24fc4b80-a14d-11eb-986b-88081877cebd.png)
![Captura de Pantalla 2021-04-19 a les 20 23 23](https://user-images.githubusercontent.com/49993/115284626-33e2fe00-a14d-11eb-97d2-c762e7e09f7c.png)
![Captura de Pantalla 2021-04-19 a les 19 40 18](https://user-images.githubusercontent.com/49993/115284644-38a7b200-a14d-11eb-92ba-833413f7a6ff.png)

**Additional context**
I need to connect to a really old server using an old certificate. It works with OpenVPN 2.3.18 but not with 2.4 or 2.5 due to insecure hashing of the certificate.
This worked fine with Tunnelblick 3.8.3a and stopped working from 3.8.4a. I cannot find 3.8.3a in the deprecated page of Tunnelblick's website, so I cannot downgrade.

I tried a custom OpenVPN binary as per the instructions in the website (cUsingCustomOpenVPNBinaries), using the same 2.3.18 binary included in the /Applications/Tunnelblick.app/Contents/Resources/openvpn/openvpn-2.3.18-openssl-1.0.2u/ folder and with the name "Openvpn/openvpn-2.3.18-openssl-1.0.2u_Custom_by_Oleguer": it appeared in the dropdown but it also refused to keep it when I selected it in the GUI. In this case, I assumed the check would not be performed because of using a custom binary...

**Diagnostic information**
[Tunnelblick-diagnostic.txt](https://github.com/Tunnelblick/Tunnelblick/files/6338225/Tunnelblick-diagnostic.txt)

**Comment by jkbullard** [comment]
Thanks for including the diagnostic info.

You must have clicked "OK" the first time the explanation of why OpenVPN version 2.4 must be used instead of 2.3.18 appeared. That window would have provided details about the problem.

However, from inspection, the problem is that the configuration contains a line with "compress lzo". "compress" is an option available only in OpenVPN 2.4 and higher. If Tunnelblick had allowed you to use OpenVPN 2.3.18, OpenVPN would have exited with an error because it does not recognize the "compress" option.

I suspect that you meant to use "compress-lzo" (note the hyphen), which is a valid option in OpenVPN 2.3. Try changing that one line and see if that allows you to use OpenVPN 2.3.18. If not, click "Reset Diagnostic Warnings" on Tunnelblick's "Preferences" panel, then quit and relaunch Tunnelblick and try to set the OpenVPN version to 2.3.18 again. That should cause the window to pop up explaining the problem.

Note that "comp-lzo" has been deprecated in OpenVPN 2.4, and "compress", introduced in 2.4, has been deprecated in OpenVPN 2.5. See [Deprecated Options in OpenVPN](https://community.openvpn.net/openvpn/wiki/DeprecatedOptions).

**Comment by olegueret** [comment]
Thanks @jkbullard that was the problem indeed. 
I switched to "comp-lzo" and it let me choose 2.3.18 again (compress-lzo is not valid in 2.3 as per the [reference manual](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-3/) at least).

> You must have clicked "OK" the first time the explanation of why OpenVPN version 2.4 must be used instead of 2.3.18 appeared. That window would have provided details about the problem.

The only window I saw was the one in the third screenshot (I got to show it again via Reset Diagnostic Warnings), which doesn't explain the problem of an invalid option used. Looking at the message in the [localization](https://github.com/Tunnelblick/Tunnelblick/blob/2016e30ca796a60659889c4f7ebba34bef09e826/tunnelblick/ca.lproj/Localizable.strings#L961) file I don't see a placeholder for the explanation.

**Comment by jkbullard** [comment]
> Looking at the message in the localization file I don't see a placeholder for the explanation.

The explanation and list of OpenVPN options that are involved are shown in a different string. See the logic in the `getOpenVPNVersionIxToUseConnecting` method (in VPNConnection.m).
