### ISSUE TITLE
Tunnelblick 3.8.6beta05 (build 5706) VPN is not connected after upgrading mac OS to Big Sur 11.4

### ISSUE THREAD

**Issue by kodali** [Tunnelblick/Tunnelblick#688]
**Describe the bug**
I have upgraded macOS from 10.1 to Big Sur 11.4. After this , TunnelBlick VPN is unable to connect, it is failed with this error, I have tried to add "ncp-disable" to .ovpn config file but error persist. Can some one please help, I have lost access to all production systems because of this VPN connectivity issue.

2021-06-29 15:27:23.670053 OPTIONS ERROR: failed to negotiate cipher with server. Add the server’s cipher (‘BF-CBC’) to --data-ciphers (currently ‘AES-256-GCM:AES-128-GCM’) if you want to connect to this server.
2021-06-29 15:27:23.670061 ERROR: Failed to apply push options

**Comment by acerbin** [comment]
Getting the same (after Tunnelblick upgrade)

**Comment by jkbullard** [comment]
This is a problem with the OpenVPN configuration.

If it happens after a Tunnelblick update, it could be because the update defaults to use a newer version of OpenVPN. For example, Tunnelblick 3.8.6a defaults to use OpenVPN 2.5; older versions defaulted to use OpenVPN 2.4.

The best way to correct this problem is to fix the OpenVPN configuration. Consult whoever set up your VPN, or get help from sources of OpenVPN expertise (the Tunnelblick Support page has links).

As an alternative, you can specify an older version of OpenVPN on the "Settings" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window. However, at some point newer versions of Tunnelblick will include only newer versions of OpenVPN, and will no longer be able to connect with old configurations that have not been updated.

**Note: when submitting an Issue, please include the information obtained by the procedure described in [Before You Post](https://tunnelblick.net/cBeforeYouPost.html).**

**Comment by zhucenichenghao** [comment]
> This is a problem with the OpenVPN configuration.
> 
> If it happens after a Tunnelblick update, it could be because the update defaults to use a newer version of OpenVPN. For example, Tunnelblick 3.8.6a defaults to use OpenVPN 2.5; older versions defaulted to use OpenVPN 2.4.
> 
> The best way to correct this problem is to fix the OpenVPN configuration. Consult whoever set up your VPN, or get help from sources of OpenVPN expertise (the Tunnelblick Support page has links).
> 
> As an alternative, you can specify an older version of OpenVPN on the "Settings" tab of the "Configurations" panel of Tunnelblick's "VPN Details" window. However, at some point newer versions of Tunnelblick will include only newer versions of OpenVPN, and will no longer be able to connect with old configurations that have not been updated.
> 
> **Note: when submitting an Issue, please include the information obtained by the procedure described in [Before You Post](https://tunnelblick.net/cBeforeYouPost.html).**

it works!

**Comment by rouge2203** [comment]
For anyone in 2025, indeed changing to a previous version ( in my case 2.4.12) works. Settings -> OpenVPN version:
