### ISSUE TITLE
How to migrate 

### ISSUE THREAD

**Issue by mingqibee** [Tunnelblick/Tunnelblick#709]
Hi 
How to migrate so that customers do not need to change client.ovpn

**Comment by jkbullard** [comment]
What do you mean by "migrate"?

**Comment by mingqibee** [comment]
@jkbullard HI   Migrate VPN servers from one machine to another

**Comment by jkbullard** [comment]
Without changing client.ovpn, you need to set up so the new server is used instead of the old server:
 * If client.ovpn uses a domain name, point the domain name to the new server.
 * if client.ovpn uses an IP address, it depends. Consult networking experts.

Note that you would also need to make sure the new server has the correct keys and certificates.

However, such a change (to the "remote" option in client.ovpn) is a "safe" change. That means that you could have users update their existing Tunnelblick configuration with a new one containing the change. See [Standard Users Installing or Replacing Configurations](https://tunnelblick.net/cNonAdminInstalls.html) and [this discussion](https://groups.google.com/u/1/g/tunnelblick-discuss/c/YZJYTcUqZyw).

**Comment by mingqibee** [comment]
Hi @jkbullard
Migrate server1 to server2
The database has been migrated and verified to be fine.

Network problems：
I use an elastic public address. The public address can be resolved into a domain name or stored on a new server using the existing public address
I have tried to change the remote of the current client.ovpn into the domain name, which can be connected normally

The question now is which keys from server1 need to be copied to server2

**Comment by mingqibee** [comment]
Hi @jkbullard 
"Note that you would also need to make sure the new server has the correct keys and certificates."
Which certificate in server1 should I use for this certificate? Server2 will do

**Comment by jkbullard** [comment]
@mingqibee - That depends on how your VPN is set up, and it's an OpenVPN question. Some links to OpenVPN resources are available on our [Support](https://tunnelblick.net/support.html) page.
