### ISSUE TITLE
Setting to install betas is checked by default an cannot be changed

### ISSUE THREAD

**Issue by Jorsta** [Tunnelblick/Tunnelblick#732]
On our Macs where Tunnelblick installed with Installomator, Tunnelblick is set to install beta versions by default. 
Moreover, the settings it locked so it cannot be changed.

All Macs are running MacOS 12 Monterey (most of then 12.5.1).

Se screenshot (Swedish client).

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/4170174/186428165-711a4398-0989-40bf-8218-28d4d2188b48.png">

**Comment by Jorsta** [comment]
Current versions on all computers where its installed by Installomator:

> Tunnelblick 3.8.8beta04 (build 5800); prior version 3.8.8beta03 (build 5790)

**Comment by jkbullard** [comment]
The checkbox is checked and cannot be changed because the version of Tunnelblick that is running is a beta version.

Tunnelblick does that so you cannot "update" to an earlier stable version, which might contain security vulnerabilities.

If you want Installomator to install a non-beta version, you'll have to modify it. Tunnelblick betas all have "beta" in their .dmg name; stable versions do not.

**Comment by Jorsta** [comment]
OK, thanks for your answer @jkbullard
