### ISSUE TITLE
Update to latest OpenVPN version 2.5.8

### ISSUE THREAD

**Issue by ozmartian** [Tunnelblick/Tunnelblick#740]
As per subject. Is this project dead? Hasn't been touched in 6 months which makes us sad.

**Comment by jkbullard** [comment]
I didn't create a new Tunnelblick release for OpenVPN 2.5.7 because it has nothing that affects Tunnelblick other than "print OpenSSL error stack if decoding PKCS12 file fails", which is uncommon and merely an enhancement of an error message.

Although there are a few minor non-security related changes in 2.5.8, I didn't think there was anything that was compelling. (Tunnelblick already works around some of the OpenVPN bugs that were fixed.)

What in 2.5.8 is important to you?

**Comment by ozmartian** [comment]
Many thanks for the response. I wasn't aware of the minor changes being irrelevant. Thx for all your work.
