### ISSUE TITLE
Unidentified developer in macOS system settings

### ISSUE THREAD

**Issue by cassiocassio** [Tunnelblick/Tunnelblick#742]
I **think** I trust this script, but the name and "unidentified" attribution don't encourage this belief

macOS 13.2

![Screenshot 2023-02-06 at 16 36 24](https://user-images.githubusercontent.com/4593556/217030792-b6c7af4c-4f6f-4e30-8121-94060f237222.png)

**Comment by jkbullard** [comment]
It's not signed by an _identified_ developer because it is a shell script, and shell scripts cannot be signed for macOS.

But assuming you are using a copy of Tunnelblick installed from a disk image downloaded from the official website, tunnelblick.net, the LaunchAtLogin.sh that is included is part of Tunnelblick.app and is protected by Tunnelblick.app's digital signature.

And because Tunnelblick checks its own signature each time it is launched, any change to LaunchAtLogin.sh would be detected the next time Tunnelblick is launched.

**Comment by brycied00d** [comment]
This has caused confusion and concern on both my part (I'm technically inclined) and my parent's (not so technically inclined - didn't know what a .sh file was and whether it was Bad :tm:). Because it can't be signed with identifying information, it appears as a random script with no clues as to what it is from without digging into via System Preferences and Finder.

I appreciate the extra details @jkbullard confirming that the script's integrity is still validated, and why the script itself cannot be signed.

If the script were to be renamed to "Tunnelblick-launchAtLogin.sh" (for example) there would at least be *something* identifying that it's related to Tunnelblick.

Is this something that can be easily renamed? Would the existing "Background Item" need to be removed manually?

**Comment by jkbullard** [comment]
Thanks, @brycied00d — renaming the script is a great suggestion.

Users can’t rename the script because it’s protected by the digital signature of the Tunnelblick app. But it’s something I’ll try to get into the next beta release. Making it a binary executable instead of a script would let it have its own signature, but that’s more work, so renaming it will probably happen first.

**Comment by jkbullard** [comment]
Fixed in Tunnelblick 4.0.0beta03.
