### ISSUE TITLE
Long configuration names are truncated in the display of Configurations

### ISSUE THREAD

**Issue by cthart** [Tunnelblick/Tunnelblick#744]
**Describe the bug**
In the Configurations tab of Tunnelblick, on my machine (running in Dark mode at least) I can't read the entire name of the configurations. I append a date for testing new versions but it's very difficult for me to tell which is which. As a workaround I can choose Rename to reveal the whole name.

**To Reproduce**
1. Tunnelblick menu -> VPN Details... 
2. choose the Configurations tab
3. Notice at the left that the Configuration names are truncated with ellipses (...) if they are too long

**Expected behavior**
I would like the column to be wider -- there is plenty of room. I can tell if there is something I can drag to make the column wider. If there is, I can't find it.

**Screenshots**
![Screen Shot 2023-02-15 at 17 38 09](https://user-images.githubusercontent.com/1210365/219096321-623c7e8b-20fe-46e3-829a-6eed0c4bbd4e.png)

**Desktop (please complete the following information):**
macOS 12.6.3, running in Dark mode, if that makes a difference.

**Comment by jkbullard** [comment]
@cthart Thanks for your report.

This is a problem with the way Tunnelblick displays the configuration names when it is first loaded:
![Screen Shot 2023-02-15 at 12 26 05 PM](https://user-images.githubusercontent.com/127273/219106216-ea72d364-fe58-4da4-a9f7-6eedaee63ae5.png)

As a workaround:

1. Select any configuration.

2. Drag the blue border to the right of the names to the left, so it makes the names even shorter:
![Screen Shot 2023-02-15 at 12 27 30 PM](https://user-images.githubusercontent.com/127273/219106541-e3632370-ae76-4041-b779-1fd1bcddfef2.png)

3. Drag the same blue border to the right. The names will expand properly:
![Screen Shot 2023-02-15 at 12 28 48 PM](https://user-images.githubusercontent.com/127273/219106866-d82e2594-f237-4792-a1df-c99487a0dbd9.png)

**Comment by jkbullard** [comment]
Fixed in Tunnelblick 4.0.0beta03.

**Comment by ady-ghe** [comment]
still present in Tunnelblick 6.0.1

**Comment by jkbullard** [comment]
@ady-ghe - The problem reported by the original poster (names displaying with ellipses when the full name would fit in the space provided – see the first screenshot) is fixed. Nobody else has reported a problem with that in the last year, and I can't reproduce it. Ellipses are shown only when the left side of the "VPN Details" window is too narrow to contain the entire name.

Are you expecting Tunnelblick to _automatically_ widen the left side of the window so that ellipses are not required even for long configuration names? Tunnelblick doesn't do that, just as Finder doesn't automatically widen the filename column in list view so that ellipses are not required for long filenames. Tunnelblick allows you to _manually_ adjust the width of the left side of the window and the width and height of the window however you wish.

If not: 

- What version of macOS are you using?
- What exactly is it that is "still present"?
- What sequence of steps reproduce the problem for you (please include one or more screenshots, as @cthart did)?
