### ISSUE TITLE
VPN credential option not working as expected.

### ISSUE THREAD

**Issue by uncharted-user** [Tunnelblick/Tunnelblick#747]
**Describe the bug**
Adding credentials using VPN credential option is not working for authentication. I tried to add username and password separated by comma and tried both as separate and common credentials. I don't know whether it was supposed to work like the way I described. Saving credentials are working for keychain, but I am trying to avoid keychain. 

**To Reproduce**
1. Import a .ovpn configuration,
2. Select the configuration and click on Advanced,
3. Click on VPN Credentials tab,
4. Add username, password credential,
5. Select this configuration uses username, password credential,
6. Try to connect to the server.

**Expected behavior**
Tunnelblick probably should connect to the server successfully.

**Screenshots**
<img width="813" alt="Screen Shot 2023-03-14 at 3 30 14 AM" src="https://user-images.githubusercontent.com/100132960/225420862-ca8caa8b-966c-4ecc-8fb5-72b5b078e928.png">

**Desktop (please complete the following information):**
 - macOS Monterey 12.6.3
 - Tunnelblick 3.8.8a (build 5776)

**Additional context**
Currently, I am following the workaround,

1. Create a file with credentials.key file with following lines,
Username
Password
2. Open each .tblk file from ~Library/Application Support/Tunnelblick/Configurations with VSCode and insert created credentials.key file ~/Library/Application Support/Tunnelblick/Configurations/Japan.tblk/Contents/Resources
3. Edit the configuration file and replace auth-user-pass with following,
auth-user-pass credentials.key

**Comment by jkbullard** [comment]
First, the OpenVPN configuration itself determines whether or not you need a username and password to connect to the VPN. That is not something you or Tunnelblick controls in any other way.

That said, I think there is a misunderstanding of what the "VPN Credentials" tab is for. It is in the "Advanced" settings because it is not needed nor used by most users. **If you have a single VPN configuration or each of your configurations has its own credentials, it is of no use to you.**

If you have one configuration, for example, you simply import the configuration. Then, the first time you try to connect the configuration, Tunnelblick will ask you for a username and password and allow you to save the username or the username and password.

- If you saved nothing, each later connection will ask for both the username and password.
- If you saved only the username, each later connection will ask for the password, having autofilled the username.
- If you saved both the username and password, each later connection will be made without asking you for anything.

Note:

1. There _is_ a checkbox that allows you to save the username and password but be prompted for it at each connection. In that case, you will be asked, but both the username and password will be autofilled. This is usually used for some connections that require a specific type of mutifactor authentication.
2. You may save the username or the username and password any time you are asked for credentials, not just the first time.

If you have a second configuration (and a third, fourth, etc.) that has different credentials, then each of them would be done similarly and independently.

The **"VPN Credentials"** tab is used when a single set of credentials is used for two or more configurations. For example, many commercial VPN service providers give you a single set of credentials but give you many (perhaps dozens) of VPN configurations, usually located in different countries. If you use such a service, you can check the box to specify that all configurations use the same credentials. Then the first time you connect any of the configurations, you will be asked for the username and password as described above. If you save both the username and password for, say, the VPN server in France, the next time you connect to a different server, say the VPN server in Belgium, it will use the credentials you entered for the VPN server in France, and you will not be asked for credentials.

**"Named credentials"** is for more complex situations. Suppose you have three different VPN service providers, each one has its own credentials, and each one has dozens of servers. You can create three sets of credentials, name each of them for the service provider associated with the credentials, and indicate to Tunnelblick that each of your configurations uses credentials from one of the three named credentials. You will be prompted to enter the credentials for each provider only the first time you connect one of that provider's configurations (assuming you save the credentials).

**Comment by uncharted-user** [comment]
Thank you for the response with such a detailed explanation. I would like to request you to add this explanation in the documentation (I failed to find it).

> The "VPN Credentials" tab is used when a single set of credentials is used for two or more configurations. For example, many commercial VPN service providers give you a single set of credentials but give you many (perhaps dozens) of VPN configurations, usually located in different countries. If you use such a service, you can check the box to specify that all configurations use the same credentials.

Yes, my VPN provider provides exactly you described above, but my objective is to avoid saving in Keychain. Could you please tell me whether it is currently possible?

<img width="753" alt="Screen Shot 2023-03-16 at 5 06 48 AM" src="https://user-images.githubusercontent.com/100132960/225463991-ea5dacc9-1ad8-4f97-abc2-75f9698dd533.png">

**Comment by jkbullard** [comment]
Why don't you want to save credentials in the Keychain? That's the usual place for storing such information on macOS.

The only other option Tunnelblick and OpenVPN provide is to save the username/password in a file, as you describe as a workaround.

**Comment by uncharted-user** [comment]
Sorry, I am more lean toward FOSS or at least Open Source. You can criticize me for using macOS, but I wish FreeBSD would have been more desktop friendly, similar to servers. Although I use Fedora on other machine. I am writing a shell script to make the workaround easy for me. I just needed to confirm that I'm not missing any feature already implemented.

Your macOS app as well as android app is amazing in terms of performance, energy consumption. I really love Tunnelblick. Thank you for the hard work. I hope this project will live long.

**Comment by jkbullard** [comment]
If you modify a .tblk (as your script will) in ~Library/Application Support/Tunnelblick/Configurations, the secured "shadow" copy of the configuration, contained in /Library/Application Support/Tunnelblick/Users/USERNAME/, should be created or updated. The ownership and permissions of each subfolder and file in that folder must also be set correctly to secure the "shadow" copy. (For security reasons, the "shadow" copy is the one that Tunnelblick actually uses to connect.)

Tunnelblick can do that for all of the configurations at once with the following command:

     sudo /Applications/Tunnnelblick.app/Contents/Resources/installer 16

The above applies to "private" configurations. "Shared" configurations are done slightly differently; they are only stored in one place, which is secured and therefore must be manipulated using sudo. The ownership and permissions of the shared configurations must also be maintained carefully, although the above command will correct any errors and make sure they are secured.

**Comment by uncharted-user** [comment]
> the secured "shadow" copy of the configuration, contained in /Library/Application Support/Tunnelblick/Users/USERNAME/, should be created or updated.
I am surprised that Tunnelblick is connecting, although the change I made on ~Library/Application Support/Tunnelblick/Configurations did not have any reflection on /Library/Application Support/Tunnelblick/Users/USERNAME/. 

>  sudo /Applications/Tunnnelblick.app/Contents/Resources/installer 16
Is that all I need to do after creating folders for shadow copy? I guess then I don't have to write anything for setting permissions there!

**Comment by jkbullard** [comment]
When a connection to a private configuration is requested, Tunnelblick checks that the two copies are identical. If they are not, Tunnelblick asks the user if the secure copy should be updated from the insecure copy, and if it should, asks for a computer administrator’s authorization to do so.

You needn’t do anything in the secure folder. Just set up all of the insecure.talks as you wish, then run the install command. That will copy all insecure copies to the secure folder and set the secure copies ownership and permissions properly.

Note: it is important that the username-password files. Have an extension of “.key” so they will be secured properly.

**Comment by uncharted-user** [comment]
That's great! However, running the sudo command is giving me the following error,
`sudo: /Applications/Tunnnelblick.app/Contents/Resources/installer: command not found`

> Note: it is important that the username-password files. Have an extension of “.key” so they will be secured properly.

Yes, I made the bash script to make a file with key extension.

>The scripts will be executed automatically if they are included in the Tunnelblick VPN Configuration (".tblk"). 

Is there any way to hook my bash script to execute automatically when the Tunnelblick is loading?

**Comment by jkbullard** [comment]
Sorry, it should be

     sudo /Applications/Tunnelblick.app/Contents/Resources/installer 16

(I misspelled Tunnelblick!)

**Comment by uncharted-user** [comment]
Sorry, I should've figured out that. The command ran successfully and reset the permission as it should be, but shadow copy did not sync with configurations. I ran that command after quitting Tunnelblick.

**Comment by jkbullard** [comment]
> The command ran successfully and reset the permission as it should be, but shadow copy did not sync with configurations. I ran that command after quitting Tunnelblick.

I can't understand that. installer should first copy every .tblk in ~Library/Application Support/Tunnelblick/Configurations to /Library/Application Support/Tunnelblick/Users/SHORT_USERNAME. Then it should secure each of the copies.

Can you post a diff of the two folders done after the "sudo …installer 16" command?

**Comment by uncharted-user** [comment]
I don't know why it is not copying even after closing the app. The output of those commands are as follows,

```
username@U-Macbook ~ % sudo diff -bur /Users/username/Library/Application\ Support/Tunnelblick/Configurations /Library/Application\ Support/Tunnelblick/Users/username

Only in /Users/username/Library/Application Support/Tunnelblick/Configurations: .DS_Store
diff -bur /Users/username/Library/Application Support/Tunnelblick/Configurations/Montreal.tblk/Contents/Resources/config.ovpn /Library/Application Support/Tunnelblick/Users/username/Montreal.tblk/Contents/Resources/config.ovpn
--- /Users/username/Library/Application Support/Tunnelblick/Configurations/Montreal.tblk/Contents/Resources/config.ovpn	2023-03-18 17:08:46.000000000 +0600
+++ /Library/Application Support/Tunnelblick/Users/username/Montreal.tblk/Contents/Resources/config.ovpn	2023-03-16 05:05:49.000000000 +0600
@@ -17,7 +17,7 @@
 
 remote-cert-tls server
 
-auth-user-pass credentials.key
+auth-user-pass
 
 #comp-lzo
 verb 3
Only in /Users/username/Library/Application Support/Tunnelblick/Configurations/Montreal.tblk/Contents/Resources: credentials.key
```

**Comment by jkbullard** [comment]
Sorry, I just tried this and had the same result. You can't use `sudo` with the installer to get the result you want. (You'll see errors from installer in /tmp/tunnelblick-installer-log.txt.)

The problem that using `sudo` doesn't set the user the same way that Tunnelblick does it. `sudo` runs installer solely as root, without indicating that it came from "username". When Tunnelblick itself runs installer, it runs it in a way that tells installer that the user it is being run for is username, but executes installer as root.

So I think you'll have to copy the .tblk and set ownership/permissions yourself. I think you can use the following:

**In ~/Library/Application Support/Tunnelblick/Configurations:**

<table>
<tr><td>file or folder</td><td>owner</td><td>group</td><td>permissions (octal)</tr>
<tr><td>xxxx.tblk/</td><td>username</td><td>usergroup</td><td>750</tr>
<tr><td>xxxx.tblk/Contents/</td><td>username</td><td>usergroup</td><td>750</tr>
<tr><td>xxxx.tblk/Contents/Resources/config.ovpn</td><td>username</td><td>usergroup</td><td>700</tr>
<tr><td>xxxx.tblk/Contents/Resources/credentials.key</td><td>username</td><td>usergroup</td><td>700</tr>
</table>

**In /Library/Application Support/Tunnelblick/Users/username:**

<table>
<tr><td>file or folder</td><td>owner</td><td>group</td><td>permissions (octal)</tr>
<tr><td>xxxx.tblk/</td><td>root</td><td>wheel</td><td>755</tr>
<tr><td>xxxx.tblk/Contents/</td><td>root</td><td>wheel</td><td>755</tr>
<tr><td>xxxx.tblk/Contents/Resources/config.ovpn</td><td>root</td><td>wheel</td><td>700</tr>
<tr><td>xxxx.tblk/Contents/Resources/credentials.key</td><td>root</td><td>wheel</td><td>700</tr>
</table>
