### ISSUE TITLE
Tunnelblick 3.8.8c fails to install

### ISSUE THREAD

**Issue by mjsteinbaugh** [Tunnelblick/Tunnelblick#758]
Installed via Homebrew Cask:

```sh
brew install --cask tunnelblick
```

When attempting to launch Tunnelblick, after being prompted to secure the installation, I'm seeing this error:

```
The installation or repair took too long or failed. Try again?
```

Attempting to retry just results in the same issue.
The previous release prior to 3.8.8c was working correctly on my machine.

Running on macOS Ventura 13.5.

Best,
Mike

**Comment by mjsteinbaugh** [comment]
Can confirm that reinstalling 3.8.8b works on my machine.

**Comment by mjsteinbaugh** [comment]
The Tunnelblick beta 4.0.0beta06 release also works.

```sh
brew install --cask tunnelblick-beta
```

**Comment by philsherry** [comment]
Same for me: 3.8.8c fails, claiming it takes too long. 
Apple M1 Max
macOS 13.5 (22G74)

**Comment by Levi-Root3** [comment]
Same for me. 3.8.8c fails with the same message as OP on several Macs, running macOS 13.2.1 and 13.5

**Comment by jkbullard** [comment]
@philsherry @Levi-Root3: Are you using brew?

@mjsteinbaugh @philsherry @Levi-Root3:
1. What are the contents of /Library/Application Support/Tunnelblick/tunnelblick-installer-log.txt
2. Do the older versions of Tunnelblick ask to secure themselves on first run after being installed by brew?

**Comment by Serneum** [comment]
Seeing the same issue, both with Brew and with the installer from the website. Not seeing any logs at the location mentioned. I am working off of MacOS Ventura 13.3.1 (a) and an Intel-based Mac

**Comment by corporate-gadfly** [comment]
Pasting the link for downgrading to `3.8.8b` in case it helps someone else:
```
brew install --cask https://raw.githubusercontent.com/Homebrew/homebrew-cask/ab7f83ae033b6c72d2ea6c4dd5cd8a64c1040a3d/Casks/tunnelblick.rb
```

**Comment by philsherry** [comment]
@jkbullard Using brew, yes. 

It had tried to update itself on my work Mac, but my work Mac had very recently had some nanny software installed by my employer, so I thought maybe that was the issue. I uninstalled that and eventually found my way here. I'd already lost too much time so I just had to install the beta version to get my work done—meaning the log details the successful installation of the beta app.

@Levi-Root3 You’re looking in the wrong Library, check that path again: `/Library` not `~/Library`.

**Comment by nickmax99** [comment]
Seeing the same issue on a clients M2 MacBook Air; fails with "The installation or repair took too long or failed. Try again?"

3.8.8b works without issue. Both were installed from the website via the .dmg. He told me that he'd tried the beta before and that had also failed but I didn't verify that with him.

**Comment by jkbullard** [comment]
@nickmax99 - Is this a new installation of Tunnelblick, or installing over an existing installation?

@everyone:

3.8.8c and 4.0.0beta07 have a problem with new installations: the folder /Library/Application Support/Tunnelblick and its subfolders are not created early enough, and the installer fails when trying to write a file into a folder that does not yet exist. That problem may mask other problems that the installer detects. It could affect brew if brew "uninstalls" those folders before installing Tunnelblick over an existing installation, or if it is a new installation.

**Anyone who has experienced this problem is encouraged to write to developers@tunnelblick.net to be sent a link later today tomorrow to a new version of Tunnelblick that fixes the problem.**

**Comment by ncorona** [comment]
Same problem here with the lastest version, downgraded to 3.8.8b as suggested by @corporate-gadfly and now it's fine.
Fresh new installation on OSX Monterey 12.6.8, Intel
It fails with message "The installation or repair took too long or failed. Try again?" as @nickmax99

**Comment by gcharita** [comment]
I had the same issue. After inspecting the **console logs**, I found the following error:

```console
Error creating or overwriting file at /Library/Application Support/Tunnelblick/tunnelblick-authorized-done
```

Interestingly enough there was no directory with the name `Tunnelblick` under `/Library/Application Support` directory, so I went ahead and created it:

```
sudo mkdir /Library/Application\ Support/Tunnelblick
```

After that, I runned Tunnelblick again and installation succeeded. 😃

**Comment by Levi-Root3** [comment]
Hi @philsherry 
There was no log file in the other Library folder. 
But it seems the problem has already been confirmed and a newer version solves it. I will mail developers@tunnelblick to acquire it.

**Comment by JimJafar** [comment]
For me the problem was I use Mackup which replaces ~/Library/Application Support/Tunnelblick/Configurations with a symlink.

In my `/Library/Application Support/Tunnelblick/tunnelblick-installer-log.txt` was a log saying something like `apparent symlink attack`.

I just temporarily moved the real Configurations directory back, completed the installation, then replaced the symlink. 

Tunnelblick does not seem to care if there's a symlink when running, only during installation.

**Comment by jkbullard** [comment]
@JimJafar wrote:
> Tunnelblick does not seem to care if there's a symlink when running, only during installation.

That's correct. It's because symlinks complicate security during installation, which runs with elevated privileges, but not during normal operation (connecting, etc.), when that folder's contents are only accessed with the user's privileges.
