### ISSUE TITLE
Every action prompts for password and Touch ID does not work

### ISSUE THREAD

**Issue by freebrowser1** [Tunnelblick/Tunnelblick#764]
**Describe the bug**
I have to filling password at every change and even when starting up the app. Moreover I cannot even use Touch ID and have to type it manually. Very annoying.

**To Reproduce**
1. Click on Tunnelblick logo in menu bar and click on VPN details 
2. Add a new .ovpn configuration file
3. It prompts for a password, even when "Inhibit automatic update checking and IP Address checking" is unchecked
4. And one has to type in a password: Touch ID does not work

**Expected behavior**
No password prompt should happen

**Screenshots**
<img width="912" alt="Screenshot 2023-09-06 at 21 22 40" src="https://github.com/Tunnelblick/Tunnelblick/assets/26625141/9b70fc4f-f431-48a7-bdb2-79358b7af9ed">

**Desktop (please complete the following information):**
 - OS: macOS M1
 - Browser [e.g. chrome, safari] N/A
 - Version 13.4

**Comment by jkbullard** [comment]
@freebrowser1 - Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

**Comment by freebrowser1** [comment]
> @freebrowser1 - Please post the diagnostic info obtained by following the instructions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html).

This is just about the app. 
The checklist covers about when OpenVPN does not connect, but for mr VPN connection works normally, but at every start of Tunnelblick or changing / adding a new .ovpn file I have to fill in a password manually.

**Comment by jkbullard** [comment]
Sorry, I misunderstood.

Tunnelblick must get a computer administrator's authorization to add a configuration because configurations can contain scripts which run as root, and if a non-admin creates and installs such a configuration, they would be able to "escalate privileges" to become root.

The way Tunnelblick gets authorization is to ask macOS for it. It is actually macOS which is asking for the password; Tunnelblick does not have access to the password. macOS gives Tunnelblick an authorization token, which it then uses to perform the privileged operations involved in installing a configuration.

There is a way to have Tunnelblick not prompt for authorization to install a "safe" configuration: Un-check the "Require administrator authorization to install all configurations" checkbox (which must be done with administrator authorization : ). If that is not checked, "safe" configurations (those which cannot invoke a script) can be installed without administrator authorization.

Tunnelblick also allows as admin to pre-authorize all actions for up to five minutes; just click the "Enter admin mode" button at the top of Tunnelblick's "VPN Details" window.

Unfortunately, the mechanism that Tunnelblick uses (to avoid having access to the password) does not allow Touch ID, so we cannot offer that as an alternative.

**Comment by freebrowser1** [comment]
Indeed, I think that it is a bug in macOS that the Touch ID does not always work and has nothing to do with Tunnelblick.
