### ISSUE TITLE
macOS 14.0 (Sonoma) compatibility

### ISSUE THREAD

**Issue by MPV** [Tunnelblick/Tunnelblick#768]
**Describe the bug**
Could you confirm the compatibility with macOS Sonoma (`14.0`)?

**To Reproduce**
1. Upgrade to macOS Sonoma

**Expected behavior**
Tunnelblick should work.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 14.0 Sonoma

**Additional context**
I found the issues below, and just wanted to make sure Tunnelblick won't have the same issue (thus holding back an upgrade to macOS Sonoma):
- https://news.ycombinator.com/item?id=37498979
   - https://mullvad.net/en/blog/2023/9/13/bug-in-macos-14-sonoma-prevents-our-app-from-working/

**Comment by mahendrasumasoft** [comment]
There is a problem after upgrading to Sonoma 14.1, Both Open VPN connect and Tunnelblick are unable to provide VPN connection, It connects but not able to route through the VPN. 
<img width="503" alt="Screenshot 2023-11-08 at 7 25 03 PM" src="https://github.com/Tunnelblick/Tunnelblick/assets/61239249/421eafe1-623a-488f-ac78-682175a66e9f">

**Comment by jkbullard** [comment]
@mahendrasumasoft - What version of macOS was last working for you?

**Comment by mahendrasumasoft** [comment]
> @mahendrasumasoft - What version of macOS was last working for you?

Tested until Ventura 13.5.2, It was working. Then upgraded to 14.

**Comment by mahendrasumasoft** [comment]
> @mahendrasumasoft - What version of macOS was last working for you?

Tested until Ventura 13.5.2, It was working. Then upgraded to 14.

**Comment by jkbullard** [comment]
@mahendrasumasoft - Please follow the directions at [Read Before You Post](https://tunnelblick.net/cBeforeYouPost.html) and paste the info in a reply or in an email to developers@tunnelblick.net.

**Comment by mahendrasumasoft** [comment]
sent an email. Thank you.

**Comment by jkbullard** [comment]
@mahendrasumasoft - I received your email with the diagnostic info, thank you.

**Where did this configuration file come from?**  It includes several "remote" entries which are very strange because they are non-routable (private) IP addresss such as 192.168.221.1 and 10.12.13.1. Those are IP addresses on a LAN, not Internet IP addresses. So if you move your computer to another network (for example, from home to an office, or an office to an Internet cafe), they would not work and would try to connect to VPN servers that don't exist on the new network.

-------

If you are troubled by the message that "The computer's apparent public IP address is not different…", that is a completely separate issue and may not be a problem, it depends on what you want to do:

- If you want everything to go through the VPN, then put a check in Tunnelblick's "Route all IPv4 traffic through the VPN" checkbox.
- If you want only traffic going to servers on the VPN network to go through the VPN, then leave the checkbox unchecked and ignore the message.

**Comment by mahendrasumasoft** [comment]
My Mac was connecting through personal as well as office network, now the problem is identified, issue was with order of DNS order was office DNS first and then 8.8.8.8 second, we reversed that to 8.8.8.8 first and that solved the issue, also checked the option  "Route all IPv4 traffic through the VPN". Thanks.

**Comment by jkbullard** [comment]
You're welcome.

However, on macOS, only the first DNS server is used, until it fails to respond at all within some timeout period. If it fails to respond within that period, the second DNS server is used until it fails to respond within some period. Because 8.8.8.8 almost never fails, **you are only using 8.8.8.8** because you put it first.

Note: none of this has anything to do with Sonoma; it should have been a separate issue.
