### ISSUE TITLE
Broken pipe on 3.8.8.g, downgrading to f fixed it.

### ISSUE THREAD

**Issue by isaiahshiner** [Tunnelblick/Tunnelblick#780]
**Describe the bug**
After connecting to a VPN (I have 3 corporate VPN envs, they all showed this behavior), I can't connect to anything and the logs are spammed with broken pipe messages. 

**To Reproduce**
1. Initiate VPN connection
2. Respond to Okta login request
3. Wait ~20 seconds (a bit longer than normal, but not much)
4. Tunnelblick says "connected" and turns green
5. Attempt to access the internet: nothing. Logs are full of broken pipe messages.

I tried:
 - Restarting tunnelblick
 - Force quitting my corporate firewall program (it restarts, but that can mitigate some issues.)
 - Restarting machine

**Expected behavior**
The connection should work. I should be able to connect to both VPN and non-VPN targets, and not have broken pipe messages.
Downgrading to version 3.8.8.f worked.

**Screenshots**
Snippet of logs, full logs are included in file.
```
11:36:21 *Tunnelblick:  Setting up to monitor system configuration with process-network-changes
11:36:21 *Tunnelblick:  End of output from client.up.tunnelblick.sh
11:36:21 *Tunnelblick:  **********************************************
2023-12-07 11:36:21.279927 Initialization Sequence Completed
2023-12-07 11:36:21.280015 MANAGEMENT: >STATE:1701977781,CONNECTED,SUCCESS,10.100.255.31,35.166.17.42,1194,,
2023-12-07 11:36:22.608265 *Tunnelblick: DNS address 10.100.255.1 is being routed through the VPN
2023-12-07 11:36:22.716196 write UDP: Broken pipe (code=32)
2023-12-07 11:36:22.757394 write UDP: Broken pipe (code=32)
2023-12-07 11:36:22.892423 write UDP: Broken pipe (code=32)
(these continue until I disconnect)
```
[TunnelBlick_broken_pipe_logs.txt](https://github.com/Tunnelblick/Tunnelblick/files/13606671/TunnelBlick_broken_pipe_logs.txt)

**Desktop (please complete the following information):**
 - MacOS Ventura 13.4.1
 - TunnelBlick version 3.8.8.g, which I installed this morning and immediately had problems.
 - Firefox 120.0.1, Chrome 120.0.6099.71 (both 120 huh)
 - Also terminal ping didn't work

**Additional context**

**Comment by jkbullard** [comment]
@isaiahshiner, thanks for your report.

Please post the diagnostic info from a successful connection with 3.8.8f.

Please also try Tunnelblick 4.0.0beta13 to see if that fixes the problem.

Thanks again.

**Comment by isaiahshiner** [comment]
[TunnelBlick_3.8.8.f_success.txt](https://github.com/Tunnelblick/Tunnelblick/files/13607755/TunnelBlick_3.8.8.f_success.txt)

I can give the beta a try tomorrow!

**Comment by jkbullard** [comment]
Thanks, @isaiahshiner. Some observations:

**There is no difference between 3.8.8f and 3.8.8g that should affect connections**. The only difference in the two versions is in the "installer" program which Tunnelblick uses when installing and securing itself and configurations. (The change fixes a crash, which you weren't having, so it is irrelevant anyway.)

There success and failure setups have two different settings for "Set DNS/WINS":
* "failure" uses Tunnelblick's default "Set nameserver" setting which runs `client.up.tunnelblick.sh`.
* "success" uses a setting of "Set nameserver (alternate 1)" which runs `client.3.up.tunnelblick.sh`.

Surprisingly, the "success" setting results in running a script that crashes:

`2023-12-07 15:28:47.521308 WARNING: Failed running command (--route-up): external program exited with error status: 1
`

I don't see anything about why it crashes, though, nor does the script seem to have logged any activity before it crashed.

You might want to play around with the "Set DNS/WINS" setting. Try "Do not set nameserver", too, since it isn't clear that the "alternate 1" setting manages to do anything before the script crashes.

The "Set nameserver" script (among other things) disables IPv6, and I noticed that the "failure" script shows some IPv6 addresses in the routing info. I don't see other evidence of IPv6, though. So try not disabling IPv6 and see if that makes any difference. (Or are the success and failure runs from different networks?)

[This discussion](https://groups.google.com/g/tunnelblick-discuss/c/NmeiQxP7dVg) has some other ideas, among them problems with a firewall, restarting router, restarting computer.

**Comment by isaiahshiner** [comment]
Yep, can confirm. I reinstalled version g and the problem did not come back. Must have been a coincidence. If it comes back I'll try these solutions... or just talk to IT 🤯 

In any case, thank you for your help!

**Comment by jkbullard** [comment]
Thanks for the update.
