### ISSUE TITLE
MFA with mobile/email OTP

### ISSUE THREAD

**Issue by jayprakashkumar1** [Tunnelblick/Tunnelblick#784]
Hi Tunnelblick community :)

I have to implement MFA with mobile/email OTP so I want to send an OTP when we connect to the VPN. So for that, I need to get the server remote IP to send OTP because OTP services are available on that IP itself with different ports.

So How and where in the code can I get the remote server IP which was given in the .ovpn configuration file as a field:
**remote [Server IP]**

Once I get the Server IP I can send OTP and in the 2FA text prompt box I can enter the OTP and then accordingly validation will take place on the server side.

So please help me to get the server remote IP in the code configuration-wise.
Surely It will also help the community if anyone wants to implement such a feature."

Thanks & regards,
Jay

**Comment by jkbullard** [comment]
I don't understand what it is you want to do:
1. Are you trying to connect to a VPN server which requires an OTP for authentication to establish a connection (in addition to a username/password)? There are several ways built into OpenVPN and Tunnelblick to include the OTP in the data it sends to the OpenVPN server – you don't need to do that yourself separately.
Or
2. Are you saying that, _after_ connecting to the VPN (with or without an OTP), you want to send an OTP to the VPN server for some other purpose, using a port on the VPN server that is different from the port used by OpenVPN?
Or
3. Are you saying that, before you connect the VPN, you want to send a request to a non-OpenVPN port on the VPN server so that it will send you an email or text with an OTP for you to use when you try to connect to the VPN? (So you will have a program/script send that request once you have the IP address of the VPN server and before you try to connect to the VPN?)
Or something else?

**Comment by jayprakashkumar1** [comment]
@jkbullard 
Yes point 3 with same server address but on a different port used by the OpenVPN server.
I just want to get the OpenVPN server IP address which is passed in the .ovpn config file as
For example one entry in the .ovpn configuration file:

**remote 192.168.198.71**

So how can I get this Server IP address(192.168.198.71 from the above example )  in the **VPNConnection.m** file in **getResponseToChallenge**?
I don't understand where to get without parsing the configuration file again.
I think this field is already parsed so how can I get it?

Sample configuration file:
client 
dev tun
cipher AES-128-CBC
auth SHA256
key-direction 1
comp-lzo 
persist-key 
persist-local-ip 
persist-remote-ip 
persist-tun 
management 127.0.0.1 9081
pull 
resolv-retry infinite
nobind 
user nobody
group nogroup
verb 4
script-security 3
auth-nocache 
ping-exit 25920000
auth-user-pass
static-challenge "Enter 2FA Authenticator code:" 1
**remote 192.168.198.71**
remote-cert-tls server 
proto tcp
port 9083
inactive 25920000 256
route 192.168.16.0 255.255.255.0 
ping 25920000
...

**Comment by jkbullard** [comment]
@jayprakashkumar1 – You can't parse an arbitrary OpenVPN configuration file to get the IP address of the VPN server because an OpenVPN configuration file can have several "remote" options and you don't know ahead of time which one will be connected. So Tunnelblick doesn't parse the configuration file to get that. (And, of course, the parameter to OpenVPN's "remote" option may be a domain name instead of an IP address, so one would need to resolve that domain name to an IP address.)

For that reason, Tunnelblick itself does not know the VPN server's IP address until a connection is made to a server successfully. That's too late for you because you need the OTP before the connection is made.

If you know that the OpenVPN configuration file contains only one "remote" option and its parameter is an IP address, you can use a Tunnelblick "pre-connect.sh" script to parse the configuration file and make a request to the VPN server for an OTP. See [Using Scripts](https://tunnelblick.net/cUsingScripts.html) for details.

**Comment by jkbullard** [comment]
Tunnelblick scripts, including the "pre-connect.sh" script) are contained within a Tunnelblick VPN Configuration – a .tblk (, see [.tblk Details](https://tunnelblick.net/cPkgs.html#format)). The script will be in the same folder within the .tblk as the OpenVPN configuration file, which will have the name "config.ovpn", so it's easy to access to the configuration file from the script.

**Comment by jayprakashkumar1** [comment]
Thanks, I'll check them out tomorrow and let you know.

Thanks a lot :)

**Comment by jayprakashkumar1** [comment]
@jkbullard 
I have tried reading the configuration file inside .tblk so if the configuration file is installed for 
**Only me** Then I have read the configuration file successfully 
Full Path: 
**/Users/itadmin/Library/Application Support/Tunnelblick/Configurations/ssl_android 5.tblk/Contents/Resources/config.ovpn**

But if the configuration file is installed for 
**All users** then opening the file for reading gives the following access denied error:
**The file “config.ovpn” couldn’t be opened because you don’t have permission to view it.**

Full Path: 
**/Library/Application Support/Tunnelblick/Shared/ssl_vpn_config.tblk/Contents/Resources/config.ovpn**

If I change the permission of the configuration file above shared using chmod then connecting to that configuration file gives the error:
**Configuration xxx is not secure. It should be reinstalled**

So how to read the configuration file that is installed for **all users** as well?

**Comment by jkbullard** [comment]
The pre-connect script runs as the specific user, and doesn't have access to the "all users" configurations because they can contain certificates and other sensitive information.

But a script running as a user can get a "sanitized" copy of the configuration (which does not contain the certificates) and parse that.

To get such a copy, your script should run the `openvpnstart` program located in `/Applications/Tunnelblick.app/Contents/Resources/openvpnstart`. The sanitized contents will be sent to stdout.

The arguments to openvpnstart you should use for an "all users" configuration are

```printSanitizedConfigurationFile     NAME     3```

where `NAME` is the name of the configuration, that is, the part of the path for the configuration file after
```
          /Library/Application Support/Tunnelblick/Shared/
```
and which has `/Contents/Resources/config.ovpn` removed.

For example, for a configuration file at
```
          /Library/Application Support/Tunnelblick/Shared/X/bar.tblk/Contents/Resources/config.ovpn
```
the full command would be
```
/Applications/Tunnelblick.app/Contents/Resources/openvpnstart printSanitizedConfigurationFile X/bar.tblk 3
```

**Comment by jayprakashkumar1** [comment]
@jkbullard 
Thanks a lot :) 
I got it now.

**Comment by jayprakashkumar1** [comment]
Fixed by @jkbullard  Thanks 👍 👍

**Comment by jkbullard** [comment]
I changed the title of this Issue to better reflect what it was about.

**Comment by jayprakashkumar1** [comment]
Ok thanks 👍

**Comment by jayprakashkumar1** [comment]
@jkbullard 
one more thing, How to disconnect VPN connection after NOT receiving OTP. ?
For example I just want to disconnect the ongoing VPN connection if OTP sending request failed(other than status code 200).

**Comment by jkbullard** [comment]
@jayprakashkumar1 – Make your pre-connect script's return value be non-zero. The connection attempt will not be made if the script returns a non-zero status.

Note: when I was double-checking that that the above was correct, I discovered that my earlier comment was wrong, and the pre-connect.sh script is run as root, not as the user. I have edited that comment to correct that, but I don't understand: what script you were using that couldn't access the "all users" configuration file?

**Comment by jayprakashkumar1** [comment]
I run this command to get configuration file content to parse remote ip. so just used this to get the remote ip. 
`/Applications/Tunnelblick.app/Contents/Resources/openvpnstart printSanitizedConfigurationFile X/bar.tblk 3`

**Comment by jkbullard** [comment]
@jayprakashkumar1 — if you’re using a pre-connect script, it can access the configuration file directly because it is running as root. It doesn’t need to use openvpnstart.

**Comment by jayprakashkumar1** [comment]
Ok. but as of now I am using openvpnstart command. So how can I stop vpn
connection at any moment? Just like not receiving the otp

**Comment by jkbullard** [comment]
@jayprakashkumar1 – please see [AppleScript Support](https://tunnelblick.net/cAppleScriptSupport.html).
