### ISSUE TITLE
Apple just released TN3158, is Tunnelblick affected by anything they wrote?

### ISSUE THREAD

**Issue by everlof** [Tunnelblick/Tunnelblick#794]
Apple just release a [technote](https://developer.apple.com/documentation/technotes/tn3158-resolving-xcode-15-device-connection-issues) regarding VPN configurations that could possibly be problematic.

The problem for the end-user is that the Xcode traffic to the iPhone won't go over the USB-cable even if it is connected.

Anyway, just wanted to check if anyone here knows if the current state of Tunnelblick is good in regards to these technote?

**Comment by jkbullard** [comment]
We do not plan on testing Tunnelblick for this because it is the entire environment that must be tested and we can't do that.

But here's my take on the issues the tech note raises:

The tech note says that there are problems with:
 * VPN apps using Packet Filter (PF) rules
 * VPN apps using a Network Extension provider with includeAllNetworks enabled
 * Security configurations using PF

Tunnelblick does not itself use either PF or a Network Extension provider, so none of these are a problem involving Tunnelblick.

However:
 * PF may be being done outside of Tunnelblick;
 * Xcode-iPhone traffic uses IPv6 over a USB interface, so anything that blocks either of those will block Xcode-iPhone traffic.

**Two Tunnelblick settings can block Xcode-iPhone traffic**:
 * **Disable IPv6 unless the VPN server is accessed using IPv6**: If checked and the server is not accessed using IPv6, *no* IPv6 traffic will be allowed when the VPN is active. (Note: the setting blocks _all_ IPv6 traffic, not just traffic through the VPN.)
 * **Disable secondary network interfaces**: If checked, the USB interface between Xcode and the iPhone will be disabled when the VPN is active.

**OpenVPN configuration options can also block Xcode-iPhone traffic**. Options could be either in the OpenVPN configuration file or pushed from the server to the client. The various --route options (--route, --route-gateway, etc.), along with --redirect-gateway and --redirect-private are the most obvious; there may be others. It might be best to ask OpenVPN experts about this.

**Comment by everlof** [comment]
Thank you very much for this reply. This is exactly what I hope for, should be enough for most people using Tunnelblick and Xcode.
