### ISSUE TITLE
Possible to force utun device?

### ISSUE THREAD

**Issue by leadenchopsticks** [Tunnelblick/Tunnelblick#818]
It seems that the utun device that Tunnelblick uses/gets assigned can be quite random. Currently it's utun6 on my Mac but tomorrow it can be utun4 again. In the past I have been able to force it by stating '`dev utun99`' in the config, but that does not seem to work anymore. Is there still a trick to force a specific utun device to be used?

**Comment by jkbullard** [comment]
Please note that it's OpenVPN, not Tunnelblick, that is doing this.

You may need to use `--dev-node utun99`, either along with `dev utun99`, or instead of it.

The [OpenVPN 2.6 man page](https://openvpn.net/community-resources/reference-manual-for-openvpn-2-6/) doesn't specify what macOS does with `--dev utun99`:

> --dev *device*
> 
> On most platforms, tunN (e.g. tun2, tun30) and tapN (e.g. tap3) will create a numbered tun/tap interface with the number specified… Some platforms do not support "numbered tap", so trying --dev tap3 will fail.

But it does specify what macOS does with `--dev-node`, which is what you want:
> --dev-node *node*
> 
> This is a highly system dependent option to influence tun/tap driver selection.
> …
> Under Mac OS X this option can be used to specify the default tun implementation. Using --dev-node utun forces usage of the native Darwin tun kernel support. **Use --dev-node utunN to select a specific utun instance**. To force using the tun.kext (/dev/tunX) use --dev-node tun. When not specifying a --dev-node option openvpn will first try to open utun, and fall back to tun.kext.

It's possible that this changed from the behavior on earlier versions of OpenVPN. If so, then a Tunnelblick update which updated the default version of OpenVPN that is used could have triggered the problem you're having.

**Comment by leadenchopsticks** [comment]
Thanks! I got it working by explicitly stating the following in my config.

```
dev-type tun
dev-node utun99
```

Using only the `dev-node` did not work.

**Comment by jkbullard** [comment]
Thanks for sharing the solution!
